feat(components/Icon): add-specific-case-for-viewbox-size
momentum-design/momentum-react-v2 pull request #172
Opened 2021-12-15 12:12 UTC by mjovicic

# Description
The new svg Icon component forces the viewBox to be "0 0 32 32". For most icons this is fine. However some (like "info-badge-filled" and "error-legacy-badge-filled"), the viewPort in the svg is "0 0 14 14" . When this gets overwritten, the svg is now being drawn with the wrong viewPort, so it appears smaller than it should (14/32 of the size it should be for the two examples). This PR fixes that case.

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281641

2021-12-15 13:21 UTC, torgeadelin commented on src/components/Icon/Icon.tsx
> +  const exceptionIconsList = [
test

2021-12-15 15:46 UTC, InteractiveTimmy requested changes
Great bug find/fix. A few code-style items as well as a request for adding some testing.

2021-12-15 15:46 UTC, InteractiveTimmy commented on src/components/Icon/Icon.tsx
> +  const viewBoxSmall = '0, 0, 14, 14';
These values should be stored in the `Icon.constants.ts` file as something similar to:

```js
const VIEW_BOX_SPECS = {
  NORMAL: '0, 0, 32, 32',
  SMALL: '0, 0, 14, 14',
};

const DEFAULTS = {
  /* ...other defaults... */
  VIEW_BOX_SPEC: VIEW_BOX_SPECS.NORMAL,
};
```

2021-12-15 15:46 UTC, InteractiveTimmy commented on src/components/Icon/Icon.tsx
> +  ];
This should also exist in the `Icon.constants.ts` file, much like the above described `VIEW_BOX_SPECS` constants.

2021-12-15 15:46 UTC, InteractiveTimmy commented on src/components/Icon/Icon.tsx
> +          viewBox={exceptionIconsList.includes(name) ? viewBoxSmall : viewBoxDefault}
Please add an attribute test and a snapshot test for this change within the local test file for this component.

2021-12-15 17:39 UTC, torgeadelin commented on src/components/Icon/Icon.unit.test.tsx
> +    const exceptionIconsList = [
Once you fix @InteractiveTimmy 's suggestions you should probably import the exceptionList from the `.constants.ts` file here.

2021-12-15 17:40 UTC, torgeadelin commented on src/components/Icon/Icon.unit.test.tsx
> +  describe('exception case for small icons', () => {
Also, add one test for a non-exception icon, making sure it has the correct viewbox.

2021-12-15 17:41 UTC, torgeadelin requested changes
Thanks for adding the test.
Small changes are still needed.

2021-12-15 17:42 UTC, torgeadelin commented
> Great bug find/fix. A few code-style items as well as a request for adding some testing.
> 
> This is potentially something that we should have corrected on the design level as well, as all icons should be provided in a standard size.

These icons are only designed for viewport 14 as far as I understood. And they are the only exceptions to the rule. It is due to accessibility issues.

All rest icons are designed at 32 viewport.

2021-12-16 11:00 UTC, mjovicic commented on src/components/Icon/Icon.unit.test.tsx
> +  describe('exception case for small icons', () => {
I have made the adjustments.

2021-12-16 11:00 UTC, mjovicic commented on src/components/Icon/Icon.unit.test.tsx
> +    const exceptionIconsList = [
I have made the adjustments.

2021-12-16 11:00 UTC, mjovicic commented on src/components/Icon/Icon.tsx
> +  ];
I have made the adjustments.

2021-12-16 11:00 UTC, mjovicic commented on src/components/Icon/Icon.tsx
> +  const viewBoxSmall = '0, 0, 14, 14';
I have made the adjustments.

2021-12-16 14:06 UTC, torgeadelin commented on src/components/Icon/Icon.unit.test.tsx
> +  describe('exception case for small icons', () => {
One more thing, please add these tests under `describe('attributes' () => { ...` instead of having them separate.

2021-12-16 18:51 UTC, mjovicic commented on src/components/Icon/Icon.unit.test.tsx
> +  describe('exception case for small icons', () => {
It makes sense, I fixed it.

2021-12-17 14:13 UTC, torgeadelin approved these changes
looks good :)

2021-12-17 15:52 UTC, InteractiveTimmy approved these changes
LGTM! Approved.

2021-12-17 15:54 UTC, merged