test: added react-testing-library and added first demo test
momentum-design/momentum-react-v2 pull request #184
Opened 2021-12-30 19:59 UTC by cscheffauer

# Description

This MR adds React Testing Library to Momentum and a first demo test. This test should showcase how testing with React Testing Library can look like and how easy it can be to write proper tests in comparison to Enzyme. 

Feel free to discuss underneath.

# Links

[React Testing Library](https://testing-library.com/docs/react-testing-library/intro)

2022-01-06 14:38 UTC, InteractiveTimmy requested changes
I really like these changes, mostly non-blocking discussion, but I would like to see the config moved into its appropriate folder, as well as more testing within `<ButtonCircle />` once we all agree on these conventions moving forwards.

2022-01-06 14:38 UTC, InteractiveTimmy commented on jest.config.js
> +  setupFilesAfterEnv: ['<rootDir>/src/helpers/enzyme_setup', '<rootDir>/jest-setup.ts'],
The setup file should be stored within the same scope of the other setup files. e.g. `./src/helpers/jest-setup.ts`, or potentially stored within the `./config` folder.

2022-01-06 14:38 UTC, InteractiveTimmy commented on tsconfig.json
> +    "./jest-setup.ts"
Moving this file into the `./src/helpers/**` folder will prevent this change from being necessary.

2022-01-06 14:38 UTC, InteractiveTimmy commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  expect(screen.getByTitle(buttonTitleMock)).toBeVisible();
This non-mutable approach to testing components allows for a very clear test scope. Since we are not storing the render output of `render(<Component />)` in a mutable variable using `react-testing-library`, we can ultimately only test the final output, and not the internal mutations performed on the **ReactNode**.

This will further prevent unnecessary tests from being written, as we will only test the finalized DOM component.

2022-01-06 14:38 UTC, InteractiveTimmy commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  expect(mockCallback).not.toHaveBeenCalled();
This approach to handling the rendered component without storing a ReactNode removes the need for utils wrapped for `ReactAria`, which further cleans up potentially unnecessary code in this project.

This also prevents tests from directly calling `component.onPress()` or similar event methods to simulate events incorrectly.

2022-01-06 14:38 UTC, InteractiveTimmy commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  userEvent.click(screen.getByRole('button', { name: buttonLabelMock }));
It appears that we also have `hover` events as well that should be tested to confirm that they work along side `ReactAria`. Events available [here](https://testing-library.com/docs/ecosystem-user-event/#pointer-events-options).

2022-01-06 14:38 UTC, InteractiveTimmy commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  userEvent.keyboard('{enter}');
This is a much more direct way of testing keyboard events, which was a testing gap we had. 👍👍👍

2022-01-06 14:51 UTC, cscheffauer commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  userEvent.click(screen.getByRole('button', { name: buttonLabelMock }));
what exact hover events on the ButtonCircle are relevant to test? the onHoverStart, onHoverEnd callbacks for example?

2022-01-06 14:52 UTC, cscheffauer commented on tsconfig.json
> +    "./jest-setup.ts"
will do that whenever we decide using RTL as a way forward! :)

2022-01-10 14:42 UTC, InteractiveTimmy commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  userEvent.click(screen.getByRole('button', { name: buttonLabelMock }));
This is correct, `onHoverStart` and `onHoverEnd`, you can see examples of these events in the testing utils file: `./test/utils.ts`. These are used in `./src/components/ButtonSimple/ButtonSimple.unit.test.tsx`, which `<ButtonCircle />` extends.

2022-01-10 18:06 UTC, cscheffauer commented on src/components/ButtonCircle/ButtonCircle.test.tsx
> +  userEvent.click(screen.getByRole('button', { name: buttonLabelMock }));
thanks - will try adding tests for them :)

2022-12-15 12:56 UTC, closed without merging