feat: create popover component (DRAFT)
momentum-design/momentum-react-v2 pull request #186
Opened 2022-01-06 16:46 UTC by cscheffauer

# Description

This PR adds a new Popover component to the Momentum library, which should act as a replacement for the Overlay trigger, etc. It could potentially replace the legacy popover component as well as the tooltip component.

It uses Tippy.js under the hood to achieve the positioning of the popover and other certain features.

Tests have been done in Storybook, within Chrome & Firefox (more tests in other browsers will follow).
Unit tests - in progress.

# Links

[Tippy.js](https://atomiks.github.io/tippyjs/v6/getting-started/)

2022-01-12 17:05 UTC, torgeadelin requested changes
Looks great so far! 
I'm going to be doing some live testing as well and will leave comments after.

Biggest blocker is the fact that there has been introduced a lot of code duplication around ModalContainer / ContentContainer components. I recommend removing the ContentContainer and reuse ModalContainer.

2022-01-12 17:05 UTC, torgeadelin commented on src/components/Popover/Popover.types.ts
> +  color?: Color;
This type should come from ModalContainer.

2022-01-12 17:05 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +      container.update();
You're not testing the hide

2022-01-12 17:16 UTC, torgeadelin commented
If the trigger on the component is `mousein`, then we automatically need to also have a trigger for `focusin`. This is an accessibility requirement.

2022-01-12 17:20 UTC, torgeadelin commented
When having the popover aligned to bottom-start/end, the arrow should be aligned towards the end, not towards the middle of the trigger.

![image](https://user-images.githubusercontent.com/14194394/149189784-96de5363-2e97-4e6f-9d32-c184f3084be4.png)

2022-01-12 17:23 UTC, torgeadelin commented
I think we also need a delay for displaying a tooltip, especially for `mousein` triggers.

2022-01-12 17:32 UTC, cscheffauer commented on src/components/Popover/Popover.unit.test.tsx
> +      container.update();
right, cause there were issues with the test atm. I will be working on the tests and then also add the hide. Thanks for reminding

2022-01-14 13:22 UTC, cscheffauer commented on src/components/Popover/Popover.types.ts
> +};
removed

2022-01-14 16:30 UTC, InteractiveTimmy requested changes
Some changes to Storybook, a few additional comments.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/ModalArrow/ModalArrow.constants.ts
> +  PLACEMENT: PLACEMENTS.BOTTOM as string,
Should this be `auto`?

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/ModalArrow/index.ts
> +import type { Props } from './ModalArrow.types';
Is there a reason we're adding the `type` keyword?

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/ModalContainer/ModalContainer.stories.args.ts
> +    correctly will only be through the Popover component. Whenever there's the use case
`pls` => `please`

```
<br/><br/>default \`true\``
```

Doesn't need to exist, `argTypes.{prop}.table.defaultValue.summary` does this.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/ModalContainer/ModalContainer.types.ts
> +  placement?: PlacementType;
It may be beneficial to move `ModalArrow` to a compound of `ModalContainer`

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/ModalContainer/index.ts
> +import type { Props } from './ModalContainer.types';
Same as above, unnecessary keyword?

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/Popover/Popover.stories.args.ts
> +        summary: 'true',
Should be stored as a constant, doesn't need to be a string.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/Popover/Popover.stories.args.ts
> +        summary: 'small',
Constant please.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>default \`false\``,
Goes into table.defaultValue.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/Popover/Popover.stories.args.ts
> +      },
defaultValue === unedefined.

2022-01-14 16:30 UTC, InteractiveTimmy commented on src/components/Popover/Popover.stories.args.ts
> +        summary: 'undefined',
Here is the undefined that the above should have.

2022-01-16 21:23 UTC, cscheffauer commented on src/components/ModalContainer/ModalContainer.types.ts
> +  placement?: PlacementType;
I would like to leave it as it is for now, since we haven't used the Compound Component pattern yet and it isn't a convention yet. It would need some training for the team first I think.
We can bring that up in a future conventions meeting and introduce that concept to Momentum 💯

2022-01-16 21:25 UTC, cscheffauer commented on src/components/ModalArrow/index.ts
> +import type { Props } from './ModalArrow.types';
the type keyword is just a visual indicator - it has no effect on Typescript. I have used it before, since it makes it easier to distinguish between a normal import and a type import. I can remove it if that is too confusing :)

2022-01-17 13:02 UTC, torgeadelin commented on src/components/ModalArrow/ModalArrow.constants.ts
> -  wrapper: `${CLASS_PREFIX}-wrapper`,
I think we should always keep the wrapper class even tho we're not using it. It's a good default selector for the component in testing.

2022-01-17 13:20 UTC, cscheffauer commented on src/components/ModalArrow/ModalArrow.constants.ts
> -  wrapper: `${CLASS_PREFIX}-wrapper`,
the arrow doesn't have any wrapper, since it is just a SVG, which gets rendered. That's why I have renamed it to svg to have it named properly.

2022-01-17 13:43 UTC, torgeadelin requested changes

2022-01-17 13:43 UTC, torgeadelin commented on src/components/ModalArrow/index.ts
> +import type { Props } from './ModalArrow.types';
Let's discuss this in the conventions, I think we talked about this in a PR that I had last week.

2022-01-17 13:43 UTC, torgeadelin commented on src/components/ModalContainer/ModalContainer.stories.args.ts
> +    to show ModalContainer with a arrow, pls use the Popover component instead.`,
Still shows pls. Please change it to `please` haha

2022-01-17 13:43 UTC, torgeadelin commented on src/components/ModalContainer/ModalContainer.stories.args.ts
> +    to show ModalContainer with a arrow, pls use the Popover component instead.`,
pls - > please

2022-01-17 13:43 UTC, torgeadelin commented on src/components/ModalContainer/ModalContainer.tsx
> + *
This is the same text as in the docs. Not sure it adds a lot of value to duplicate it here too. Keeping it in both location will increase the maintaining effort.

2022-01-17 13:43 UTC, torgeadelin commented on src/components/ModalContainer/ModalContainer.utils.ts
> + * `undefined` if placement is `undefined`
`undefined` if placement is `undefined` should be on line 12?

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.constants.ts
> +  COLOR: 'primary',
use the constant from ModalContainer.constants.ts

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>Possible event names: \`click\`, \`mouseenter\`, \`focusin\`, \`manual\` (to programmatically trigger the popover)`,
I'm not sure how I feel about the `<br/>`. I think we should let storybook handle the formatting.

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>Possible event names: \`click\`, \`mouseenter\`, \`focusin\`, \`manual\` (to programmatically trigger the popover)`,
Also, if you wrap the string with '' you don't need to escape `\\``

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.stories.docs.mdx
> +The `<Popover />` component allows adding a Popover to whatever provided
`provided as`

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.stories.tsx
> +  placement: 'bottom',
use constant

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.stories.tsx
> +      placement: 'bottom-start',
Constant here too, use it everywhere, I won't leave a comment in all the places.

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.tsx
> +          round={variant === 'medium' ? ROUNDS[75] : ROUNDS[50]}
Why this `variant` prop? Does the design spec only allow 2 variants for Popovers in terms of the border radius?

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.types.ts
> +export interface Props {
I think we have a rule to leave empty space between types here. Not sure if it's enforced by eslint.

2022-01-17 13:43 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +          triggerComponent={<button>Click Me!</button>}
I see why you did this, but the purpose of separating all the attribute tests in tiny individual tests, is to have a better report when tests are failing. If only one is failing, reading it from the console might not be as obvious, because the test is called `should have provided attributes when attributes are provided`, but if we have them separated, will be easy to spot which one is actually failing from the test name.

2022-01-17 13:43 UTC, torgeadelin commented on src/index.js
> +  Popover as PopoverNext,
I think we should export the placements too maybe? Not sure.

2022-01-17 13:46 UTC, cscheffauer commented on src/components/Popover/Popover.tsx
> +          round={variant === 'medium' ? ROUNDS[75] : ROUNDS[50]}
jup - in Figma there are 2 variants of the popover, one small and one medium.

2022-01-17 13:48 UTC, cscheffauer commented on src/components/Popover/Popover.unit.test.tsx
> +          triggerComponent={<button>Click Me!</button>}
testing library does give u a really in depth error message with the line it is appearing and more. So I think with RTL we would need to re-evaluate if splitting these tests is valuable.

2022-01-17 13:49 UTC, cscheffauer commented on src/index.js
> +  Popover as PopoverNext,
i will review that once I'm reusing the Popover component in other places

2022-01-17 13:59 UTC, cscheffauer commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>Possible event names: \`click\`, \`mouseenter\`, \`focusin\`, \`manual\` (to programmatically trigger the popover)`,
multiline doesn't work with ", that's why ` is used and the escape is needed.

2022-01-17 14:01 UTC, cscheffauer commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>Possible event names: \`click\`, \`mouseenter\`, \`focusin\`, \`manual\` (to programmatically trigger the popover)`,
to the <br/> - without it the description would look like this (no line breaks or anything between possible event names and so on:
![image](https://user-images.githubusercontent.com/29776408/149782299-2f3470b2-7e81-4b3d-aab2-b3173540f589.png)

2022-01-17 14:05 UTC, cscheffauer commented on src/components/ModalContainer/ModalContainer.tsx
> + *
will remove it here then, since the docs will be readable by the consumers as well.

2022-01-17 14:08 UTC, cscheffauer commented on src/components/ModalContainer/ModalContainer.stories.args.ts
> +    to show ModalContainer with a arrow, pls use the Popover component instead.`,
![Alt Text](https://media.giphy.com/media/VI9EMXyh4BUHxAP1Fq/giphy.gif)

2022-01-17 14:35 UTC, torgeadelin approved these changes
Looks good to me.
Great work Christopher! 🍻

2022-01-17 16:07 UTC, torgeadelin commented on src/components/Popover/Popover.stories.args.ts
> +    <br/><br/>Possible event names: \`click\`, \`mouseenter\`, \`focusin\`, \`manual\` (to programmatically trigger the popover)`,
I think that's fine tho.

2022-01-18 14:45 UTC, InteractiveTimmy commented on src/components/ModalArrow/ModalArrow.constants.ts
> +  PLACEMENT: PLACEMENTS.BOTTOM as string,
Any comments/details on this?

2022-01-18 15:10 UTC, InteractiveTimmy approved these changes
Looks good to me! thank you for making the changes.

2022-01-18 19:05 UTC, merged