feat: divider dot component
momentum-design/momentum-react-v2 pull request #187
Opened 2022-01-07 23:03 UTC by tallidin

# Description
Divider dot component

![image](https://user-images.githubusercontent.com/82111158/148618225-3e9ad0b2-b6a1-4248-9832-143ec1678d97.png)

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292468

2022-01-07 23:08 UTC, cscheffauer commented on src/components/DividerDot/DividerDot.stories.docs.mdx
> +The `<DividerDot />` component.
Having a documentation here would make sense I think :)

2022-01-10 14:34 UTC, InteractiveTimmy requested changes
Looks good! Just need a common story to demonstrate the usage.

2022-01-10 14:34 UTC, InteractiveTimmy commented on src/components/DividerDot/DividerDot.stories.tsx
> +Example.argTypes = { ...argTypes };
Can a story be inserted that shows this specific use case of this component? i.e. a `Common` story that includes text being divided by the `<DividerDot />`?

2022-01-12 09:15 UTC, cscheffauer approved these changes

2022-01-12 16:05 UTC, InteractiveTimmy approved these changes
LGTM!

2022-01-12 16:05 UTC, InteractiveTimmy commented on src/components/DividerDot/DividerDot.stories.tsx
> +};
Thanks for adding this common example! approved!

2022-01-12 16:06 UTC, merged