task(components/button-group): button-group update to ease use in audio/video controls
momentum-design/momentum-react-v2 pull request #224
Opened 2022-03-29 15:01 UTC by chburket

# Description

Updates were made to the ButtonGroup component to make it easier to use it with the audio/video controls design.
* Added a "compressed" property to compress horizontal space and remove inner borders around ChildNodes
* Added new Compressed and Audio Video Controls stories.
* Updated snaps of components that used ButtonGroup since it added data-compressed={false} to all of them.

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303422

![image](https://user-images.githubusercontent.com/15893389/160640633-8fab8845-1b64-466e-a824-b6525a14fd71.png)
![image](https://user-images.githubusercontent.com/15893389/160641917-22787e0d-3571-42d6-9ccb-84afba22e013.png)

2022-03-29 15:12 UTC, cscheffauer commented on src/components/ButtonGroup/ButtonGroup.stories.args.ts
> +    defaultValue: CONSTANTS.DEFAULTS.SPACED,
i think this might be a copy paste issue ;) i guess it should be `CONSTANTS.DEFAULTS.COMPRESSED` instead (same below for the default value)

2022-03-29 15:16 UTC, chburket commented on src/components/ButtonGroup/ButtonGroup.stories.args.ts
> +    defaultValue: CONSTANTS.DEFAULTS.SPACED,
Doh!

2022-03-29 15:42 UTC, chburket commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +
done

2022-03-31 17:38 UTC, torgeadelin requested changes

2022-03-31 17:38 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.style.scss
> +            padding-left: 0.2rem;
these values are not correct. The distance between the icon and the right border of the button should be 12px (or 0.75rem)

2022-03-31 17:38 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.style.scss
> +            padding-left: 0.2rem;
Ok, i see how this is tricky, because you're setting fixed witdths depending on the size of the buttons inside the button group, you won't be able to exactly match the distance between the icon and the right side of the button group. 

What I would do is, set width to `fit-content` on the button, and add `padding-right: 0.75rem` here.
But not sure if this will work with all the sizes (I'm not even sure we need to support all sizes in this compressed mode)

2022-03-31 17:38 UTC, torgeadelin commented on src/components/ButtonPill/ButtonPill.style.scss
> +    color: var(--videoSupport-controls-button-text);
We can't do that here, button pill needs to have the tokens of button pill. 
I'm starting to think this maybe should be a separate component after-all..., otherwise we need to override the button pill tokens within the button group component (assuming this is used as a video/audio button)

2022-03-31 17:46 UTC, chburket commented on src/components/ButtonPill/ButtonPill.style.scss
> +    color: var(--videoSupport-controls-button-text);
See Natalia's notes in https://github.com/momentum-design/momentum-react-v2/pull/208.

These tokens are temporary. I was just making the outline property match what she had done elsewhere.

2022-03-31 17:48 UTC, chburket commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +
Is there a reason we don't allow comments here?  I found the code for each story ran together without them.

2022-03-31 17:50 UTC, chburket commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +        <ButtonPill outline ghost key="0" size={40} style={{ minWidth: '6.8rem' }}>
That is to simulate how the figma shows the buttons.  Mute and Unmute have a min-width so they don't change widths when toggling.

2022-03-31 17:51 UTC, chburket commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +};
I can remove stories if that's the right thing to do.  Where should I put examples of how the audio-video buttons should work?

2022-03-31 18:04 UTC, chburket commented on src/components/ButtonCircle/ButtonCircle.style.scss
> +      width: 1.31rem;
38 + 1 + 1 (for border) = 40.  Our data-size='40' matches the size of the Figma buttons.

2022-03-31 18:11 UTC, chburket commented on src/components/ButtonCircle/ButtonCircle.style.scss
> +      width: 1.31rem;
I started with .75 compressed width vs uncompressed and then adjusted by eye when the size was visibly unpleasant.  There are no figmas for sizes other then 40, so I made a best-effort.

2022-04-01 11:54 UTC, torgeadelin commented on src/components/ButtonCircle/ButtonCircle.style.scss
> +      width: 1.31rem;
Hmm, seems odd. inspecting the height of the buttons in Figma does show 38 (audio video) and 40 for our existing button pills.

2022-04-01 11:56 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +
If we introduce this, we need to also change the component generation scripts. We have very tight rules for formatting and the way we write code in this database to keep consistency. If you feel like this adds value, we should make a decision as a team if we should include them (and also add corresponding adjustments to the plop scripts)

2022-04-01 11:57 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +};
the stories for audio and video button are really good and should stay here. I'm only referring to the `Compressed ` suite.

2022-04-01 12:00 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.style.scss
> +            padding-left: 0.2rem;
Fair, I think this should be ok for this particular case, altho I like to follow the exact Figma spec for all spacing/sizing etc. If at least one more team member is fine with this then I'm happy with these changes.

2022-04-01 12:01 UTC, torgeadelin commented on src/components/ButtonPill/ButtonPill.style.scss
> +    color: var(--videoSupport-controls-button-text);
Please raise a jira to fix this once the tokens get fixed.

2022-04-03 23:10 UTC, chburket commented on src/components/ButtonCircle/ButtonCircle.style.scss
> +      width: 1.31rem;
I snapshotted figma buttons and my buttons at 100% and examined in photo editor.  They appear to be exactly the same height.

![image](https://user-images.githubusercontent.com/15893389/161452839-c0ee2be7-1333-4fcb-ae9a-6e67b0d36d4a.png)

2022-04-03 23:11 UTC, chburket commented on src/components/ButtonPill/ButtonPill.style.scss
> +    color: var(--videoSupport-controls-button-text);
I'll talk to Natalia and see if she's already opened one for her earlier changes.  If not, I will.

2022-04-04 10:56 UTC, torgeadelin approved these changes
Looking really good, but as mentioned before, I'd like someone else to check the CSS decisions in the PR before merging this.

2022-04-04 14:29 UTC, InteractiveTimmy approved these changes
Changes look good in regards to fulfilling the requirements / design, i do share the same concerns with the obscure sizing [specifically in width: `1.31rem`]. There may be a more refined way to build this component's style sheets, but, this can be revisited later, as the code follows all conventions within its scope.

There could potentially be a `<MediaControls />` component that could be created here if we have time to go back and refactor the full button tree.

2022-04-04 20:41 UTC, chburket commented
I'm going to go ahead and merge this so other audio/video work can get started. I think a new ComboButton? component that pre-composes a PillButton and CircleButton (with down arrow) would be a nice addition and then we could strip out the somewhat odd "compressed" numbers and use it for audio/video controls and other places that need the button + dropdown.

2022-04-04 20:42 UTC, merged