Feat/meeting card container/create
momentum-design/momentum-react-v2 pull request #225
Opened 2022-03-29 20:00 UTC by InteractiveTimmy

# Description

The scope of the changes in this pull request are to create the core `<MeetingCardContainer />` component that will be utilized for all upcoming **Meeting Container** components. This component can be later used as the root for `<MeetingListItem />` container once the **Meeting Container** components are generated.

**Note** - The changes in this pull request also allow for localized CSS Variables to be created to help reduce code footprint and improve readability when multiple variations of a component utilize similar values from our design tokens.

## Screenshots

![Screen Shot 2022-03-29 at 3 58 26 PM](https://user-images.githubusercontent.com/14828820/160696720-29462ee8-47a7-4125-8cd8-5d72b067d881.png)
![Screen Shot 2022-03-29 at 3 57 35 PM](https://user-images.githubusercontent.com/14828820/160696724-4876981b-a197-4888-b3a2-1c1c2bbad6c3.png)
![Screen Shot 2022-03-29 at 3 57 39 PM](https://user-images.githubusercontent.com/14828820/160696726-80f64926-b025-460c-a3b5-c3dc8f53194f.png)
![Screen Shot 2022-03-29 at 3 57 48 PM](https://user-images.githubusercontent.com/14828820/160696728-0be498eb-c39d-49b2-90fd-7790f42817cc.png)
![Screen Shot 2022-03-29 at 3 57 59 PM](https://user-images.githubusercontent.com/14828820/160696729-98fba4f0-7971-42b1-94e8-e8b9422e284d.png)
![Screen Shot 2022-03-29 at 3 58 05 PM](https://user-images.githubusercontent.com/14828820/160696733-63600ddc-22c0-4404-85eb-2fb93b19fdb9.png)
![Screen Shot 2022-03-29 at 3 58 10 PM](https://user-images.githubusercontent.com/14828820/160696734-33affa6f-d570-4f33-a71f-cde07ac0e5bf.png)
![Screen Shot 2022-03-29 at 3 58 16 PM](https://user-images.githubusercontent.com/14828820/160696735-b4a26ec2-6481-47b6-9db3-9f1c6d9696fa.png)
![Screen Shot 2022-03-29 at 3 58 20 PM](https://user-images.githubusercontent.com/14828820/160696736-97838e19-5c9a-4d40-8481-deea9269820e.png)

# Links

[SPARK-313907](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313907)
[Figma Article](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=31674%3A56400).

2022-03-31 13:02 UTC, chburket commented
Nit: the screenshot for status color is showing "rounding = inactive". Is that an old shot?

2022-03-31 13:34 UTC, InteractiveTimmy commented
> Nit: the screenshot for status color is showing "rounding = inactive". Is that an old shot?

This needed to be fixed, but i didn't notice it. Thanks! it's been updated/fixed!

2022-03-31 14:51 UTC, InteractiveTimmy commented
I have updated the naming from `<MeetingCardContainer />` to `<CalendarCard />` to better match the design articles.

2022-03-31 17:19 UTC, chburket approved these changes
Looks good!

2022-03-31 17:43 UTC, torgeadelin requested changes

2022-03-31 17:43 UTC, torgeadelin commented on src/components/CalendarCard/CalendarCard.style.scss
> +  --local-active-background-color: var(--theme-background-secondary-active);
you can't use theme tokens here, you need to create new tokens in the tokens repo for this specific component, release, and use those instead.

2022-03-31 17:48 UTC, torgeadelin commented
Also, still seeing both MeetingCardContainer and CalendarCard in storybook if i run it.

2022-03-31 18:54 UTC, InteractiveTimmy commented on src/components/CalendarCard/CalendarCard.unit.test.tsx
> +      const { container } = render(<CalendarCard />);
the `render()` method returns an object with a `container` key:value pair for testing. This needs to stay `container`.

2022-03-31 18:55 UTC, InteractiveTimmy commented on src/components/CalendarCard/CalendarCard.unit.test.tsx
> +    it('should have child nodes that when children prop is provided', async () => {
Fixed! good catch!

2022-03-31 19:04 UTC, InteractiveTimmy commented on src/components/CalendarCard/CalendarCard.style.scss
> +  --local-active-background-color: var(--theme-background-secondary-active);
Yep! Based on our design flow, I need this to be approved prior to generating the tokens, as if the design approval process here changes, we end up needing to make another PR on the tokens repo unnecessarily. Once approval is complete here, I'll make the changes to the token repo.

2022-03-31 19:08 UTC, InteractiveTimmy commented
> Also, still seeing both MeetingCardContainer and CalendarCard in storybook if i run it.

Not sure why this is, I am not seeing this:

![Screen Shot 2022-03-31 at 3 06 42 PM](https://user-images.githubusercontent.com/14828820/161131003-b8c5b5dd-cb95-4a7f-ae69-4aa4811a2ad5.png)

2022-04-01 15:49 UTC, torgeadelin approved these changes
as discussed in 1:1 you will add the tokens and update this pr

2022-04-05 13:50 UTC, InteractiveTimmy commented
This has been updated to accepted the new tokens in the tokens repo. as well as reflect the new design specifying `card` instead of `calendar card`.

2022-04-05 14:20 UTC, merged