feat(components/SpaceListItem): add-draft-message-icon-indicator-inside-space-list
momentum-design/momentum-react-v2 pull request #231
Opened 2022-04-06 15:57 UTC by mjovicic

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description
 When a user fails/forgets to send a message there is no visible indicator on the space list to notify them that they have a draft .
Here we are adding draft icon indicator which will be shown inside space list for conversation with draft message.

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-320156

2022-04-06 18:14 UTC, InteractiveTimmy requested changes
A few changes around the prop type, and the need for a unit / prop / attribute test.

2022-04-06 18:14 UTC, InteractiveTimmy commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +        summary: '',
Should be `undefined` for `argTypes.draft.table.defaultValue.summary`.

2022-04-06 18:14 UTC, InteractiveTimmy commented on src/components/SpaceListItem/SpaceListItem.types.ts
> +
This appears as though it should be a boolean.

2022-04-06 18:14 UTC, InteractiveTimmy commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +        summary: 'string',
This prop should likely be a `boolean`

2022-04-06 18:14 UTC, InteractiveTimmy commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +    it('should match snapshot with isSelected and draft', async () => {
A props test [unit test] to validate that a specific icon is rendered within this component when `draft === true` is needed. See the `attributes` section of this test file.

2022-04-07 10:22 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +    it('should match snapshot with isSelected and draft', async () => {
I have resolved this.

2022-04-07 10:22 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +      const draft = 'Test Message';
I have resolved this.

2022-04-07 10:22 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +        summary: 'string',
I have resolved this.

2022-04-07 10:22 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +    description: 'Draft Message',
I have resolved this.

2022-04-07 10:22 UTC, mjovicic commented on src/components/Icon/Icon.constants.ts
> +  'draft-indicator-small',
```EXCEPTION_ICONS_LIST``` consists of icon names that have different behavior in terms of view-box model, so in this case I can't change ```draft-indicator-small``` because that is an icon name.

2022-04-07 10:23 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.tsx
> +        return <Icon name="draft-indicator-small" {...iconProps} weight="filled" />;
I have resolve this.

2022-04-07 10:23 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +        summary: '',
I have resolved this.

2022-04-07 14:10 UTC, InteractiveTimmy approved these changes
Looks good to me! one change to the test is needed, will approve after the test is updated.

2022-04-07 14:10 UTC, InteractiveTimmy commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +        .find(Icon)
This test only validates if a non-explicit icon is displayed, we should be more explicit and confirm that an Icon with the props of `icon.props().name === CONSTANTS.EXCEPTION_ICON_LIST[4]` is presented. This should be a sub-10 line change in the test.

2022-04-07 15:41 UTC, torgeadelin requested changes
small changes, looking good otherwise.

2022-04-07 15:41 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +  hasDraft: {
should be `isDraft` to follow the other format of the other props no?

2022-04-07 15:41 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +        .find(Icon)
filtering by `[data-test="icon-name"]` after `.find(Icon)` should be enough.

2022-04-07 15:41 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +        .find(Icon)
`icon.props().name === CONSTANTS.EXCEPTION_ICON_LIST[4]` this is not correct, because the exception_icon list has nothing to do with this component.

2022-04-07 17:55 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.stories.args.ts
> +  hasDraft: {
I have resolved this.

2022-04-08 09:41 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.types.ts
> +  isFileStaged?: boolean;
since it's the same as isDraft, we don't need to add an extra Prop in my opinion. (the icon is the same). That logic `isDraft || isFileStaged` should be in Cantina and not here.

2022-04-08 09:41 UTC, torgeadelin requested changes
Remove the extra prop.

2022-04-08 10:11 UTC, torgeadelin approved these changes
looking good!

2022-04-08 10:34 UTC, merged