Feat/components/tags
momentum-design/momentum-react-v2 pull request #233
Opened 2022-04-11 20:38 UTC by InteractiveTimmy

# Description

The scope of the changes in this pull request are to add the `<Tag />` component.

## Screenshots

![Screen Shot 2022-04-11 at 4 36 46 PM](https://user-images.githubusercontent.com/14828820/162827678-16403a3f-9dc6-40a4-908f-b6594f444e29.png)
![Screen Shot 2022-04-11 at 4 36 51 PM](https://user-images.githubusercontent.com/14828820/162827681-21b22ee5-814d-4b30-848e-27436e420dc9.png)
![Screen Shot 2022-04-11 at 4 36 55 PM](https://user-images.githubusercontent.com/14828820/162827684-4d3395ec-0f2b-4c52-989e-1094fa8bbe30.png)
![Screen Shot 2022-04-11 at 4 37 04 PM](https://user-images.githubusercontent.com/14828820/162827686-6463a669-4af4-4649-b99c-f34a2b500366.png)

# Links

[SPARK-320560](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-320560).
[Figma](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/branch/3AnFAJsgv2FnOkeQejbVUU/Components---Windows?node-id=4931%3A1009).

2022-04-11 22:16 UTC, InteractiveTimmy commented
Due to an IDE error, I didn't catch the issue with `type` as a prop for `button`. I've switched `type` to `format` throughout the component.

2022-04-12 09:23 UTC, torgeadelin requested changes
Looks really good.
One blocking change is that we should probably reuse the team colours in this component as well.

2022-04-12 09:23 UTC, torgeadelin commented on src/components/Tag/Tag.stories.args.ts
> +          .join(' | '),
neat!
![image](https://media.giphy.com/media/ituYMBPySjm9JlVPog/giphy.gif)

2022-04-12 09:23 UTC, torgeadelin commented on src/components/Tag/Tag.style.scss
> +    }
Lol, I kinda like this!
But we should really make a decision wether it's the style we want to adopt going further or not.
This is a good POC of how it works.

We should bring this up on the next MRv2 meeting.

2022-04-12 09:23 UTC, torgeadelin commented on src/components/Tag/Tag.types.ts
> +  | 'violet';
Ditto

2022-04-12 09:23 UTC, torgeadelin commented on src/components/Tag/Tag.unit.test.tsx
> +import userEvent from '@testing-library/user-event';
Again, we have not made an official decision to use RTL.
We should discuss about this in the next meeting.

If we do decide to move over to RTL, the plop scripts need updated.

2022-04-12 14:08 UTC, InteractiveTimmy commented on src/components/Tag/Tag.constants.ts
> +};
These don't overlap in a way that makes them easy to couple [two extra colors, one color that isn't named correctly]. Will be leaving these as is.

2022-04-12 14:08 UTC, InteractiveTimmy commented on src/components/Tag/Tag.types.ts
> +  | 'violet';
These don't overlap in a way that makes them easy to couple [two extra colors, one color that isn't named correctly]. Will be leaving these as is.

2022-04-12 19:06 UTC, InteractiveTimmy commented on src/components/Tag/Tag.style.scss
> +    }
Will note this as an item.

2022-04-12 19:06 UTC, InteractiveTimmy commented on src/components/Tag/Tag.unit.test.tsx
> +import userEvent from '@testing-library/user-event';
Using this here since Enzyme is deprecated.

2022-04-12 19:07 UTC, InteractiveTimmy commented on src/components/Tag/Tag.unit.test.tsx
> +    });
Updated `<ButtonSimple />` to have a class to test inheritance. This created a ton of snapshot updates. This is simply due to the `md-button-simple` class name update.

2022-04-13 14:34 UTC, torgeadelin approved these changes
lgtm!

2022-04-13 15:44 UTC, merged