feat(icons): tooltips for space list icons
momentum-design/momentum-react-v2 pull request #239
Opened 2022-04-26 12:34 UTC by mjovicic

# Description
Currently we do not provide users with tooltip information regarding space list icons on Web. Tooltips are needed for most icons as it is not obvious to the user what they are. This was highlighted after the introduction of the draft indicator.

**OLD IMPLEMENTATION (without tooltip)** 
![tooltip-old](https://user-images.githubusercontent.com/25443019/165300028-59d42699-c64c-4be8-b19c-b82179dce702.gif)

**NEW IMPLEMENTATION (with tooltip)**
![tooltip-new](https://user-images.githubusercontent.com/25443019/165300019-4608f8d9-d677-4483-b64d-6c22e27105a1.gif)

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-323707
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-323825
https://www.figma.com/file/IyTViwqLFPjlbmX84QeQd8/SPARK-320154%3A-Tooltips-for-space-list-icons?node-id=2%3A3)

PR on web-webex-client
https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/2594

2022-05-03 10:57 UTC, torgeadelin requested changes
Some small changes.

2022-05-03 10:57 UTC, torgeadelin commented on src/components/Icon/Icon.constants.ts
> -  'draft-indicator-small',
Why was this removed?

2022-05-03 10:57 UTC, torgeadelin commented on src/components/Icon/Icon.types.ts
> +   * Custom title string on the icon hover.
Should be `Provides accessibility label when icon is hovered.`

2022-05-03 10:57 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.tsx
> +        );
You should probably include the `title: rightIconTooltip` on the object on line 73 to avoid repetition.

2022-05-03 10:57 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.tsx
>          return <Icon name="draft-indicator" {...iconProps} />;
Any reason title is not provided here? I thought this is the exact case that you need to use as part of the work you're doing.

2022-05-03 10:57 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.types.ts
> +   * Right icon tooltip shown on hover
Add a period at the end. `.`

2022-05-04 10:14 UTC, mjovicic commented on src/components/Icon/Icon.constants.ts
> -  'draft-indicator-small',
I have updated the Icon name so I have remove it...but now I realize that it should be defined anyway because it is exception case
I have resolve this.

2022-05-04 10:14 UTC, mjovicic commented on src/components/Icon/Icon.types.ts
> +   * Custom title string on the icon hover.
I have resolve this.

2022-05-04 10:14 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.tsx
> +        );
Good point, I have resolve this.

2022-05-04 10:14 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.tsx
>          return <Icon name="draft-indicator" {...iconProps} />;
I have resolve this.

2022-05-04 10:14 UTC, mjovicic commented on src/components/SpaceListItem/SpaceListItem.types.ts
> +   * Right icon tooltip shown on hover
I have resolve this.

2022-05-04 10:57 UTC, torgeadelin requested changes

2022-05-04 10:57 UTC, torgeadelin commented on src/components/Card/Card.stories.args.ts
> -  },
there's a bunch of changes not related to your PR. make sure you rebase with latest master

2022-05-04 12:13 UTC, torgeadelin approved these changes

2022-05-04 12:13 UTC, torgeadelin commented on src/components/Card/Card.stories.args.ts
> -  },
seems to be fixed now

2022-05-04 12:25 UTC, merged