feature(meeting-container): adds meeting container
momentum-design/momentum-react-v2 pull request #240
Opened 2022-04-29 03:03 UTC by breardon2011

Adds in MeetingContainer for space back and non space backed meetings. 

# Description
A new component was added to handle both space backed and non spacebacked meetings. It extends ButtonSimple and Card. It was implemented in accordance with Figma. 

Card was modified by adding isStatic and isDisabled props to handle the disabled state coming from the MeetingContainer component 

Tests were added to handle new states, snapshot and check for extension of ButtonSimple. 

# Links
[Figma](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/branch/3AnFAJsgv2FnOkeQejbVUU/Components---Windows?node-id=27314%3A50060)

[Space backed Jira](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313910)

[Not Space backed Jira](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313912)

2022-04-29 15:46 UTC, InteractiveTimmy requested changes
Looks great! A few blocking changes around cleaning up comments and constants.

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/Card/Card.unit.test.tsx
> +      expect(component.classList.contains(BUTTON_SIMPLE_CONSTANTS.STYLE.wrapper)).toBe(true);
Good way to validate this!

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.constants.ts
> +  container: `${CLASS_PREFIX}-container`,
This area may need to be cleaned up, I don't think all of these are used in the component.

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.stories.docs.mdx
> +This component displays meeting details and action buttons supplied by the consumer
Great mdx writeup, contains more than enough information to understand the component! good work!

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.stories.tsx
> +// TODO: Provide default arguments for this story here. These populate into the argument table for this component.
We can remove these comments, as they are not necessary after the component is completed. Any comments including `TODO` or `NOTE`, unless explicitly written by yourself to help better-define code, should be removed.

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.tsx
> + *
You can remove this line.

2022-04-29 15:46 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.unit.test.tsx
> +      .exists();
Great overall test coverage!

2022-04-29 18:40 UTC, breardon2011 commented
I also just realized I forgot to put exports in index files initially

2022-04-29 20:55 UTC, InteractiveTimmy requested changes
Looks like you're missing one prop from the argTypes? Correct me if I'm mistaken.

2022-04-29 20:55 UTC, InteractiveTimmy commented on src/components/MeetingContainer/MeetingContainer.stories.args.ts
> +  titleType: {
Looks like you're missing `meetingTitle` prop from the argTypes?

2022-05-02 16:05 UTC, InteractiveTimmy approved these changes
LGTM!

2022-05-02 16:10 UTC, merged