feat(chips): add core chips component
momentum-design/momentum-react-v2 pull request #247
Opened 2022-05-26 09:22 UTC by breardon2011

# Description
Adds the core chips components as described in the figma

*The full description of the changes made in this request.*
Added the chips component with supporting features and tests as shown in the figma 
# Links
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=34401%3A58258

2022-05-26 12:41 UTC, torgeadelin requested changes

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      border-radius: 16px;
use rem

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      border-radius: 16px;
use rem

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    margin-right: 0.313em;
this should be 4px according to Figma so 0.25rem

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    margin-right: 0.313em;
<img width="600" alt="image" src="https://user-images.githubusercontent.com/14194394/170507406-404e3b9e-b5ee-4e2b-b94e-8be69bf44af4.png">

When looking for measurements around icons, make sure you select the actual icon component (see left side) and not the vector. The vector is slightly smaller than the viewbox of the actual icon.

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    margin-left: 0.215em;
In terms of margin-left again it's a different value.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/14194394/170507824-a90444ef-3225-4d27-a8bd-8e5ad21ad95d.png">

I'm assuming you tried to calculate the total based on the padding of the button which you define in line 2.

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    margin-right: 0.243em;
Same for this. (see above comments regarding spacing)

2022-05-26 14:59 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +button {
Also general note regarding EM, i think you should use REM in this case -- in the design spec we only have one variant in terms of size, so it doesn't really make sense to have EM in that case. the parent/base button which the chip is based on will always have the same size.

2022-05-26 17:50 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +  }
yeah i wasnt sure about that, i reasoned that it didnt say it was static, itd be easy to change though

2022-05-26 17:56 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +
I can attach an id or something too if that doesnt work, honestly meant to change the button{} before pushing but forgot about it, thanks

2022-05-26 17:57 UTC, breardon2011 commented on src/components/Chip/Chip.tsx
> +        <div data-avatar={!!avatar} className={STYLE.left}>
yeah i was gonna say, I probably chose too generic considering legacy, thats easy

2022-05-26 17:59 UTC, breardon2011 commented on src/components/Chip/Chip.unit.test.tsx
> +    });
that makes sense

2022-05-26 18:23 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    margin-left: 0.215em;
yeah weirdly, i couldnt see the view where it shows the 16x16 (vs the actual icon outline) in the figma, now I see it though, that'll be a lot easier.

2022-05-26 18:28 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    margin-right: 0.313em;
this was the issue LOL, I couldnt figure out why there was discrepancy, in the setup ive used in the past it was sort of abstracted in a way there was only one thing to select

2022-05-26 20:20 UTC, breardon2011 commented on src/components/Chip/Chip.stories.tsx
> +const exampleAvatar = <Avatar size={24}>AA</Avatar>;
👍

2022-05-26 20:21 UTC, breardon2011 commented on src/components/Chip/Chip.stories.tsx
> +// TODO: Provide default arguments for this story here. These populate into the argument table for this component.
👍

2022-05-26 20:21 UTC, breardon2011 commented on src/components/Chip/Chip.stories.tsx
> +// NOTE: Primary story. This renders a single component with all external props.
👍

2022-05-26 20:28 UTC, breardon2011 commented on src/components/Chip/Chip.tsx
> +
👍

2022-05-26 20:38 UTC, breardon2011 commented on src/components/Chip/Chip.tsx
> +    error = false,
👍

2022-05-26 20:40 UTC, breardon2011 commented on src/components/Chip/Chip.tsx
> +        <div data-avatar={!!avatar} className={STYLE.left}>
👍

2022-05-26 20:41 UTC, breardon2011 commented on src/components/Chip/Chip.unit.test.tsx
> +    /* ...additional snapshot tests... */
👍

2022-05-26 20:59 UTC, breardon2011 commented on src/components/Chip/Chip.unit.test.tsx
> +    /* ...additional attribute tests... */
👍

2022-05-26 20:59 UTC, breardon2011 commented on src/components/Chip/Chip.unit.test.tsx
> +  });
👍

2022-05-26 22:17 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +  width: fit-content;
👍

2022-05-26 22:21 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    padding: 0em;
👍

2022-05-26 22:21 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    white-space: nowrap;
👍

2022-05-26 22:25 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +      border-radius: 16px;
👍

2022-05-26 22:26 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +      border-radius: 16px;
👍

2022-05-27 01:52 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    padding: 0em;
I tested and actually text lengths doesn't impact, but shrink 0 did mess up the positioning, so I'll leave it out

2022-05-27 01:55 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    white-space: nowrap;
it does rely on this, it stacks without it

2022-05-27 11:00 UTC, torgeadelin requested changes

2022-05-27 11:02 UTC, torgeadelin commented on src/components/Chip/Chip.tsx
> +    error = false,
you still haven't used the defaults when deconstructing the props

2022-05-27 11:03 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +  }
They have mentioned that hover and press state should be the same as errored state. see comment on figma

2022-05-27 11:03 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    margin-right: 0.313em;
yeah, it's weird. took me a while to figure it out haha

2022-05-27 15:23 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    padding-right: 0.625rem;
oh yeah dropping nowrap definitely works now without the classes overlapping

2022-05-27 15:51 UTC, torgeadelin commented on src/components/Chip/Chip.constants.ts
> +  centerSection: `${CLASS_PREFIX}-centerSection`,
Don't kill me but use kebab case instead of camel case

2022-05-27 15:51 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +  }
The hover/active is still not fixed.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/14194394/170734576-785d6d18-c8c3-4ab9-b8cb-84973776823b.png">

2022-05-27 16:00 UTC, torgeadelin requested changes
one more fix and should be good to go!

2022-05-27 16:58 UTC, breardon2011 commented on src/components/Chip/Chip.constants.ts
> +  centerSection: `${CLASS_PREFIX}-centerSection`,
no you're right on that, just too much NextStepCase training lol

2022-05-30 08:57 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    pointer-events: none;
Why was this added?

2022-05-30 10:18 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +    pointer-events: none;
Oh, I see why. I'm afraid this is not what we want. Adding this will make the chip not clickable when in error state. It is true, it no longer has hover and press states but we still want it to be clickable. 

You should be able to select the &[data-error='true'] + the hover and press states with something like this 
```css
&[data-error='true'], &[data-error='true']:hover, &:&[data-error='true']:press {
  //common style for errored state
}
```

2022-05-30 22:45 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +    pointer-events: none;
ahh, I had wondered as I was making it, makes sense

2022-05-31 09:17 UTC, torgeadelin approved these changes
Looking good now. Thank you for addressing all the comments!

2022-05-31 15:47 UTC, merged