feat: added text-toast component
momentum-design/momentum-react-v2 pull request #250
Opened 2022-06-01 15:51 UTC by cscheffauer

# Description

Added Text Toast component as defined in the Figma link below. This is a precondition for the TemporaryUnmute toast.

# Links

Figma: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44750%3A103463

2022-06-02 14:02 UTC, InteractiveTimmy requested changes
A few changes to improve refactor protection, some around JSDoc, and then some around style assignments.

Only real blocking change is that it's not exported at the root `src/index.js` file.

2022-06-02 14:02 UTC, InteractiveTimmy commented on src/components/TextToast/TextToast.types.ts
> +   * Default: `undefined`
same as above.

2022-06-02 14:02 UTC, InteractiveTimmy commented on src/components/index.ts
> +export { default as TextToast } from './TextToast';
Are you missing the export on `src/index.js`?

2022-06-02 14:09 UTC, InteractiveTimmy requested changes

2022-06-02 14:09 UTC, InteractiveTimmy commented on src/components/TextToast/TextToast.constants.ts
> +  ALIGNMENT: 'center' as TextToastTextAlign,
This will prevent the need for type-casting.

2022-06-07 10:51 UTC, torgeadelin approved these changes
Looking great!

2022-06-07 13:49 UTC, merged