feat(checkbox): add checkbox component
momentum-design/momentum-react-v2 pull request #255
Opened 2022-06-08 19:00 UTC by nataliadelmar

# Description

Add the Checkbox component as defined in the Component Library.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/56999622/172695611-5fc0195f-e6c4-49bc-bf65-b683e2731d5c.png">

# Links

[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=40300%3A80462)

2022-06-09 10:48 UTC, maxinteger requested changes
Added few comments for the tests and a suggestion for additional data- attributes

2022-06-09 10:48 UTC, maxinteger commented on src/components/Checkbox/Checkbox.tsx
> +      <label className={classnames(STYLE.wrapper, className)} data-disabled={isDisabled}>
I think you should add `data-selected` and `data-indeterminate` attributes as well

2022-06-09 10:48 UTC, maxinteger commented on src/components/Checkbox/Checkbox.unit.test.tsx
> +    });
Do we need these tests? They are checking the same thing as the snapshot tests

2022-06-09 10:48 UTC, maxinteger commented on src/components/Checkbox/Checkbox.unit.test.tsx.snap
> +    style={
something wrong with the snapshots 

for example here the `{display: "block"}` should not be added to the label and the className form the props is missing

it is might be because of the icon loading asynchronously the svg file
try to use `mountAndWait` instead of `mount` in the snapshot tests

2022-06-09 14:56 UTC, torgeadelin requested changes
Looking good, a few bugs and things that need changing tho.
Also, needs testing :P

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.stories.args.ts
> +        summary: 'undefined', // NOTE: Default value for this prop.
Remove comments

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.style.scss
> +      }
![Uploading image.png…]()

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +        {label && <Text className={STYLE.label}>{label}</Text>}
Remove the `<Text>` component, the `label` tag only allows inline blocks inside. It should be sufficient to add the label styling on the label itself (i think you already have the font family, just add the correct size and text color in there)

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +        {label && <Text className={STYLE.label}>{label}</Text>}
Not sure if they need to be tokenised?

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +        {!selected && !indeterminate && <div className={STYLE.notSelected} />}
Could be simplified in

```js
{(selected || indeterminate) 
  ? <div className={STYLE.selected}>{icon}</div>
  : <div className={STYLE.notSelected} />
}
```
}

```

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.style.scss
> +.md-checkbox-wrapper {
We also need `width: fit-content`, otherwise, the label will grow on the whole line and you'd be able to toggle the checkbox when clicking far away from the label. See pic: 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/14194394/172876235-537be464-193a-4653-b393-3cf305cc42e7.png">

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +    <FocusRing>
FocusRing doesn't really work here, because the focus spec is a bit complicated, and it is only around the rectangle, and since we are not using the native html element for checkbox (which does that), we need to manually implement the focus using ` useFocusRing()` from Aria. There's an example on how to do it [here](https://react-spectrum.adobe.com/react-aria/useCheckbox.html)

2022-06-09 14:56 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.types.ts
> +  children?: ReactNode;
Remove

2022-06-21 15:49 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.stories.tsx
> +    },
storybook is now broken
<img width="399" alt="image" src="https://user-images.githubusercontent.com/14194394/174842845-3cc84f4d-7b94-4d71-bfc0-7958331b238f.png">

2022-06-21 16:00 UTC, torgeadelin requested changes
Few more small changes, but looking great!

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.stories.args.ts
> +  children: {
i still see it?

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.style.scss
> +  font-size: 1rem;
no need if you're using Text

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +  const ref = React.useRef();
Might be worth adding forward ref, see `ListItemBase` on how we do it.

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +  });
Why did you add this?

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +  });
`inputProps` returned by `useCheckbox` should already handle this

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +    <div>
no need for the extra div

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.tsx
> +  const { children, className, isSelected, disabled, isIndeterminate, ...rest } = props;
you should grab `label` prop instead of children for the label. Toggle component does that, so we should follow the same pattern maybe. (#259)

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.types.ts
> +  /**
add newline

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.unit.test.tsx
> +    it('should match snapshot with not selected checkbox', async () => {
Add one test with selected as well

2022-06-21 16:00 UTC, torgeadelin commented on src/components/Checkbox/Checkbox.unit.test.tsx
> +  describe('actions', () => {
Add test for space key interaction, see example here #259

2022-06-21 16:00 UTC, torgeadelin commented on src/components/ThemeProvider/ThemeProvider.style.scss
> +  --md-globals-focus-ring-box-shadow-accent: 0 0 0 0.0625rem
Why did you add this? is it because it's different in figma than the one we currently have?
Has this changed everywhere maybe? Can you check? If yes, we just need to update the existing one on line 134

2022-06-22 17:07 UTC, torgeadelin approved these changes
Looks really great!

2022-06-23 10:07 UTC, maxinteger requested changes
I added few minor comments

2022-06-23 10:07 UTC, maxinteger commented on src/components/Checkbox/Checkbox.tsx
> +  const selected = isSelected || state.isSelected || DEFAULTS.IS_SELECTED;
I do not think we need any default value here

you can remove these lines

You can replace everywhere the `isSelected` with `state.isSelected` because `useToggleState` gets the all the props and it is using the `isSelected`

2022-06-23 10:32 UTC, maxinteger commented on src/components/Checkbox/Checkbox.tsx
> +import { useCheckbox } from 'react-aria';
The build is failing because you import the whole `react-aria` instead of `@react-aria/checkbox`

Not sure what is the root cause of this error tho. We might have incompatible versions of the react-aria in the project. But we can investigate that in another story

2022-06-23 13:08 UTC, merged