feat(toggle): add toggle component
momentum-design/momentum-react-v2 pull request #259
Opened 2022-06-10 19:02 UTC by maxinteger

# Description

Add the Toggle component as defined in the Component Library.

![image](https://user-images.githubusercontent.com/983050/173132545-36454a89-09cf-4fcb-8f17-f76b3b2ca22a.png)

# Links

[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=40297%3A97282)

2022-06-10 19:12 UTC, maxinteger commented on src/components/Toggle/Toggle.stories.tsx
> +export { Example, Common };
Anybody knows why Storybook shows the "Example" story under both exported stories?

If I change the order then I can see the "Common" in both case but not the Examples

2022-06-15 14:40 UTC, cscheffauer commented on src/components/Toggle/Toggle.stories.tsx
> +export { Example, Common };
will double check

2022-06-15 14:40 UTC, cscheffauer commented
@maxinteger the build is failing - pls check why :)

2022-06-15 14:42 UTC, cscheffauer commented on src/components/Toggle/Toggle.style.scss
> +  $switch-height: math.div($switch-width, 2);
is this a requirement? that the height is half of the width?

2022-06-15 14:43 UTC, cscheffauer commented on src/components/Toggle/Toggle.style.scss
> +  $transition-time: 350ms;
where is this coming from? was this defined in figma somewhere? :) i haven't been working with css animations in Momentum yet, so I'm curious how that has been defined.

2022-06-15 14:47 UTC, cscheffauer commented on src/components/Toggle/Toggle.unit.test.tsx
> +      expect(input.hasAttribute('checked')).toBe(true);
since we have jest-dom from testing-library extended, you could also simply do:
```typescript
expect(input).toBeChecked();
```

2022-06-15 14:48 UTC, cscheffauer commented on src/components/Toggle/Toggle.unit.test.tsx
> +  });
in terms of confidence I think keyboard events would be also nice to be tested.

2022-06-15 14:50 UTC, cscheffauer commented on yarn.lock
> +"@react-aria/focus@^3.6.0":
I believe these changes here were not meant to be made (I guess that happened when running yarn in the repository). Could be probably removed (but I don't know exactly how we deal with this normally).

2022-06-15 14:54 UTC, cscheffauer commented on src/components/Toggle/Toggle.stories.tsx
> +export { Example, Common };
i'm not experiencing that - there might be a storybook caching issue, which could be resolved by running:
`yarn storybook:start --no-manager-cache`

2022-06-15 14:57 UTC, cscheffauer commented on src/components/Toggle/Toggle.tsx
> +  const { id, className, style, isDisabled, label } = props;
ah sorry - found it - there is a onChange type

2022-06-15 14:58 UTC, maxinteger commented on src/components/Toggle/Toggle.style.scss
> +  $switch-height: math.div($switch-width, 2);
based on the figma design, yes
the width of the toggle is double of the height I can not see any reason why it should change in any circumstances

2022-06-15 14:59 UTC, cscheffauer commented on src/components/Toggle/Toggle.stories.tsx
> +  const [isSelected, setIsSelected] = useState(props.isSelected);
this is awesome, but it's not really visible in the story. It would be great to fire a "onChange" action on the actions tab in storybook. To make that work, pls check other stories and how they do it:
![image](https://user-images.githubusercontent.com/29776408/173859687-8c6bc03b-7ca3-4c62-8120-405dc40c0f4a.png)

2022-06-15 14:59 UTC, maxinteger commented on src/components/Toggle/Toggle.style.scss
> +  $transition-time: 350ms;
I got it from the Legacy toggle button, but probably I should check with the UX team

2022-06-15 15:34 UTC, maxinteger commented on yarn.lock
> +"@react-aria/focus@^3.6.0":
Yes, I used wronger version of react-switch

2022-06-15 15:36 UTC, maxinteger commented on src/components/Toggle/Toggle.tsx
> +  const { id, className, style, isDisabled, label } = props;
the `onChange` is inherited from the `AriaToggleProps` and it is managed by the `useToggleState` hook
You can see an example in the last unit test

2022-06-15 16:22 UTC, cscheffauer commented on src/components/Toggle/Toggle.style.scss
> +  $transition-time: 350ms;
I would check that with @nataliadelmar if thats fine or not :)
I don't mind having good looking animations, but it depends on the spec really.

2022-06-21 15:03 UTC, torgeadelin commented on src/components/Toggle/Toggle.style.scss
> +  $transition-time: 350ms;
it's ok to leave it, better than nothing i guess?

2022-06-21 15:25 UTC, torgeadelin requested changes
A few comments, but looking really great!

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.constants.ts
> +  focused: `${CLASS_PREFIX}--focused`,
i don't think we should use double dashes. you're probably borrowing the concept from [BEM](https://en.bem.info/methodology/) but we don't really have that as a convention in this repo.

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.stories.tsx
> +// NOTE: Primary story. This renders a single component with all external props.
Remove coomment

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.stories.tsx
> +// NOTE: Common variants story. This renders multiple variants of a single component.
Remove

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.stories.tsx
> +// NOTE: Export stories here. The first export should be `Example`, and the last export should be `Common`.
Remove

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.tsx
> +  const ref = React.useRef();
Might be worth adding ForwardRef as well. Look at `ListItemBase` component as an example on how we handle this.

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.types.ts
> +   * Boolean to describe when toggle is on/off
Might be worth mentioning that this is a prop that will control the component externally. Ie, if it's set to true, and you click on it, state wouldn't change.

2022-06-21 15:25 UTC, torgeadelin commented on src/components/Toggle/Toggle.tsx
> +  const children = label && <span className={STYLE.label}>{label}</span>;
In terms of the label, the spec doesn't really show any so not sure we need this.
I've asked a question, please continue the conversation with design team on this here: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp?node-id=46518:104139#214980864

2022-06-29 09:09 UTC, maxinteger commented on src/components/Toggle/Toggle.tsx
> +    <label
Note: this component does not have `label` prop (see [Figma discussion](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=46518%3A104139#214985832)), but we need the `<label>` tag to handle accessibility. The only issue is the user of the component might wrap Toggle into another `<label>`. 
As far as I know label can not contain another label, but I tried in Chrome and it did not cause any issue.

If we want to remove the label then we have to remove the input as well, and implement a completely custom input component.

2022-07-01 09:37 UTC, cscheffauer commented on src/components/Toggle/Toggle.stories.tsx
> +const componentStateToProps = (state) => {
why is this necessary?

2022-07-01 09:44 UTC, cscheffauer commented on src/components/Toggle/Toggle.unit.test.tsx
> +  });
I think what would be nice here as well is a focus. So that u do `userEvent.focus` and then you do a `expect(input).toBeFocused()`.

Also I would recommend a test with disabled state, where u set the Toggle to disabled and then u try to do the focus again and it shouldn't work. Also pressing space key or clicking shouldn't work on disabled.
With that we have more confidence that it works just as the user would use it :)

2022-07-05 17:47 UTC, torgeadelin approved these changes
Looking good!

2022-07-06 13:18 UTC, cscheffauer commented on src/components/Toggle/Toggle.style.scss
> +        background-color: var(--togglemomentumstyle-toggled-thumb-tint-disabled);
is that the name from the Tokens library? togglemomentumstyle ? that is sounds odd to me
@torgeadelin @nataliadelmar

2022-07-06 13:19 UTC, cscheffauer commented on src/components/Toggle/Toggle.tsx
> +  const state = useToggleState(props);
`isSelected` could be destructured here already

2022-07-06 13:24 UTC, cscheffauer approved these changes

2022-07-06 14:04 UTC, maxinteger commented on src/components/Toggle/Toggle.style.scss
> +        background-color: var(--togglemomentumstyle-toggled-thumb-tint-disabled);
I created a PR to fix the variable names
https://github.com/momentum-design/tokens/pull/230

2022-07-15 13:06 UTC, merged