feat(chips/modifiers): Add modifiers to chips
momentum-design/momentum-react-v2 pull request #260
Opened 2022-06-13 07:09 UTC by breardon2011

# Description
Add modifiers to the chips to support the search and multiline modifier as described in the figma and their corresponding supported sizes. 

# Links

[figma](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44750%3A103435)

2022-06-14 10:08 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
>        border-color: var(--theme-outline-cancel-normal);
this should come from the component tokens, not theme

2022-06-14 10:08 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
>        border-color: var(--theme-outline-primary-normal);
this should come from the component tokens, not theme

2022-06-14 10:11 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      padding: 0rem 0.438rem;
suspicious value

2022-06-14 10:11 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
wrong font, we're not using that in the web library. we already set the font in the ThemeProvider so no need to write it here

2022-06-14 10:11 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +        padding: 0.063rem 0.5rem;
suspicious value

2022-06-14 10:12 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      padding: 0rem 0.406rem;
suspicious value

2022-06-14 10:12 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
remove

2022-06-14 10:18 UTC, torgeadelin commented on src/components/Chip/Chip.tsx
> +  const textStyle = search && size === 24 ? { fontSize: '.875rem', fontWeight: 600 } : undefined;
instead of this, you can use the already defined `types` we have on the `<Text/>` component.
https://momentum-design.github.io/momentum-react-v2/?path=/story/momentum-ui-text--types

if you hover on the typography in Figma, you'll see what type you need
<img width="313" alt="image" src="https://user-images.githubusercontent.com/14194394/173554683-d295631f-c1af-4cef-84b1-2e95d75281be.png">

2022-06-14 10:20 UTC, torgeadelin commented on src/components/Chip/Chip.tsx
> +  const textStyle = search && size === 24 ? { fontSize: '.875rem', fontWeight: 600 } : undefined;
so you can do something like `<Text type={search ? 'subheader-secondary': 'another-type'}/>`. You'd have more logic here tho, because it also depends on the size.

After doing this you can remove all type related css properties from the css file. The `<Text/>` component will have this based on the `type` prop.

2022-06-14 10:20 UTC, torgeadelin commented on src/components/Chip/Chip.tsx
> +        data-multiline={multiline}
this doesn't really work, tried to use it in storybook and i see this.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/14194394/173555201-202e17c6-749d-4e12-9ac6-2ec379a8abd3.png">

2022-06-14 10:25 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
>      padding: 0em 0.625rem;
rem

2022-06-14 10:25 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      border: 0.063rem solid;
suspicious value

2022-06-14 18:44 UTC, breardon2011 commented on src/components/Chip/Chip.tsx
> +  const textStyle = search && size === 24 ? { fontSize: '.875rem', fontWeight: 600 } : undefined;
Yeah I struggled with what was the cleanest, most easy to understand way to manage the variations in play, I dont mind doing it this way

2022-06-14 18:45 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
Hmm I guess I'm curious why they specify it in the figma, but will remove for sure

2022-06-14 18:46 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
>        border-color: var(--theme-outline-cancel-normal);
ah ok, I was sort of unclear on how the tokens are used here

2022-06-14 18:48 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
> +      border: 0.063rem solid;
A note on the variations, the multicolor chips is put on hold because the UI colors did not exist, so only the modifiers will be submitted, the only color tokens I created were for multiline etc. There is a separate blocked jira for the multicolor chips

2022-06-14 23:32 UTC, breardon2011 commented on src/components/Chip/Chip.style.scss
>        border-color: var(--theme-outline-cancel-normal);
Made a tokens pr to add https://github.com/momentum-design/tokens/pull/220

2022-07-05 15:40 UTC, InteractiveTimmy requested changes
Seems to be a missing test for `size`, needs the variants to be inclusive of the full list of new colors.

2022-07-05 15:40 UTC, InteractiveTimmy commented on src/components/Chip/Chip.stories.tsx
> +    },
As Catalin mentioned, this should be done as its own sub-story: `ChipColors`. This can easily be done by iterating over the `CHIP_CONSTANTS.MULTILINE_COLORS` [or similar const] in the variants with a map:

```js
ChipColors.parameters = {
  variants: CHIP_CONSTANTS.MULTILINE_COLORS.map((color) => ({children: `chipColor = ${color}`, chipColor: color})),
}
```

2022-07-05 15:40 UTC, InteractiveTimmy commented on src/components/Chip/Chip.unit.test.tsx
> +    });
It appears a `size` test may be missing.

2022-07-11 11:17 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
it's in figma because you're most likely looking at the [Windows Library](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=0%3A1) and not the [Web](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=0%3A1) BUT, the windows does tend to be more up to date. I usually check both 🤷🏻‍♂️

But as a note, you should never have to write any typography (99.9% of the time) because these come from the Text component or are there by default (from the ThemeProvider). 

In terms of size and weight, yes, you might need to adjust those, bug again, if you use `Text` component the font, weight and size will automatically be set to the correct values and you'll only need to figure out the `type` property, which usually is in Figma if you hover over the `Ag` property in the Typography section on the right hand side. 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14194394/178252752-bffa59e8-000e-4487-a354-5b1f3a3b5ae8.png">

*to see the whole name hover over the value of `Ag` and it'll show. In the example the correct type is `body-primary`.

2022-07-11 11:41 UTC, torgeadelin commented on src/components/Chip/Chip.style.scss
> +      border: 0.063rem solid;
thanks for explaining this!

2022-07-11 11:48 UTC, torgeadelin approved these changes
Looking great! thanks for addressing all the comments :D

2022-07-13 17:38 UTC, InteractiveTimmy approved these changes
LGTM! Thanks for addressing the comments!

2022-07-14 16:02 UTC, merged