feat(notification-toast): add notification toast component
momentum-design/momentum-react-v2 pull request #265
Opened 2022-06-21 15:51 UTC by nataliadelmar

# Description

Adding Notification Toast component to the library as seen in Figma.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/56999622/174843409-51d99415-1976-4bb3-bff8-dd0c13b39170.png">

https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=36552%3A55990

# Links

*Links to relevent resources.*

2022-06-21 16:10 UTC, Coread commented on src/components/ToastNotification/ToastNotification.style.scss
> +    padding-right: 0.1rem;
question: I always ask when I see non-pixel sized rem values. Is the right padding really 0.1rem here? That is 1.6px

2022-06-21 16:23 UTC, Coread approved these changes
Looks good, just check on the padding value and that unused import before merge

2022-06-21 16:50 UTC, torgeadelin approved these changes
Approving so in case I'm not here, it doesn't block you but i'd like for you to add the additional tests.

2022-06-21 16:50 UTC, torgeadelin commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +    });
you forgot to add tests for leadingVisual, buttons and onClose

2022-06-22 09:58 UTC, maxinteger requested changes
Few minor spacing problems and some chages for handling component actions in the story

2022-06-22 09:58 UTC, maxinteger commented on src/components/ToastNotification/ToastNotification.style.scss
> +    padding-top: 0.25rem;
based on the figma it should be 0.75rem between the text and the button group but the gap is only 0.5rem at the moment

2022-06-22 09:58 UTC, maxinteger commented on src/components/ToastNotification/ToastNotification.style.scss
> +.md-toast-notification-wrapper {
it should be 1rem padding on all sides, but it is only 0.5rem. Even if I add the leading visual, text or the button group paddings it is still just 0.75rem

2022-06-22 09:58 UTC, maxinteger commented on src/components/ToastNotification/ToastNotification.stories.tsx
> +  onClose: () => {
instead of this you can add the `onClose` to the `argTypes` like this:
```ts
export default {
   ...commonStyles,
   ...toastNotificationArgTypes, 
   onClose: { action: 'closed' },
}
```

this way you can utilise the "Actions" tab in Sotrybook and you can remove all the `onClose` handlers from this file

2022-06-22 09:58 UTC, maxinteger commented on src/components/ToastNotification/ToastNotification.types.ts
> +  text?: string;
text prop should be required

2022-06-23 14:46 UTC, maxinteger requested changes
minor style problems

2022-06-23 14:46 UTC, maxinteger commented on src/components/ToastNotification/ToastNotification.style.scss
> +.md-toast-notification-wrapper {
The left and bottom padding of the wrapper is good now, but the top and right padding are still small

2022-06-23 15:49 UTC, merged