feat(popover): add close btn and focusBackOnTrigger
momentum-design/momentum-react-v2 pull request #273
Opened 2022-07-13 11:41 UTC by torgeadelin

# Description
- Added `closeButtonPlacement` to configure the popover to have a close button (`top-left' | 'top-right' | 'none'`)
- Added `focusBackOnTrigger` to configure the popover to focus back on trigger on close
- Added `closeButtonProps` to support the `closeButtonPlacement` and give flexibility to add accessibility props on the close button (aria label, title, translation etc)

# Screenshots
<img width="326" alt="image" src="https://user-images.githubusercontent.com/14194394/178725498-70ee9f07-e80e-4ed5-a5d3-b1aa9c5bbafd.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/14194394/178725536-e05b465a-e9c1-482c-aaa3-b7f9a7038e38.png">

2022-07-13 13:53 UTC, maxinteger requested changes

2022-07-13 13:53 UTC, maxinteger commented on src/components/Popover/Popover.constants.ts
> +const CLOSE_BUTTON_PLACEMENTS: Record<string, string> = {
Please remove `Record<string, string>` because it define a much wider type than what we need.
TS can infer the best type for `CLOSE_BUTTON_PLACEMENTS`

2022-07-13 13:53 UTC, maxinteger commented on src/components/Popover/Popover.stories.args.ts
> +    options: [...Object.values(CLOSE_BUTTON_PLACEMENTS as Record<string, string>)],
`as Record<string, string>` is not necessary here

2022-07-13 13:53 UTC, maxinteger commented on src/components/Popover/Popover.style.scss
> +  z-index: 1000;
why it is 1000? Do we have any system to define which z-index can be used in different situation?

2022-07-13 15:31 UTC, torgeadelin commented on src/components/Popover/Popover.stories.args.ts
> +    options: [...Object.values(CLOSE_BUTTON_PLACEMENTS as Record<string, string>)],
removed

2022-07-13 15:31 UTC, torgeadelin commented on src/components/Popover/Popover.constants.ts
> +const CLOSE_BUTTON_PLACEMENTS: Record<string, string> = {
removed

2022-07-15 09:08 UTC, maxinteger approved these changes

2022-07-15 09:10 UTC, merged