feat/add-radio-button
momentum-design/momentum-react-v2 pull request #277
Opened 2022-07-20 10:48 UTC by Jex-y

# Description

Added RadioGroup component

# Links

[figma spec](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=40968%3A67045)

2022-07-25 14:09 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +const Radio: FC<Props> = (props: Props) => {
I would recommend moving this out into a separate file - that makes it more clear and abstracted.

2022-07-25 14:10 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.stories.args.ts
> +  // NOTE: Below is an example. See [Storybook argTypes documentation]{@link https://storybook.js.org/docs/react/api/argtypes}.
remove this line

2022-07-25 14:40 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +          [STYLE.selected]: selected,
replace with data-attribute

2022-07-25 14:40 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +  const icon = <Icon className={STYLE.icon} name="shape-circle" weight="filled" scale={8} />;
since its only used once, i would recommend using inline

2022-07-25 14:40 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +  const radio = (
since its only used once, i would recommend using inline

2022-07-25 14:41 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +          [STYLE.focus]: isFocusVisible,
can u pls check if the FocusRing component also works here instead?

2022-07-25 14:43 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +  const selected = state.selectedValue === props.value;
instead of doing it here i would recommend passing the selected as a prop to the radio component

2022-07-25 14:46 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +          } else if (React.isValidElement(option)) {
i think this is not necessary

2022-07-25 14:46 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +            const value = option.value;
this can be done inline

2022-07-25 15:30 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +  const selected = state.selectedValue === props.value;
If I do this, I would still need to take in the state to pass to `useRadio` so then there could be a case where the isSelected value does not match. Should I try and mock the state for `useRadio`, reimplement the features that it provides or keep the context and this bit the same?

2022-07-26 10:26 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +          [STYLE.focus]: isFocusVisible,
I don't think the `FocusRing` component will work as the element being focused (the hidden input) is different from the one being styled.

2022-07-26 12:42 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.types.ts
> +  options?: Array<Props | string | ReactNode>;
i would recommend adding docs here for all props

2022-07-26 12:44 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.tsx
> +    onChange = props.onChange
that is really weird - i think we shouldn't allow onChange and setValue to be passed in.

2022-07-26 13:19 UTC, cscheffauer commented on src/components/RadioGroup/Radio.tsx
> +      <VisuallyHidden>
i think we don't need visuallyhidden - we can simply use `<input type="radio" />` and style it how we want.
The icon in line 38 is also not necessary, cause the styling could be done through css.

2022-07-26 13:38 UTC, Jex-y commented on src/components/RadioGroup/Radio.tsx
> +      <VisuallyHidden>
It appears to be difficult to style radio buttons and they are generally done by hiding the original component. I misread the react-aria docs and it is done there as well: https://react-spectrum.adobe.com/react-aria/useRadioGroup.html#styling

2022-07-26 14:24 UTC, torgeadelin requested changes
Small changes.
Huge praise for the excellent testing coverage! Probably the most well tested component in the library!! Great job!

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.stories.tsx
> +// NOTE: Primary story. This renders a single component with all external props.
remove all comments

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.style.scss
> +  line-height: 1.2rem;
You should use `<Text/>` component with the corresponding `type` instead and remove the css related to typography.

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +  };
Any reason you had to do this?

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +  }
Nice!

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +  }
But where did you see spec for horizontal layout for radio?

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +      <span {...labelProps}>{label || DEFAULTS.GROUP_LABEL}</span>
Please assign defaults when you deconstruct the props and not in the return.
Applies for all defaults.

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +      {description && <div className={STYLE.description}>{description}</div>}
We don't seem to support description in Figma? Where did you get this from?

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children' | 'onChange'> {
Why omitting `onChange`?

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.unit.test.tsx
> +    // Start
what's the comment for?

2022-07-26 14:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.unit.test.tsx
> +      expect(option2).toHaveAttribute('data-selected', 'false');
We should probably check the functional property, not the `data-selected`.
I think there's ` expect(input).toHaveValue(...etc);` assertion available. You can keep the data-selected too actually, it gives more coverage.

this applies to all tests in the `actions` suite.

2022-07-26 14:34 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +      {description && <div className={STYLE.description}>{description}</div>}
It is not in the figma but the current component is being used in Cantia with a description. I could contact the UX team and see if we could get a spec but for now I have made it similar to the current radioGroups usage: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/30161059/181034470-46b690e0-13d4-4ac0-a29e-836213145c84.png">

2022-07-26 14:37 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +  };
In the case that setValue is not set this would do nothing rather than error and talking to Christoph he said that it would be preferred to something like
```js
if (setValue) {
    setValue(value)
}
```

2022-07-26 14:39 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +  }
Its not in the figma spec but is supported by react-aria radio group and it was a few lines. It can be removed if it would be better to keep the component closer to the spec

2022-07-26 14:41 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children' | 'onChange'> {
Having spoken to @cscheffauer it would be better to only pass a setter for the value to make it more obviously a controlled component.

2022-07-26 14:45 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +      {description && <div className={STYLE.description}>{description}</div>}
Currently reworking that menu with the new components like this: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/30161059/181037027-bbe426c6-7085-42d0-8206-dab1b4c21ada.png">

2022-07-26 15:43 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.unit.test.tsx
> +      expect(option2).toHaveAttribute('data-selected', 'false');
@torgeadelin Would it be ok to just check the data attribute since the styles associated with it are tested in the snapshots? Im having some trouble getting the applied css in the test.

2022-07-27 14:23 UTC, cscheffauer commented on src/components/RadioGroup/RadioGroup.unit.test.tsx
> +      expect(option2).toHaveAttribute('data-selected', 'false');
you could actually do `expect(option1).toBeChecked();`

2022-07-28 16:46 UTC, maxinteger requested changes

2022-07-28 16:46 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.tsx
> +            }
the `children` was excluded from the Radio's Props
This issue is visible in the test snapshots as well, in the second test case the labels are empty

```suggestion
           if (typeof option === 'string') {
              return <Radio key={option} value={option} isDisabled={isDisabled} label={option} />;
            } else {
              return <Radio key={option.value} isDisabled={isDisabled} {...option} />;
            }
```

2022-07-28 16:46 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.tsx
> +
minor: please do not add extra empty line after the doc comment

2022-07-28 16:46 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.stories.docs.mdx
> +| aria-details     | `string`                       | Identifies the element (or elements) that provide a detailed, extended description for the object                      |
this table is unnecessary, sotrybook autogenerate it for you, check the Docs tab and scroll to the bottom

2022-07-28 17:25 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.stories.docs.mdx
> +| aria-details     | `string`                       | Identifies the element (or elements) that provide a detailed, extended description for the object                      |
This table is for the the props that are passed for each option in an array rather than the whole group and I think storybook only does it for the top level component.

2022-07-28 17:26 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.stories.docs.mdx
> +| aria-details     | `string`                       | Identifies the element (or elements) that provide a detailed, extended description for the object                      |
Actually I may be wrong, just found this in the documentation https://storybook.js.org/docs/react/writing-stories/stories-for-multiple-components, will have a deeper look tomorrow.

2022-08-01 10:00 UTC, Jex-y commented on src/components/RadioGroup/Radio.tsx
> +      <VisuallyHidden>
I have now been able to do this by using `appearance: none`

2022-08-01 12:11 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children' | 'onChange'> {
Removed in [#518f267](https://github.com/momentum-design/momentum-react-v2/pull/277/commits/518f26794676d8f20c1eb6d6cf5d3ae7ddd23118)

2022-08-01 12:13 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.tsx
> +  }
Removed in [#518f26](https://github.com/momentum-design/momentum-react-v2/pull/277/commits/518f26794676d8f20c1eb6d6cf5d3ae7ddd23118)

2022-08-01 13:19 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +  };
I mean more about the whole wrapping of the callback. I don't understand why we need `setValue` we should probably be using onChange

2022-08-01 13:20 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.tsx
> +      {description && <div className={STYLE.description}>{description}</div>}
nice!

2022-08-01 13:21 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children' | 'onChange'> {
we shouldn't decide this. this has to act exactly like the native HTML radio button and should also have the same API.
We're just styling it here, nothing more.

2022-08-01 13:24 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.stories.docs.mdx
> +| aria-details     | `string`                       | Identifies the element (or elements) that provide a detailed, extended description for the object                      |
We don't always include all the props that come from react-aria.. I'm not sure how I feel about having the table or not. I guess it helps for now but if they make any changes it will be hell to keep this updated.

We had an attempt to generate the storybook props table based on typescript and doc comments, not sure why we didn't follow with that.

I guess for now I'm not bothered if this stays here.

2022-08-01 13:26 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.stories.tsx
> +  subcomponents: { Radio },
nice!

2022-08-01 13:32 UTC, torgeadelin commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children' | 'onChange'> {
Because the `onChange` from the `useRadioGroup` has this type `(value: T) => void` we can always just pass the setter function of a useState hook directly without having to deal with `e.target.value`.

Also changing this to `setvalue` breaks the pattern of HTMLInputs -- they all have an onChange.

So please use onChange and remove the setValue prop.

2022-08-01 13:43 UTC, torgeadelin approved these changes
Looking great!

2022-08-01 15:42 UTC, maxinteger requested changes
Only minor issues, otherwise looks great

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +    // See https://caniuse.com/css-has
If we want to use `:has` then it should be part of a bigger refactoring
please remove this comment

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +      outline: none !important;
`!important` is not needed here

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +      align-items: center;
the `input` does not have any child component, so the these properties are not needed

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +          border-radius: 50%;
because of the consistency, please use `border-radius: 0.5rem`
BTW it is unnecessary because you already set the `border-radius` in line 21

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +            border-radius: 50%;
remove it please

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +            border-radius: 50%;
remove it please

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.style.scss
> +          border-radius: 50%;
remove it please

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface Props extends Omit<AriaRadioProps, 'children'> {
minor: for better readability please rename this interface to `RadioProps`

2022-08-01 15:42 UTC, maxinteger commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children'> {
I see you removed the orientation prop and the radios rendered horizontally
In forms radios rendered in vertically so you have more space for labels and more readable.
Is UX team happy with this default rendering?

2022-08-01 15:53 UTC, Jex-y commented on src/components/RadioGroup/RadioGroup.types.ts
> +export interface GroupProps extends Omit<AriaRadioGroupProps, 'children'> {
That was a mistake, thanks for spotting.

2022-08-02 08:59 UTC, maxinteger requested changes
Just one more request :)

2022-08-02 08:59 UTC, maxinteger commented on src/components/RadioGroup/index.ts
> +export type RadioGroupProps = GroupProps;
You can simplify the export here:
```suggestion
export * as RADIO_GROUP_CONSTANTS from './RadioGroup.constants';
export * from './RadioGroup.types';
```

2022-08-02 09:13 UTC, maxinteger approved these changes
Nice job

2022-08-02 12:41 UTC, merged