fix(usedividerdot): use dividor-dot for second-line in space-list-item
momentum-design/momentum-react-v2 pull request #295
Opened 2022-09-02 16:51 UTC by jor-row

# Description

Replaced the '-' between words in secondLine in SpaceListitem with a dividerDot

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-299144

Before: 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/86778628/188201542-d8cf40af-87b9-4c5f-bc87-2c2a738fb83c.png">
After: 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/86778628/188201640-9a9f3913-97d1-4f92-b04b-eb27349f19e1.png">

2022-09-05 09:23 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +                <>
the Fragment tag is not needed here because react can handle automatically when when you try tor render a variable which is a list of components.

You need fragment when you have have manually (not by `map` or `reduce` etc.) created component but you do not need a container, like in line 63

2022-09-05 10:07 UTC, jor-row commented on src/components/SpaceListItem/SpaceListItem.tsx
> +                <>
I've removed the unnecessary tag now

2022-09-07 13:23 UTC, torgeadelin requested changes
A few small changes, but great work!
Praise for the extremely well test coverage! 🎉

2022-09-07 13:23 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.constants.ts
> +  DIVIDER_DOT: false,
rename this to SHOW_DIVIDER_DOT (same as the prop, but all caps)

2022-09-07 13:23 UTC, torgeadelin commented on src/components/SpaceListItem/SecondLineElement.tsx
> +import React, { FC } from 'react';
Also this component needs a test.

2022-09-07 13:23 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.unit.test.tsx
> +    // Begins here
remove comment

2022-09-07 17:06 UTC, jor-row commented on src/components/SpaceListItem/SecondLineElement/SecondLineElement.tsx
> +      <span data-test="second-line-element-child">{children}</span>
I added the span here to allow for testing of the children prop for this component. Is there a better way to go about this? This seemed like the simplest way to go about it.

2022-09-08 12:57 UTC, maxinteger requested changes

2022-09-08 12:57 UTC, maxinteger commented on src/components/SpaceListItem/SecondLineElement/SecondLineElement.tsx
> +      <span data-test="second-line-element-child">{children}</span>
You are right, you should not add extra DOM element just for testing.
It is possible to check the text content of the root element with enzyme the which should be sufficient
see my comment in the test

2022-09-08 12:57 UTC, maxinteger commented on src/components/SpaceListItem/SecondLineElement/SecondLineElement.unit.test.tsx
> +      expect(container.textContent).toBe(exampleChildProp);
You can test text children without additional node like this:
```suggestion
      const container = mount(<SecondLineElement>{exampleChildProp}</SecondLineElement>);

      expect(container.text()).toEqual(exampleChildProp);
```

2022-09-08 12:57 UTC, maxinteger commented on src/components/SpaceListItem/SecondLineElement/SecondLineElement.unit.test.tsx
> +      ).toEqual(1);
Same as above
```suggestion
      const container = mount(
        <SecondLineElement showDividerDot={showDividerDot}>{exampleChildProp}</SecondLineElement>
      );
      expect(container.text()).toEqual(exampleChildProp);
```

2022-09-08 12:57 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +          return filteredArray;
this `return` is unnecessary

2022-09-08 13:56 UTC, jor-row commented on src/components/SpaceListItem/SecondLineElement/SecondLineElement.unit.test.tsx
> +      expect(container.textContent).toBe(exampleChildProp);
That's much simpler, thank you! I've changed those unit tests and removed the unnecessary dom element from SecondLineElement.

2022-09-20 10:24 UTC, maxinteger requested changes
I found some mostly cosmetic problems :)

2022-09-20 10:24 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +        const nextElementClean = nextElement.trim();
do we need to trim the value for rendering as well? Is it specified somewhere?
If you need trim just to filter out empty items, then better if to use the `filter` method

2022-09-20 10:24 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +      if (_secondLineArrayClean?.length) {
`_secondLineArrayClean` is always an array so the `?` is unnecessary

2022-09-20 10:24 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +              })}
It is a minor thing but you can simplify this code a bit
```suggestion
              {_secondLineArrayClean.map((secondLineContent, i) => (
                  <SecondLineElement key={`second-line-item-${i}`} showDividerDot={i > 0}>
                    {secondLineContent}
                  </SecondLineElement>
                )
             )}
```

2022-09-20 10:24 UTC, maxinteger commented on src/components/SpaceListItem/SpaceListItem.tsx
> +      const _secondLineArrayClean = _secondLineArray?.reduce((filteredArray, nextElement) => {
minor but please do not start the variable name with `_`
actually you can remove it from `_secondLineArray` as well.

2022-09-20 10:36 UTC, jor-row commented on src/components/SpaceListItem/SpaceListItem.tsx
> +        const nextElementClean = nextElement.trim();
This is to filter out empty items but also to ensure that if a string with leading empty space is passed into the secondLineArray that extra space is not rendered between the dividerDot and the text and to keep those spaces even. See below:
<img width="322" alt="Screenshot 2022-09-20 at 11 34 09" src="https://user-images.githubusercontent.com/86778628/191236115-d227bd88-23b2-4999-8eed-1fc5596d868c.png">
The first example is with trimming the value and the second is without but leading empty space in each string.

2022-09-20 10:42 UTC, jor-row commented on src/components/SpaceListItem/SpaceListItem.tsx
> +      if (_secondLineArrayClean?.length) {
I thought that if secondLine was not provided we would need to check but line 45 handles that. I've removed the ```?```s

2022-09-20 10:45 UTC, jor-row commented on src/components/SpaceListItem/SpaceListItem.tsx
> +      const _secondLineArrayClean = _secondLineArray?.reduce((filteredArray, nextElement) => {
Noted. I've removed the ```_``` from any variables in this component.

2022-09-20 11:47 UTC, jor-row commented on src/components/SpaceListItem/SpaceListItem.tsx
> +      if (_secondLineArrayClean?.length) {
Removing the ```?``` causes all of the unit tests to fail...

2022-09-20 12:49 UTC, maxinteger approved these changes
Great work

2022-09-21 10:06 UTC, torgeadelin commented on src/components/SpaceListItem/SpaceListItem.constants.ts
> +  DIVIDER_DOT: false,
this was not renamed

2022-09-21 10:09 UTC, torgeadelin commented on src/components/SpaceListItem/SecondLineElement.tsx
> +import React, { FC } from 'react';
any reason this was ommited?

2022-09-21 10:11 UTC, torgeadelin approved these changes
Great work!

2022-09-21 10:16 UTC, merged