feat(toggle-circle-button): implement button circle toggle
momentum-design/momentum-react-v2 pull request #302
Opened 2022-09-08 14:39 UTC by nataliadelmar

# Description

PR to implement the buttonCircleToggle component. This is a component that is based on ButtonCircle and adds toggle hooks to it to make it toggable/selectable. 

As for now, only the outline and ghost buttons have a toggable version designed in the component library, which only cover these button colour types in the scope.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/56999622/189151168-4b0d311d-a213-4333-aad0-a48de20bc0e3.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/56999622/189151218-a8599bc1-a052-4b50-908a-bb6b63cb2f06.png">

# Links

[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=4445%3A5884)

2022-09-09 08:56 UTC, maxinteger requested changes
Only few minor thing, otherwise looks great

2022-09-09 08:56 UTC, maxinteger commented on src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
> +  if (ghost === false && outline === false) {
Is this a toggle button specific problem or should we have this warning for the `ButtonCircle` as well?

I think we should not show this error in production build so please add the `process.env.NODE_ENV !== "production"` condition as well
```suggestion
if (process.env.NODE_ENV !== "production")
   if (ghost === false && outline === false) {
```

if the build fails because of this extra condition then you can remove it for now

2022-09-09 08:56 UTC, maxinteger commented on src/components/ButtonCircleToggle/ButtonCircleToggle.stories.tsx
> +// };
please remove the commented code

2022-09-09 08:56 UTC, maxinteger commented on src/components/ButtonCircleToggle/ButtonCircleToggle.stories.tsx
> +import { MultiTemplate, Template } from '../../storybook/helper.stories.templates';
please remove the unnecessary import

2022-09-09 09:53 UTC, nataliadelmar commented on src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
> +  if (ghost === false && outline === false) {
we should not have ths warning for buttonCircle; only for this toggle

2022-09-09 14:11 UTC, maxinteger approved these changes

2022-09-09 15:54 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
> +  if (ghost === false && outline === false) {
I think it's fine to add this warning in production. It's there for a reason to prevent the consumers to use this component in the wrong way.

2022-09-09 16:12 UTC, torgeadelin requested changes
A few comments but looking 🍇

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss
> +    &[data-outline='true'][data-ghost='true'] {
you shouldn't need to select both, one or the other is sufficient.

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
> +  const ref = useRef();
we need to use forward ref to provide more flexibility for this component.
Please look how we do that for ButtonSimple

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.tsx
> +  delete buttonProps.disabled;
please add a comment to explain why this is needed

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.types.ts
> +export interface Props extends ButtonCircleProps, AriaToggleButtonProps {}
We don't want all the props from buttonCircle at this point, please omit `color` for now

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.types.ts
> +export interface Props extends ButtonCircleProps, AriaToggleButtonProps {}
`extends Omit<ButtonCircleProps, 'color'>, ...`

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.stories.args.ts
> +  ...buttonCircleArgTypes,
it would be nice to create another arg type for toggleButton and include those as well.
We should at least have these 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/14194394/189394057-5225bbbf-e181-46e7-ad4a-73bdb307f885.png">

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.stories.args.ts
> +  ...buttonCircleArgTypes,
I'd create a reusable util like `commonStyles`

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx
> +    it('should handle mouse press events', () => {
the name is technically wrong, you're not pressing the button in the component, you're only checking the callback gets used correctly if provided.

I would instead try to click the button and check the onChange gets called instead of calling onChange manually.
Also add a test for the same when it's disabled and check the onChange doesn't get called;

2022-09-09 16:12 UTC, torgeadelin commented on src/components/ButtonCircleToggle/ButtonCircleToggle.unit.test.tsx
> +    it('should handle mouse press events', () => {
Also click twice for the first test to check that it goes from false -> true -> false a.k.a it toggles

2022-09-12 13:23 UTC, torgeadelin reviewed
LGTM!

2022-09-13 14:04 UTC, torgeadelin requested changes
one small change and should be ready

2022-09-13 14:04 UTC, torgeadelin commented on package.json
> +    "@react-stately/toggle": "^3.4.1",
remove

2022-09-13 14:35 UTC, torgeadelin approved these changes
LGTM

2022-09-13 17:16 UTC, merged