fix(search-input): fix styling to align with figma
momentum-design/momentum-react-v2 pull request #310
Opened 2022-09-23 14:33 UTC by jor-row

# Description

This PR fixes some of the styling in the SearchInput component:

- Changes weight of icons to "bold"
- Centres the icons and text within the wrapper div 
- Moves the icons closer to the sides of the wrapper
- Adds the two height variations as seen in the Figma and adds a default width
- Replaces the old 'searching' icon with the LoadingSpinner component

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-356975

https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=25054%3A38561

Before: 
![Screenshot 2022-09-23 at 15 31 49](https://user-images.githubusercontent.com/86778628/191984824-97ffde11-53c6-4f7c-ae80-51e108e9139a.png)

After: 
![Screenshot 2022-09-23 at 15 31 58](https://user-images.githubusercontent.com/86778628/191984855-8e9d6315-474f-4d3e-a4f2-00d4a507f500.png)

2022-09-23 15:37 UTC, maxinteger requested changes

2022-09-23 15:37 UTC, maxinteger commented on src/components/SearchInput/SearchInput.constants.ts
> +};
since the keys and values are the same, better if you are us an array instead 
```suggestion
const HEIGHTS = [28, 32] as const;
```

Note: the `as const` mean TS will infer `[28, 32]` type for the `HEIGHTS` variable instead `number[]`

2022-09-23 15:37 UTC, maxinteger commented on src/components/SearchInput/SearchInput.constants.ts
> +};
Here just use the number as the default height
Also I recommend to add the `as const`, see the reason above

```suggestion
const DEFAULTS = {
  HEIGHT: 32,
} as const;
```

2022-09-23 15:37 UTC, maxinteger commented on src/components/SearchInput/SearchInput.stories.args.ts
> +    options: [...Object.values(HEIGHTS)],
If `HEIGHT` is an array you can do this:
```suggestion
    options: HEIGHTS,
```

2022-09-23 15:37 UTC, maxinteger commented on src/components/SearchInput/SearchInput.stories.tsx
> +    <>
fragment tag is redundant, since the `<div>` is the only root component

2022-09-23 15:37 UTC, maxinteger commented on src/components/SearchInput/SearchInput.types.ts
> +export type SearchFieldHeight = 28 | 32;
The problem is, you defined the height 2 places, here and in the `SearchInput.constants.ts`. You should have a single source of truth. You can reuse the `HEIGHT` constant here:

```suggestion
export type SearchFieldHeight = typeof HEIGHT[number];
```

This is not a perfect solution because we are importing a value into a type definition files, but from the TS point of view both just .ts files so ¯\_(ツ)_/¯

Another solution would be to convert union type to array type (`1 | 2 | 3` => `[1, 2, 3]`) but it involves some type magic... maybe next time

2022-09-23 15:46 UTC, jor-row commented on src/components/SearchInput/SearchInput.stories.tsx
> +    <>
I think that was left over from when I was testing and had added in another div there. I'll take a not to have one last look over anything like that I've left from messing around with things.

2022-09-24 17:44 UTC, jor-row commented on src/components/SearchInput/SearchInput.stories.tsx
> +      <SearchInput height={32} {...props} />
Todo: remove height prop as 32 is the default value

2022-09-24 17:47 UTC, jor-row commented on src/components/SearchInput/SearchInput.style.scss
> +  align-items: center;
Todo: are lines 12-14 all needed?

2022-09-24 17:49 UTC, jor-row commented on src/components/SearchInput/SearchInput.constants.ts
> +const SEARCH_ICON_HEIGHT_MAPPING: Record<SearchFieldHeight, IconScale> = {
Todo: change naming to ICON_HEIGHT_MAPPING as used for searching and cancel icon too

2022-09-28 14:55 UTC, maxinteger approved these changes
Nice one

2022-09-28 15:04 UTC, merged