fix: update list accessibility
momentum-design/momentum-react-v2 pull request #319
Opened 2022-10-14 10:45 UTC by maxinteger

- fix shift+tab to the first list item
- can open menu inside list item
- add unit tests
- update list story

2022-10-14 10:58 UTC, torgeadelin requested changes

2022-10-14 10:58 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.tsx
> +    if (listContext?.currentFocus === undefined) {
nice catch! I saw this the other day, and the reason we couldn't focus on the first item was due to 0 = false

2022-10-14 10:58 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.tsx
> -        {...pressProps}
Why was this removed?

2022-10-14 10:58 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.utils.test.tsx
> +import { getKeyboardFocusableElements } from './ListItemBase.utils';
Praise for moving out of the component and adding tests!

2022-10-14 10:58 UTC, torgeadelin commented on src/components/List/List.unit.test.tsx
> +  describe('list focus', () => {
Praise for adding these tests.

2022-10-14 10:58 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.tsx
> -        {...pressProps}
This breaks the ability for users to have onPress on the list item which is not wha we want

2022-10-14 11:50 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> -        {...pressProps}
You are right I removed for testing, but I forgot to add it back

2022-10-17 16:20 UTC, cscheffauer requested changes
Have u tested these changes with Cantina?
like linking locally and check that all e2e tests in Cantina pass etc.?
would be good, since fundamental changes have been made

2022-10-17 16:20 UTC, cscheffauer commented on src/components/List/List.unit.test.tsx
> +              <input data-testid="input" />
instead of using data-testid, i would recommend to use getByRole('textbox') and getByRole('button') for quering. using data-testid should be avoided if possible. if u want to narrow it to the specific input/button, u can use the "name" option, see here:
https://testing-library.com/docs/queries/byrole#api

2022-10-17 16:20 UTC, cscheffauer commented on src/components/List/List.unit.test.tsx
> +    it('should handle manu in the list item', async () => {
typo `manu`

2022-10-18 08:25 UTC, maxinteger commented on src/components/List/List.unit.test.tsx
> +              <input data-testid="input" />
I agree, `data-testid` should be avoided, but in this case the input is created only for the unit test and it is not part of the production code

2022-10-18 13:56 UTC, torgeadelin approved these changes
Looking great!

2022-10-19 09:14 UTC, merged