feat(popover): add backdrop
momentum-design/momentum-react-v2 pull request #331
Opened 2022-11-24 11:50 UTC by torgeadelin

# Description
- added backdrop
- fixed useNativeKeydown bug
- added tests

# Links
[SPARK-320405](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-320405)

2022-11-25 13:00 UTC, maxinteger commented on src/components/Popover/plugins.ts
> +  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
I removed this line locally and I did not get any error
If you want to be sure you can define the type of the `addBackdrop` variable

```
import type { Plugin } from 'tippy.js';
// ...
export const addBackdrop: Plugin = {
```

2022-11-28 14:01 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +          <Popover triggerComponent={<ButtonSimple>Popover 1</ButtonSimple>} strategy="fixed">
added one test for the other strategy as well

2022-11-28 17:08 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +            <p>Content</p>
fixed

2022-11-29 13:44 UTC, maxinteger requested changes

2022-11-29 13:44 UTC, maxinteger commented on src/components/Popover/Popover.unit.test.tsx
> +      expect(contentAfterClickingBoth).not.toBeInTheDocument();
you are right, but what about the check after the click in line 271

2022-11-29 13:44 UTC, maxinteger commented on src/components/Popover/tippyPlugins.ts
> +export const addBackdrop: Plugin = {
could you please add unit test(s)?

2022-11-29 13:44 UTC, maxinteger commented on src/components/Popover/tippyPlugins.ts
> +  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
I think you do not need this comment anymore

2022-11-29 14:23 UTC, torgeadelin commented on src/components/Popover/plugins.ts
> +  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
removed

2022-11-29 14:26 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +      expect(contentAfterClickingBoth).not.toBeInTheDocument();
the click on 271 is just a button which does nothing.
I've added a check to make sure the first popover is not visible either (altho i've checked that before clicking)

2022-11-29 14:28 UTC, torgeadelin commented on src/components/Popover/tippyPlugins.ts
> +export const addBackdrop: Plugin = {
there is a small unit test already, not sure how much more I can test this, it's technically just an object.

2022-11-29 14:29 UTC, torgeadelin commented on src/components/Popover/tippyPlugins.ts
> +export const addBackdrop: Plugin = {
im open to suggestions tho

2022-11-29 17:00 UTC, maxinteger commented on src/components/Popover/tippyPlugins.ts
> +export const addBackdrop: Plugin = {
the `onMount` and the `onHide` methods are contains some logic and you can test that

For example `onMount` does nothing when the trigger is `mouseenter` or the `onHide` remove only one layer of backdrop

```ts
document.body.innerHTML = '<div [data-tippy-root]' />'
const tippyInstance = { props: { trigger: 'click'}}
const pluginInstance = addBackdro.fn(tippyInstance)
pluginInstance.onMount()
expect(/**backdrop exists*/)
pluginInstance.onHide()
expect(/**backdrop does not exists*/)
```

2022-11-30 09:05 UTC, maxinteger approved these changes

2022-11-30 12:18 UTC, merged