Feat/list/fix list focus on change
momentum-design/momentum-react-v2 pull request #332
Opened 2022-11-28 13:48 UTC by torgeadelin

# Description
Fixed list focus auto-focus on every update.

# Links

2022-11-28 22:07 UTC, maxinteger requested changes
Added few observation

2022-11-28 22:07 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> +      setShouldIgnoreFocusUpdate(true);
this is incorrect, in the search use case the list can shrink when user add more chars to the search term but it can grow as well when suer remove chars from the term

Here you try to exclude cases where focus should not happen, maybe you can try the opposite and the find the cases when focus must be called

If I understand correctly focus should be called only when 
- the user select a row by keyboard or mouse or
- you reset the selected index And the last focused item was inside the list
Probably you can add an extra `isNeedFocus` parameter to the `setContext`

2022-11-28 22:07 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.utils.tsx
> +export const useDidUpdateEffect = (fn: EffectCallback, inputs: DependencyList): void => {
missing unite test

2022-11-29 11:56 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +    it.only('should show/hide Popover on tab + enter', async () => {
hehe, removed

2022-11-29 11:57 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.tsx
> +    if (listContext?.currentFocus >= listContext?.listSize) {
yeah, seems kinda cryptic.
added as separate check

2022-11-29 12:07 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.tsx
> +      setShouldIgnoreFocusUpdate(true);
Focus happens at the item level, not in the context. the context only stores the current focused item and the list item base will automatically focus depending on that current focus variable form the context. in short, the state is lifted but the focusing mechanism is still in the list item.

It does feel correct to me because:
- when the list grows, that means that the focus must have been within the range of the previous list size, and the new items added (even though they can appear at the beginning, or end of list) can't really be refocused based on what was focused previously because I'm not storing the mapping of `itemIndex` -> `itemFocused`.
- when the list shrinks, this is where resetting to 0 when the focus overflows always makes sense, and also, if it doesn't it will focus back on the same item (in terms of which one was focused before based on position, not the actual item). Again, I don't think I can focus back exactly to the one that was focused before because I'm not storing the mapping of `itemIndex` -> `itemFocused`.

With the current solution, did you find any bugs?
If not, I might suggest to leave it as is due to time constraints.

2022-11-29 12:26 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.utils.tsx
> +export const useDidUpdateEffect = (fn: EffectCallback, inputs: DependencyList): void => {
added

2022-11-29 13:17 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> +      setShouldIgnoreFocusUpdate(true);
t looks good in storybook, so you can leave it as it is. Probably we can revisit this problem later and fix with ordering.

2022-11-29 13:18 UTC, maxinteger approved these changes

2022-11-29 14:21 UTC, merged