feat(add-offset-popover): Add offset prop to Popover
momentum-design/momentum-react-v2 pull request #345
Opened 2022-12-16 17:57 UTC by nataliadelmar

# Description

Add offset to the Popover component to allow the consumer to manipulate the position in which the Popover appears regarding its trigger.

Tippy includes this property (See https://atomiks.github.io/tippyjs/v6/all-props/#offset), which is why we needed to add it to our implementation and pass it through.

This work is done on behalf of [SPARK-382377](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-382377), in order to be able to trigger a Popover from the scheduled meeting bricklet that appears in the center of the bricklet rather than outside of it, as the spec states. 

<img width="920" alt="image" src="https://user-images.githubusercontent.com/56999622/208159633-49007741-b3e8-4d49-95bc-3fdb72f39543.png">

# Links

[SPARK-382377](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-382377)

2023-01-06 10:53 UTC, torgeadelin requested changes
looking good, small adjustments

2023-01-06 10:53 UTC, torgeadelin commented on src/components/Popover/Popover.tsx
> +  }
can you add this to the utils file or create one if doesn't exist?
Easier to test.

2023-01-06 10:53 UTC, torgeadelin commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
> +              0,
why has this order changed?

2023-01-06 11:16 UTC, maxinteger requested changes

2023-01-06 11:16 UTC, maxinteger commented on src/components/Popover/Popover.tsx
> +      offset={[distance, skidding]}
this should be 
```suggestion
      offset={[skidding, distance]}
```
see in the docs: https://atomiks.github.io/tippyjs/v6/all-props/#offset

2023-01-06 11:16 UTC, maxinteger commented on src/components/Popover/Popover.types.ts
> +  offset?: Array<number | undefined>;
I think the tippy API is not very nice here and we should not copy it.

Instead create 2 optional props like `offsetDistance?: number` and `offsetSkid?: number` or with similar name.

2023-01-09 11:06 UTC, nataliadelmar commented on src/components/Popover/Popover.tsx
> +  }
Leaving this logic in the LazyTippy's offset prop as it got reduced by separating distance from skidding
Is that oki? :)

2023-01-09 12:23 UTC, cscheffauer requested changes

2023-01-09 12:23 UTC, cscheffauer commented on src/components/Popover/Popover.constants.ts
> +  OFFEST_DISTANCE: 5,
typo (and line below)

2023-01-09 12:23 UTC, cscheffauer commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
> +              0,
it appears that there is a change on the offset prop DEFAULTS, probably because of that.
@nataliadelmar can u pls check this again? like there is something different now in terms of order, pls check if we don't break anything existing.

2023-01-20 17:53 UTC, torgeadelin approved these changes
lgtm

2023-01-23 12:09 UTC, nataliadelmar commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
> +              0,
oh yeah; it was due to the incorrect swapping of properties in offest; it is now back to normal :)

2023-01-30 13:19 UTC, maxinteger approved these changes
Nice one

2023-01-31 10:40 UTC, cscheffauer approved these changes

2023-01-31 10:41 UTC, merged