SPARK-399325: add separator line in button group
momentum-design/momentum-react-v2 pull request #356
Opened 2023-01-27 14:11 UTC by nataliadelmar

# Description

For in-meeting reactions, we need a button group that has a small separator in the middle. I added a separator property to our Button Group to enable/disable this ui element in the component. 
<img width="154" alt="image" src="https://user-images.githubusercontent.com/56999622/215106758-03717fed-5552-4098-88d4-bdd2aba53059.png">

# Links
[SPARK-399325](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-399325)

2023-01-30 14:08 UTC, torgeadelin requested changes
Just the one issue and some suggestion, otherwise looking good.

2023-01-30 14:08 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +  <ButtonCircle ghost key="2">
you shouldn't change the commonChildren, it will change the other stories that use them.

2023-01-30 14:08 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +  variants: [{}, { separator: true }],
At the moment I can't see the round border around the group.
<img width="218" alt="image" src="https://user-images.githubusercontent.com/14194394/215498910-4fcc89b7-a277-4b42-b140-6729bce46cb4.png">

2023-01-30 14:08 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +Separator.parameters = {
Also, please add a variant as part of this group to showcase the actual raise hand and reactions picker split. (including a popover for reaction picker)

Something like this.
```js
{
      style: {marginTop: '1rem'},
      separator: true,
      children: [
        <ButtonCircle ghost key="0" size={40}>
          <Icon
            key="0"
            name="raise-hand"
            autoScale={125}
          />
        </ButtonCircle>,
        <MenuTrigger
          key="2"
          placement="top-end"
          triggerComponent={
            <ButtonCircle ghost key="1" size={40}>
              <Icon name="reactions" autoScale={125} />
            </ButtonCircle>
          }
          children={[
            <Menu key="0" selectionMode="single">
              <Item>Item 1</Item>
              <Item>Item 2</Item>
            </Menu>,
          ]}
        />,
      ],
    },
```

2023-01-30 14:08 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.style.scss
> +
why is it necessary do define the style in 2 places?

2023-01-30 14:08 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.unit.test.tsx
> +describe('<ButtonGroup />', () => {
nice catch!

2023-01-30 16:32 UTC, nataliadelmar commented on src/components/ButtonGroup/ButtonGroup.style.scss
> +
wanted to leverage on the existing tree but yeah Ive added it in one single place with the conditions it needs

2023-01-31 10:45 UTC, torgeadelin commented on src/components/ButtonGroup/ButtonGroup.stories.tsx
> +  variants: [{}, { separator: true }],
nvm we discussed 1:1 that i need to set rounded to true.

2023-01-31 10:54 UTC, torgeadelin approved these changes
LGTM

2023-01-31 11:05 UTC, merged