feat(reaction): add onComplete
momentum-design/momentum-react-v2 pull request #357
Opened 2023-01-30 11:23 UTC by torgeadelin

# Description

Add onComplete event handler for Reaction component.

# Links

2023-01-30 13:43 UTC, maxinteger requested changes
Could you please add a unit test

2023-01-30 13:50 UTC, torgeadelin commented
Added, sorry forgot to push last commit @maxinteger

2023-01-30 19:25 UTC, nataliadelmar commented on src/components/Reaction/Reaction.unit.test.tsx
> +      console.warn = jest.fn();
none of this should give you an error; Do we still need this console.warn?

2023-01-30 19:25 UTC, nataliadelmar commented on src/components/Reaction/Reaction.unit.test.tsx
> +      jest.spyOn(jsonImport, 'useDynamicJSONImport').mockReturnValue({ animationData: 'data' });
why don't you pass this mock to the first test only as you overwrite it in the next 2 tests

2023-01-30 19:25 UTC, nataliadelmar commented on src/components/Reaction/Reaction.unit.test.tsx
> +        .mockReturnValue({ addEventListener, removeEventListener, destroy } as never);
why not using the AnimationItem type from lottie for this?

2023-01-31 11:19 UTC, torgeadelin commented on src/components/Reaction/Reaction.tsx
> +      animation.addEventListener('complete', onComplete);
yes, addressed

2023-01-31 11:19 UTC, torgeadelin commented on src/components/Reaction/Reaction.unit.test.tsx
> +      expect(container.find(`.${STYLE.notFound}`).text()).toEqual(GLYPH_NOT_FOUND);
we have both snapshots and manually checking the DOM

2023-01-31 11:20 UTC, torgeadelin commented on src/components/Reaction/Reaction.unit.test.tsx
> +      console.warn = jest.fn();
it does, in the case where I force it to go in error state, it will console.warn `Reaction load failed`

2023-01-31 11:28 UTC, torgeadelin commented on src/components/Reaction/Reaction.unit.test.tsx
> +      jest.spyOn(jsonImport, 'useDynamicJSONImport').mockReturnValue({ animationData: 'data' });
it was already mocked, i didn't realise it. removed

2023-01-31 11:29 UTC, torgeadelin commented on src/components/Reaction/Reaction.unit.test.tsx
> +        .mockReturnValue({ addEventListener, removeEventListener, destroy } as never);
it's not really and AnimationItem because it's missing a lot of other properties.

2023-01-31 11:54 UTC, maxinteger requested changes

2023-01-31 11:54 UTC, maxinteger commented on src/components/Reaction/Reaction.tsx
> +    console.warn('Reaction load failed:', error);
MR2 is a library which is consumed by Apps. Tis means the lib should not do unchangeable thing for example pollute the console with warning. Logging should be happening in the App.

Either remove this warning or add an `onLoadFailed` prop, so the app react on the error.

Also much easier to test

2023-01-31 12:06 UTC, maxinteger approved these changes

2023-01-31 12:14 UTC, merged