Feat/reactions/add new reactions
momentum-design/momentum-react-v2 pull request #359
Opened 2023-02-01 17:06 UTC by torgeadelin

# Description
- update to consume latest animations
- add types and constants with all available animations for reactions
- - original (messaging)
- - on video

**I have renamed some constants which might be breaking consumers that are importing them.**

# Links
https://jira-eng-gpk2.cisco.com/jira/secure/RapidBoard.jspa?rapidView=4992&view=detail&selectedIssue=SPARK-400192&sprint=27627&quickFilter=44812

2023-02-01 17:42 UTC, torgeadelin commented on src/components/Reaction/Reaction.style.scss
> -    width: 0.75rem;
Forgot to revert this.

2023-02-01 17:42 UTC, torgeadelin commented on src/components/Reaction/Reaction.style.scss
> -    width: 1rem;
And this.

2023-02-02 10:20 UTC, cscheffauer requested changes

2023-02-02 10:20 UTC, cscheffauer commented on src/components/Reaction/Reaction.util.test.ts
> +  it('returns the correct value when second param is empty', () => {
i would also consider testing if the first param is empty and both params are empty

2023-02-02 10:20 UTC, cscheffauer commented on src/components/Reaction/Reaction.tsx
> +      <div data-name={name} className={STYLE.notFound}>
depending on whats the intention of data-name: if data-name should be a helper prop to identify reactions easily in unit tests, this data-name here could actually cause false positives, since it will still say the real data-name of the reaction, even though it wasn't found. 
I think there are probably 2 solutions for here:
1. Change `data-name={name}` to `data-name={"not-found"}` or similar
2. Add a `data-error` attribute with `not-found` or similar to explicitly indicate that this reaction isn't found

2023-02-02 12:15 UTC, torgeadelin commented on src/components/Reaction/Reaction.tsx
> +      <div data-name={name} className={STYLE.notFound}>
Oh, that's a very good point!
I've added it because if you load a bunch of icons and some fail, it's difficult to know which ones failed from looking at the DOM. I will replace it with `data-error`.

2023-02-02 14:12 UTC, cscheffauer approved these changes
small comment - rest looks really good! 💯

2023-02-02 14:12 UTC, cscheffauer commented on src/components/Reaction/Reaction.constants.ts
> +const ORIGINAL_REACTIONS = {
can u pls add a TSDoc to this and the on video reactions with an example of how this constant will look like then?
OR a snapshot test of these constants might be valuable as well (making sure the constants stay as they are intended to be)

thanks!

2023-02-02 17:35 UTC, merged