fix(toast-notification): accept non string content
momentum-design/momentum-react-v2 pull request #365
Opened 2023-02-09 00:01 UTC by pradeep0601

# Description:
The changes are comprised of update of the below components - 
1. ToastNotification
   - accept both string & non-string content 
   - a callback to handle clicks on the toast message
 
2. AlertBanner
    - remove left & right margin

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2023-02-09 10:33 UTC, torgeadelin commented
Why do you need a callback on click to the text?

2023-02-09 17:11 UTC, pradeep0601 commented
> Why do you need a callback on click to the text?

@torgeadelin - This is required to deal with a scenario where we want to open the chat panel in case of clicking on the in-meeting-chat notification.

![image](https://user-images.githubusercontent.com/8437271/217887276-efb6be2f-506e-4951-bff9-c1020f1fcaa3.png)

2023-02-13 19:36 UTC, chburket approved these changes
LGTM

2023-02-14 18:01 UTC, torgeadelin requested changes

2023-02-14 18:01 UTC, torgeadelin commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +      component.props().onClick({
Why is this needed?

2023-02-14 18:01 UTC, torgeadelin commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +      component.props().onClick({
I'm referring to the big click event object.

2023-02-15 17:14 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.tsx
> +
@torgeadelin - Do you mean instead of wrapping the non-string content, I should convert it to string and wrap it into the `Text` component?

2023-02-16 02:16 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.tsx
> +  };
There are two issues with using of ButtonSimple component - 

1. Button Simple comes with the default CSS of a button (background, active, focus etc.)- which can be fixed by overriding it.
2. As we already have a button (leadingVisula) as a descendant of it, so it throws a console error -  `validateDOMNesting(...): <button> cannot appear as a descendant of <button>
`

2023-02-16 02:16 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.tsx
> +
done

2023-02-16 02:17 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.types.ts
> +  onToastMessageClick?: (event: React.MouseEvent<HTMLElement>) => void;
updated

2023-02-16 02:18 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.types.ts
> +  content: string | ReactElement | ReactElement[];
updated, thanks

2023-02-16 02:23 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +      component.props().onClick({
The big object has been auto-generated, and without that it complains - `Argument of type '{}' is not assignable to parameter of type 'MouseEvent<{}, MouseEvent>'.
  Type '{}' is missing the following properties from type 'MouseEvent<{}, MouseEvent>': altKey, button, buttons, clientX, and 29 more.`

2023-02-16 13:28 UTC, cscheffauer requested changes
lets chat about this

2023-02-16 13:28 UTC, cscheffauer commented on src/components/AlertBanner/AlertBanner.style.scss
> +  margin: 0.5rem 0rem;
why was this changed?

2023-02-16 13:28 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +const content = 'This is a test';
i think its worth having a test where we pass in the content as a 'string' and JSX, to ensure both work

2023-02-16 13:28 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationTemplate.tsx
> +  content: string | ReactElement | ReactElement[];
I think this could also be typed as `React.ReactNode` instead

2023-02-16 13:28 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.stories.tsx
> +        'Very long text that can occupy two, three or even more lines. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e
i don't see an example in storybook where the content is NOT a string - like we should also show this as an option, like how to pass in something like a JSX

2023-02-16 13:28 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.tsx
> +      onToastPress(e as unknown as React.MouseEvent<HTMLElement, MouseEvent>);
whats on toastPress for?

2023-02-16 13:28 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.tsx
> +    ...(onToastPress && {
like what is the intention of this?
if `onToastPress` is pass in, you want the div to be a button which is clickable?

If yes, some notes on this:
- Its discouraged from web standards to put a `role=button` on a div, instead of using a native button element
- If this is a real use case, where u want a interactable toast, we have to talk and find a proper architecture allowing it.

2023-02-16 15:27 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.tsx
> +
@torgeadelin we need to discuss this - i would recommend to use a div instead

2023-02-16 20:38 UTC, pradeep0601 commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +const content = 'This is a test';
added unit tests

2023-02-16 20:39 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.tsx
> +    ...(onToastPress && {
As per our discussion, I removed the click callback.

2023-02-16 20:52 UTC, pradeep0601 commented on src/components/AlertBanner/AlertBanner.style.scss
> +  margin: 0.5rem 0rem;
It was required to remove the extra margin from the persistent chat banner.
Removing it from here and will override it in the cantina.

2023-02-17 09:00 UTC, cscheffauer requested changes

2023-02-17 09:01 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.tsx
> +  };
we discussed this and came to the conclusion to not make the whole toast clickable - instead its recommended to pass in a buttonGroup

2023-02-17 09:03 UTC, cscheffauer commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +      component.props().onClick({
as mentioned in comment above, we will not make the toast clickable - therefore this comment can be resolved, since its not applicable anymore

2023-02-17 21:38 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.stories.tsx
> +        'Very long text that can occupy two, three or even more lines. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e
Added storybook with an option to select string or non-string content in the example section.

2023-02-17 21:38 UTC, pradeep0601 commented on src/components/ToastNotification/ToastNotification.unit.test.tsx
> +      const content = <>{exampleContent}</>;
updated

2023-02-17 21:43 UTC, pradeep0601 commented on src/utils/component-conversions.tsx
> +     React.cloneElement(<div />, { ...addedProps }, children) :
It was needed for the case where PrimitiveConvertor receive a fragment with className (observed in the case of in-meeting chat).
Now, as I'm not using it and handling the case of string and non-string content in the ToastNotification component itself, so reverted the code.

2023-02-21 17:50 UTC, cscheffauer requested changes
just some small things I spotted, which need to be addressed to be merged

2023-02-21 17:50 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +        enterAnimation: 'slideInBottom',
so I have double checked this and this test is not going to work.
The `enterAnimation` prop is passed to `waitForNotificationToAppear`, but in that function its not passed on to the NotificationSystem itself.
That could have been also catched by looking at the snapshots, which we SHOULD do - otherwise they are useless.

2023-02-21 17:50 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +        enterAnimation: 'slideInBottom',
actually there are other props also not being passed through in the `waitForNotificationToAppear` function - please check that and update the snapshots accordingly.

2023-02-21 17:50 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +      const { container } = render(<NotificationSystem />);
why can for this whole block here the `waitForNotificationToAppear` util not be used? I would recommend to reuse it as well (u will have to tweak line 63 - if content is a text, just assert for the text to show up - otherwise wait for the button to show up)

2023-02-21 17:50 UTC, cscheffauer commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +    it('should accept a free string as a notification content', async () => {
if you change the test util `waitForNotificationToAppear` as suggested in my comment above, this test and the test below about (passing in a react element) are both not necessary, since thats what the util already tests implicitly.

2023-02-21 19:43 UTC, pradeep0601 commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +        enterAnimation: 'slideInBottom',
updated

2023-02-21 19:43 UTC, pradeep0601 commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +      const { container } = render(<NotificationSystem />);
done, thanks

2023-02-21 19:43 UTC, pradeep0601 commented on src/components/NotificationSystem/NotificationSystem.unit.test.tsx
> +    it('should accept a free string as a notification content', async () => {
done

2023-02-23 09:00 UTC, cscheffauer approved these changes

2023-02-23 10:36 UTC, torgeadelin approved these changes

2023-02-27 22:44 UTC, merged