feat(slider): added new slider component
momentum-design/momentum-react-v2 pull request #405
Opened 2023-05-31 16:02 UTC by cscheffauer

# Description

- Added new slider component (only for horizontal orientation right now since this is what we need atm)
- Added unit tests
- Accessibility comes from React-aria

2023-06-05 20:26 UTC, jor-row requested changes
A few nitpicks, questions for my benefit and one step of the build seems to be failing

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.hooks.test.ts
> +    {
question: I'm assuming it's not possible to have a value that isn't reachable with the given step? e.g. What happens if ```value: 3, minValue: 0, maxValue: 10, step: 3```?

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.types.ts
> +  isDisabled: boolean;
issue: I notice there is no styling that changes based on whether this component is disabled or not. Am I just missing it or does that need to be added? I can see that there are tokens and such for that state in the Figma

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.unit.test.tsx
> +    it('should be change value as expected if pressing left and down arrow key', async () => {
nitpick: typo 
```suggestion
    it('should change value as expected when left or down arrow key is pressed', async () => {
```

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.unit.test.tsx
> +    it('should be change value as expected if pressing right and up arrow key', async () => {
nitpick: typo
```suggestion
    it('should change value as expected when right or up arrow key is pressed', async () => {
```

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.unit.test.tsx
> +    it('should be stick to minValue even after pressing more often left arrow', async () => {
nitpick: typo
```suggestion
    it('should stick to minValue even after pressing left arrow key more', async () => {
```

2023-06-05 20:26 UTC, jor-row commented on src/components/Slider/Slider.unit.test.tsx
> +    it('should be stick to maxValue even after pressing more often right arrow', async () => {
nitpick:  typo
```suggestion
    it('should stick to maxValue even after pressing right arrow key more', async () => {
```

2023-06-05 20:29 UTC, jor-row commented on src/components/Slider/Slider.stories.args.ts
> +
suggestion: Maybe adding ```isDisabled``` as an arg for the storybook would be nice

2023-06-06 08:44 UTC, cscheffauer commented on src/components/Slider/Slider.hooks.test.ts
> +    {
it is possible at the moment to set any value from the top, there is no clamping / fallback handling in place at the moment. its not necessary to have this right now for the feature we need the slider for, so i'll keep this as a tech debt, if thats fine for u!

2023-06-06 20:21 UTC, jor-row approved these changes

2023-06-07 08:46 UTC, merged