feat(overlay-alert): focus lock
momentum-design/momentum-react-v2 pull request #427
Opened 2023-09-28 13:21 UTC by Coread

# Description

- Added focusLockProps to Overlay. If present, the overlay will render inside a FocusLock
- Used these focusLockProps for OverlayAlert. OverlayAlert can still be configured to use different focusLockProps but the default is to returnFocus

Why didn't I just put the FocusLock in OverlayAlert? Because, like with legacy overlay component, overlays naturally want to restrict the focus to what they show in front of them and not behind them. I left this configurable in case there are exceptions to that.

2023-09-28 13:41 UTC, cscheffauer requested changes
missing interaction tests, otherwise looking good!

2023-09-28 13:41 UTC, cscheffauer commented on src/components/Overlay/Overlay.types.ts
> +  focusLockProps?: Omit<ComponentProps<typeof FocusLock>, 'children'>;
Nice typing! i didn't know about `ComponentProps` :)

2023-09-28 13:41 UTC, cscheffauer commented on src/components/Overlay/Overlay.unit.test.tsx
>    });
This component and also the `OverlayAlert` are both lacking of actionability tests (which could be done with React Testing Library). Would be great to have 2 simple tests - one with focus lock enabled, one disabled.
The enabled case you gonna focus on a element inside of the modal and then press tab to get to a element outside of it (shouldn't be possible). For disabled opposite scenario - you should be able to focus.
Interactions like `Tab` from [user-event](https://testing-library.com/docs/user-event/convenience#tab) could be used.

2023-09-28 14:01 UTC, Coread commented on src/components/Overlay/Overlay.unit.test.tsx
>    });
I trust that FocusLock works as expected. There is little value in testing a component that is not part of this library

2023-09-29 10:53 UTC, cscheffauer approved these changes
looking good 💯

2023-09-29 14:21 UTC, merged