feat(input-select): add inputSelect component
momentum-design/momentum-react-v2 pull request #454
Opened 2024-02-01 05:16 UTC by Tianhui-Han

add a comboBox with input and select, inputValue is used to filter select list item

![image](https://github.com/momentum-design/momentum-react-v2/assets/133636998/653098c7-90ca-4a55-8d74-a6f408d1d261)
![image](https://github.com/momentum-design/momentum-react-v2/assets/133636998/77b75da6-e7bf-4e61-acd1-d08c74442671)

2024-02-07 16:31 UTC, jor-row requested changes
I haven't had a super close look at the implementation/tests. I will have a closer look once these comments for manual testing/accessibility testing are addressed

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +        <Input
issue: Pressing down while focused in the input should open the menu (if not already open) and move focus within the menu

source: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +        <Input
issue: Pressing esc when focused on the input should do the following 

<img width="920" alt="Screenshot 2024-02-07 at 16 05 17" src="https://github.com/momentum-design/momentum-react-v2/assets/86778628/ae966ba9-8748-4f58-8f6b-61193a873318">

source: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +        <Input
Pressing enter while in the input component should also open the menu (if not already open) and move focus within the menu

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +      {description && !isOpen ? (<div className={STYLE.description}>{description}</div>) : null}
question: does the description really have to be removed when the menu is open?

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.stories.tsx
> +export { Example, Sections};
question: This component, when used in Cantina, will be used within a modal, right? Have you tested that the menu can come out of the modal you are using in Cantina and not get cut off?

Example of a story from the SelectNext component:

<img width="507" alt="Screenshot 2024-02-07 at 16 17 22" src="https://github.com/momentum-design/momentum-react-v2/assets/86778628/184dd18b-3924-467b-a3e3-ab142f7dd063">

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.types.ts
> +  [propName: string]: any;
question: is the any type necessary?

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.types.ts
> +}
issue: missing empty line at end of file

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.types.ts
> +  height?: string;
question: why are we supporting any height? The Figma only shows a height of 32px. Besides, the text and arrow size does not scale with it making it larger/smaller does not work great.

2024-02-07 16:31 UTC, jor-row commented on src/components/Combobox/Combobox.types.ts
> +export interface Props {
issue: all of these props should have a jsdoc comment above them describing what they do and what the default is if there is one.

2024-02-08 01:33 UTC, Tianhui-Han commented
> I haven't had a super close look at the implementation/tests. I will have a closer look once these comments for manual testing/accessibility testing are addressed

Understood, once I have fixed the aforementioned issues, I will notify you. Thank you for helping with the review.

2024-02-09 11:07 UTC, Tianhui-Han commented on src/components/Combobox/Combobox.types.ts
> +  height?: string;
> question: why are we supporting any height? The Figma only shows a height of 32px. Besides, the text and arrow size does not scale with it making it larger/smaller does not work great.

Understood, I will remove support for any height.

2024-02-20 02:59 UTC, Tianhui-Han commented on src/components/Combobox/Combobox.tsx
> +    setItems(itemsPayload);
> issue: 问题：
> 
> 1. Enter something to filter by in the input在输入中输入要过滤的内容
> 2. Close the menu and open it again关闭菜单并再次打开
> 
> Current bahviour: 目前的行为： All items are displayed, not filtered by what is currently in the input component显示所有项目，而不是按输入组件中当前的内容进行过滤
> 
> Expected behavioud: 预期行为： Items should still be filtered by what is in the input component项目仍应根据输入组件中的内容进行过滤
> 
>  Screen.Recording.2024-02-07.at.15.54.39.mov

Regarding this point, the effect required in my current task is to display all items (without filtering) after clicking.

Of course, I think it is completely reasonable to only display items after filtering here. 

So, I plan to add a property called shouldFilterOnButtonClick to this component to cover these two situations. I wonder if this is reasonable.

2024-02-20 14:08 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +    setItems(itemsPayload);
Can you link a figma or user flow from UX for your feature that specifically says that if there is text in the input field and the button is pressed to show the items that they shouldn't be filtered? 

From a user's perspective, if I type a word to filter by and open the menu I expect it to be filtered. Note that the examples on https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/ do exactly this.

2024-02-21 01:50 UTC, Tianhui-Han commented on src/components/Combobox/Combobox.tsx
> +    setItems(itemsPayload);
> Can you link a figma or user flow from UX for your feature that specifically says that if there is text in the input field and the button is pressed to show the items that they shouldn't be filtered?
> 
> From a user's perspective, if I type a word to filter by and open the menu I expect it to be filtered. Note that the examples on https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/ do exactly this.

It seems that this detail is not mentioned in Figma. The function I have implemented already exists in the desktop app, so I referred to the interaction performance in the desktop app. Here is the link to the interaction video: https://app.vidcast.io/share/308ad8ba-aa36-4a3a-8e59-3d27fb7852d3

Of course, if you think this is unnecessary, I think it is completely reasonable.

2024-02-21 06:03 UTC, Tianhui-Han commented
> I haven't had a super close look at the implementation/tests. I will have a closer look once these comments for manual testing/accessibility testing are addressed

I have made modifications according to your suggestions. The unit test part is not yet complete and is still in progress. 

Could you please check if the current changes meet the expectations? Thank you!

2024-02-21 15:48 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +import { Input } from '@momentum-ui/react-collaboration';
issue: I think this is the legacy input component which shouldn't be used. We have the new TextInput component, and we should import the TextInput component the same way that we do Menu, Icon and ButtonPill (i.e. ```import TextInput from '../TextInput')

2024-02-21 15:48 UTC, jor-row commented on src/components/Combobox/Combobox.style.scss
> +    .md-combobox-description {
Why was the error state removed? It is part of the Figma so should be implemented

2024-02-21 15:50 UTC, jor-row commented on src/components/Combobox/Combobox.tsx
> +    setItems(itemsPayload);
Ok, if that is how desktop has implemented it then we should follow that for consistency between clients

2024-02-21 23:00 UTC, jor-row requested changes

2024-02-21 23:02 UTC, jor-row commented
> > I haven't had a super close look at the implementation/tests. I will have a closer look once these comments for manual testing/accessibility testing are addressed
> 
> I have made modifications according to your suggestions. The unit test part is not yet complete and is still in progress.
> 
> Could you please check if the current changes meet the expectations? Thank you!

Accessibility issues that I raised look good. I've left some comments about parts of the implementation. Let me know when the unit tests are done and I'll have another look

2024-02-21 23:02 UTC, jor-row commented on src/components/Combobox/Combobox.types.ts
> +  items: IComboboxGroup[];
Changing the prop name to be more descriptive should be enough

2024-02-22 07:22 UTC, Tianhui-Han commented on src/components/Combobox/Combobox.types.ts
> +  onAction?: (item: IComboboxItem) => void;
Indeed, here we should only need to keep onSelectionChange to ensure our functionality is complete. I will remove onAction.

2024-02-26 08:18 UTC, Tianhui-Han commented
> > > I haven't had a super close look at the implementation/tests. I will have a closer look once these comments for manual testing/accessibility testing are addressed
> > 
> > 
> > I have made modifications according to your suggestions. The unit test part is not yet complete and is still in progress.
> > Could you please check if the current changes meet the expectations? Thank you!
> 
> Accessibility issues that I raised look good. I've left some comments about parts of the implementation. Let me know when the unit tests are done and I'll have another look

Hey Jordan, I’ve completed these modifications and filled out the unit tests. 
Could you please review it for me? Thank you very much!

2024-02-27 00:11 UTC, jor-row requested changes
Tests looking good, just a few small comments and tests to add before I can approve

2024-02-27 00:11 UTC, jor-row commented on src/utils/combobox.unit.test.ts
> +  it('test case withSection', () => {
can you add a test case where the input value does not match any of the item labels

2024-02-27 02:01 UTC, Tianhui-Han commented on src/components/Combobox/Combobox.types.ts
> +  onSelectionChange?: (item: IComboboxItem) => void;
> onSelectionChange

Actually, I also think that onSelectionChange can cover almost all cases, so it would be more reasonable to remove onAction first.

2024-02-27 02:21 UTC, Tianhui-Han commented
> Tests looking good, just a few small comments and tests to add before I can approve

Hey Jordan, I have made these changes, could you please review them again? Thank you for your continuous support, you are very patient!👍

2024-02-27 22:57 UTC, jor-row approved these changes
Looks good, thanks for making all those changes! I'm approving so I'm not blocking this feature work any longer, but please make sure you export the component in src/index before merging

2024-02-27 22:57 UTC, jor-row commented on src/components/Combobox/Combobox.utils.ts
> +import {IComboboxGroup, IComboboxItem} from './Combobox.types'
small: missing semi colon at end of line

2024-02-27 22:57 UTC, jor-row commented on src/components/Combobox/index.ts
Important: you need to add ```Combobox``` as one of the exports from ```./components``` in the file in ```src/index.js``` otherwise you won't be able to use it in Cantina properly

2024-02-28 09:05 UTC, Tianhui-Han commented
> Looks good, thanks for making all those changes! I'm approving so I'm not blocking this feature work any longer, but please make sure you export the component in src/index before merging



> Looks good, thanks for making all those changes! I'm approving so I'm not blocking this feature work any longer, but please make sure you export the component in src/index before merging

I’ve made a small adjustment to the logic, making the interaction between selectionChange and inputValue more reasonable, and also improved the overall naming conventions. 

However, it seems that I don’t have the permission to merge. Could you please help me merge it? Thank you very much!👍

2024-02-29 01:12 UTC, merged