fix(comboBox): fix lost styles
momentum-design/momentum-react-v2 pull request #455
Opened 2024-02-29 05:47 UTC by Tianhui-Han

# IMPORTANT
**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

fixed the issue of missing styles in the component

# Links

*Links to relevent resources.*

2024-03-13 17:30 UTC, jor-row requested changes

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.stories.tsx
![Screenshot 2024-03-13 at 17 08 37](https://github.com/momentum-design/momentum-react-v2/assets/86778628/71e9e39c-d4a5-45ec-92b9-3ea399353299)

In List item story styling is broken

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.style.scss
> +  .md-combo-box-input-section:hover .md-combo-box-divider {
![Screenshot 2024-03-13 at 17 11 51](https://github.com/momentum-design/momentum-react-v2/assets/86778628/8af95d31-ac93-476f-8047-354521c91835)

hover now goes past the divider, can we not get it to line up?

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.unit.test.tsx
> +      it('reset inputValue, when focus shifts from inside the component to outside', async () => {
does this actually work?


https://github.com/momentum-design/momentum-react-v2/assets/86778628/aa0fa9f4-eb4e-400a-a226-f2dd90d22ed3

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.utils.ts
> +            const scrollTop = Number.isNaN(element.scrollTop)?0:element.scrollTop;
please add some spaces to make this more readable 

```
const scrollTop = Number.isNaN(element.scrollTop) ? 0 : element.scrollTop;
```

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.utils.ts
> +            const scrollTop = Number.isNaN(element.scrollTop)?0:element.scrollTop;
What if scrollTop is ```undefined``` or ```null``` or a string or anything other than a number and NaN? Is there a type for this value?

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.utils.test.ts
> +        it('test case', () => {
please write a more descriptive test case description

ideally this should be a ```it.each```

something like 

```
it.each`
element | expectedSum
${sampleElement1 as Element) | ${0}
${sampleElement2 as Element) | ${0}
${sampleElement3 as Element) | ${0}
${sampleElement4 as Element) | ${18.5}
`('correctly returns $expectedSum for $element, (element, expectedSum) => {
     expect(getSumScrollTop(element).toEqual(expectedSum);
}
````
so in the tests we will see exactly what the test is doing instead of just "test case"

2024-03-13 17:30 UTC, jor-row commented on src/components/ComboBox/ComboBox.tsx
There are a *lot* of changes to this file but this PR doesn't actually explain what problems you are fixing so it's hard to review as I can't confirm what wasn't working now works as you expect

Can you add some details/examples of what was wrong and what has been fixed?

2024-03-14 00:56 UTC, Tianhui-Han commented on src/components/ComboBox/ComboBox.tsx
Of course, I will execute it immediately

2024-03-14 01:05 UTC, Tianhui-Han commented on src/components/ComboBox/ComboBox.unit.test.tsx
> +      it('reset inputValue, when focus shifts from inside the component to outside', async () => {
Perhaps I didn’t describe it clearly enough, because if you just click outside, it doesn’t re-trigger the focus event of other elements, so it doesn’t trigger. If you want to test this, you can see the effect in MultipleComboBox. Of course, if you think it is necessary to cover the case you are currently demonstrating, I think it’s reasonable. If you suggest, I will do it.

2024-03-14 01:07 UTC, Tianhui-Han commented on src/components/ComboBox/ComboBox.stories.tsx
This should be caused by the offset I set in the test template, I will correct it.

2024-03-20 22:36 UTC, jor-row requested changes
Changes look OK, just that weird behaviour I've commented on above

2024-03-20 22:36 UTC, jor-row commented on src/components/ComboBox/ComboBox.stories.tsx
This one still looks a little strange. 
![Screenshot 2024-03-20 at 22 06 31](https://github.com/momentum-design/momentum-react-v2/assets/86778628/f1389ff8-c7c5-42a6-9403-155d935f90de)

Just make the Overlay Alert and surrounding div big enough to display the whole thing.

2024-03-20 22:36 UTC, jor-row commented on src/components/ComboBox/ComboBox.unit.test.tsx
> +      it('reset inputValue, when focus shifts from inside the component to outside', async () => {
I think the issue with clicking outside should be fixed as well. Arguably people will run into this issue more by clicking off the menu than focusing outside it using a keyboard

2024-03-21 14:22 UTC, jor-row approved these changes
Tested and changes look OK, approving but please fix the storybook before merging

2024-03-21 14:22 UTC, jor-row commented on src/components/ComboBox/ComboBox.stories.tsx
>    );
no need for another div, just made the child div of the overlay alert taller and its fine 

<img width="446" alt="Screenshot 2024-03-21 at 14 18 54" src="https://github.com/momentum-design/momentum-react-v2/assets/86778628/e57169e0-c899-42e9-944e-360b0a38cdcd">

2024-03-21 14:22 UTC, jor-row commented on src/components/ComboBox/ComboBox.stories.tsx
This isn't fixed

2024-04-02 17:16 UTC, merged