feat(group): add new component Group
momentum-design/momentum-react-v2 pull request #460
Opened 2024-05-14 23:14 UTC by stanjiawang

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*
Add new component ```Group``` to be the container of a group of ReactNode elements.
Provide accessibility role='group' and <label /> for the Group component.

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2024-05-15 17:39 UTC, nataliadelmar commented on src/components/Group/Group.constants.ts
> +const CLASS_PREFIX = 'md-group';
this component should be called 'InputGroup'

2024-05-15 17:39 UTC, nataliadelmar commented on src/components/Group/Group.constants.ts
> +  GROUP_ARIA_LABEL: 'group',
Do we need a default? is it allowed to have an input group without label?

2024-05-15 18:14 UTC, stanjiawang commented on src/components/Group/Group.constants.ts
> +const CLASS_PREFIX = 'md-group';
Thanks for your comments! Changed ```Group``` to ```InputGroup```. @nataliadelmar

2024-05-15 18:14 UTC, stanjiawang commented on src/components/Group/Group.constants.ts
> +  GROUP_ARIA_LABEL: 'group',
Thanks for your comments! Removed ```GROUP_ARIA_LABEL``` since ```label``` will be required. @nataliadelmar

2024-05-16 11:13 UTC, nataliadelmar requested changes

2024-05-16 11:13 UTC, nataliadelmar commented on src/components/InputGroup/InputGroup.types.ts
> +  orientation?: 'horizontal' | 'vertical';
I agree it applies very nicely to cases like checkboxes or things like this... make sure that none of our current detected bugs for input groups has a grid layout if we want to keep this as it is

2024-05-16 11:13 UTC, nataliadelmar commented on src/components/InputGroup/InputGroup.tsx
> +        </label>
I do not think we should default the styling of the visible label. Given my comment in the label on the types file, I would modify this to:
```
return (
   <div 
       className={classnames(className, STYLE.container)}
        aria-labelledby={ariaLabelledby}
        aria-label={ariaLabel} // in case they pass an aria label
        role="group"
        ...otherProps
    >
         {label} // this label would have the id="same-as-arialabelledby"
         {map....}
     </div>
)
```

2024-05-16 11:13 UTC, nataliadelmar commented on src/components/InputGroup/InputGroup.tsx
> +          ref: (e) => {
This would normally work fine if the children would be single independant controls. I fear it will not behave as expected if we have pairs of label-input boxes inside the group, or pairs of label-checkbox inside the inputs box, etc.

2024-05-16 17:01 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  ariaControls?: string;
Thanks for your comments! Removed ```ariaControls```. @nataliadelmar

2024-05-16 17:09 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.tsx
> +      aria-controls={ariaControls}
Thanks for your comments! Removed ```aria-controls```. Added ```otherProps```.

2024-05-16 17:14 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  onTabPress?: () => void;
Thanks for your comments! Removed ```onTabPress```. @nataliadelmar

2024-05-16 17:28 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.tsx
> +      id={id}
Thanks for your comments! Changed to:

```
    <div
      aria-label={ariaLabel}
      aria-labelledby={ariaLabelledby}
      className={classnames(className, STYLE.container)}
      role='group'
      style={style}
      {...otherProps}
    >
   ```
   @nataliadelmar

2024-05-16 17:36 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  orientation?: 'horizontal' | 'vertical';
Agreed! It should be flexible for this component as user could pass in the style or classname.

Removed ```orientation```. @nataliadelmar

2024-05-16 17:51 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.tsx
> +        </label>
Thanks for your comments! Removed style for ```label``` so user could pass ```label``` as ReactElement.  @nataliadelmar

2024-05-16 17:54 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  label: string;
Thanks for your comments!

Changed to
```
  /**
   * aria-label attribute for the InputGroup
   */
  ariaLabel?: string;

  /**
   * aria-labelledby attribute for the InputGroup
   */
  ariaLabelledby?: string;
  /**
   * The label for the InputGroup.
   */
  label?: ReactElement;
  ```
  @nataliadelmar

2024-05-16 19:36 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  labelStyle?: CSSProperties;
Thanks for your comments! Removed ```labelStyle```. @nataliadelmar

2024-05-17 23:42 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.types.ts
> +  orientation?: 'horizontal' | 'vertical';
Removed ```orientation```. Thanks!

2024-05-17 23:43 UTC, stanjiawang commented on src/components/InputGroup/InputGroup.tsx
> +          ref: (e) => {
Removed ```map``` and use ```children``` directly based on our discussion. 
Thanks for your comments! @nataliadelmar

2024-05-21 16:01 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +const Vertical = () => {
more interesting than showing the different flex directions, it would be great to show these cases:
1 Group of text inputs together with label 'Personal details' on top
2 Group of checkboxes together with label 'Countries you have visited' on top
3 Group of toggles together with a label 'Other options' on top (like the one we have in layout dropdown inside a meeting)

2024-05-21 17:09 UTC, stanjiawang commented on src/components/AriaGroup/AriaGroup.style.scss
> +  flex-direction: column;
Thanks for your comments! Removed default style and related code. @nataliadelmar

2024-05-21 17:10 UTC, stanjiawang commented on src/components/AriaGroup/AriaGroup.types.ts
> +  style?: CSSProperties;
Removed ```style``` since we have ```className```. Thanks for your comments! @nataliadelmar

2024-05-21 17:16 UTC, stanjiawang commented on src/components/AriaGroup/AriaGroup.tsx
> +    label,
Removed ```label```. Thanks for your comments! @nataliadelmar

2024-05-21 17:47 UTC, stanjiawang commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +const Vertical = () => {
Created new storybook, thanks for your comments! @nataliadelmar

2024-05-21 18:27 UTC, nataliadelmar approved these changes
A non-blocking comment on the storybook

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +      children={children}
we should have here ariaLabelledBy = 'text-inputs-label-id'

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +    id: 'text-input-group'
not needed as we want to imitate this structure https://www.w3.org/WAI/tutorials/forms/grouping/#:~:text=Because%20WAI%2DARIA%20not

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +      <label htmlFor='text-input-group' >
insated of htmlFor, we should use id="text-inputs-label-id"

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +      <label htmlFor='checkbox-group' >
same as in the Inputs example: let's use ariaLabelledBy on the group and id on the label

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +      />
to make this example look more real, copy the snippet we have on Toggle stories to make a label appear next to the toggle:
https://github.com/momentum-design/momentum-react-v2/blob/f5018d5a6aa5c38c6283a68b43772288fd91ba08/src/components/Toggle/Toggle.stories.tsx#L23C4-L27C12

2024-05-21 18:27 UTC, nataliadelmar commented on src/components/AriaGroup/AriaGroup.stories.tsx
> +      <label htmlFor='other-options-group' >
same as in the Inputs example: let's use ariaLabelledBy on the group and id on the label

2024-05-21 18:47 UTC, merged