fix(focus-lock): focus lock on popover, modal etc
momentum-design/momentum-react-v2 pull request #478
Opened 2024-05-29 11:44 UTC by cscheffauer

# Description

- Moved Focus Lock into ModalContainer
- Removed logic from MenuTrigger to tab outside of the modal, since this is not applicable anymore according to WCAG
- CSS changes necessary since DOM structure changed due to the focus lock movement
- Adjusted unit tests in all applicable spots

2024-05-29 17:25 UTC, jor-row requested changes

2024-05-29 17:25 UTC, jor-row commented on src/components/Popover/Popover.tsx
I'm seeing an interesting change in behaviour that I'm not sure we want. when linking locally with cantina in the call controls on production I can tab through each button as expected, but on local host when tabbing through call controls I have to press tab to dismiss the tooltips (the ones on start/stop video and mute/unmute in "non expanded (icon only) mode"). Also, some tooltips aren't opening at all with keyboard.

Is this due to these changes?

https://github.com/momentum-design/momentum-react-v2/assets/86778628/8df81f97-c0a4-4588-afd4-53a9badb878a

2024-05-29 17:25 UTC, jor-row commented on src/components/Popover/Popover.tsx
Focus enters popovers as expected

2024-05-29 17:25 UTC, jor-row commented on src/components/Popover/Popover.tsx
I tested with the latest momentum and looks like this behaviour is due to this PR so we should fix that

2024-05-31 08:25 UTC, cscheffauer commented on src/components/Popover/Popover.tsx
> +    ...(interactive && { 'aria-labelledby': triggerComponentId, focusLockProps: { returnFocus: true,  } }),
good catch - we haven't discussed this during tech breakdown, going to set it to the same value as `focusBackOnTrigger`

2024-05-31 08:26 UTC, cscheffauer commented on src/components/MenuTrigger/MenuTrigger.tsx
> -      }
yes, clarified in the space

2024-05-31 08:34 UTC, cscheffauer commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx
> +    describe('keyboard accessibility', () => {
that was ordered that way previously - have cleaned it up now

2024-06-03 08:00 UTC, cscheffauer commented on src/components/Popover/Popover.tsx
fixed

2024-06-03 08:54 UTC, cscheffauer commented on src/components/ModalContainer/ModalContainer.types.ts
> +import FocusLock from 'react-focus-lock';
yes, there have been issues with it (can't recall the exact issues). We could have also used focus scope, but we would have needed a lot more of work arounds than we do need for the react-focus-lock.

2024-06-04 10:59 UTC, jor-row commented on src/components/Popover/Popover.tsx
Linked locally with Cantina and here are some issues I'm seeing:

- OverlayAlert no longer returns focus properly. This works as expected on web-unstable. Examples to test: Profile Popover -> Settings -> Report an issue / Health Checker, Space settings -> View space policy
- In-meeting reaction popover you can no longer press Tab to cycle through all the options, but can cycle through them all with alt-tab
- In-meeting reaction popover, can no longer press esc to close the popover when focused on any of the reaction buttons
- End meeting button, the thing that takes focus when the popover is opened is not the button and cannot be pressed 

Accessibility bug that we thought would be fixed with this but isn't yet
- Video options popover doesn't automatically take focus when opened

2024-06-04 11:00 UTC, jor-row commented on src/components/Popover/Popover.tsx
4. Looks like this can be solved in Cantina - remove FocusTrappableElement and add autoFocus={false} to the PopoverNext props

2024-06-04 14:21 UTC, jor-row approved these changes

2024-06-04 14:24 UTC, merged