feat: add new tooltip component
momentum-design/momentum-react-v2 pull request #479
Opened 2024-05-30 14:30 UTC by maxinteger

# Description

Implement the Tooltip component

2024-05-31 10:02 UTC, nataliadelmar commented on src/components/Popover/Popover.unit.test.tsx
> +    expect(modalContainer).toBeInTheDocument();
we should check this tooltip is not in the screen before openPopoverByClickingOnTriggerAndCheckContent()

2024-05-31 10:27 UTC, nataliadelmar commented on src/components/Tooltip/Tooltip.stories.args.ts
> +  isDescendant: {
descendant or description?

2024-05-31 10:27 UTC, nataliadelmar commented on src/components/Tooltip/Tooltip.tsx
> +            content: isDescription ? 'describedby' : 'labelledby',
aria content?

2024-05-31 10:34 UTC, maxinteger commented on src/components/Tooltip/Tooltip.tsx
> +            content: isDescription ? 'describedby' : 'labelledby',
Yes, see see it in the tippy docs
https://atomiks.github.io/tippyjs/v6/all-props/#aria

2024-05-31 10:37 UTC, cscheffauer requested changes
Can u please wait with this PR, till PR https://github.com/momentum-design/momentum-react-v2/pull/478 is in (multiple changes to the Popover, which could affect this PR)

2024-05-31 10:37 UTC, cscheffauer commented on src/components/Tooltip/Tooltip.tsx
> +        trigger="mouseenter focus"
focus doesn't need to be set here, since its set by default in the Popover component, if the trigger is mouseenter.

2024-05-31 10:53 UTC, maxinteger commented on src/components/Tooltip/Tooltip.tsx
> +        trigger="mouseenter focus"
I will leave it is as it is, this way more explicit

2024-06-04 15:24 UTC, cscheffauer requested changes

2024-06-04 15:24 UTC, cscheffauer commented on src/components/MenuTrigger/MenuTrigger.tsx
> +      role="menu"
this PR is about the Tooltip, not about fixing issues with the menu. we should not pass in the role="menu" here - also i think the role "menu" is set in the menu component itself, so for me this is out of scope of this PR and also might introduce more issues.

2024-06-04 15:24 UTC, cscheffauer commented on src/components/Tooltip/Tooltip.stories.tsx
> +Offset.args = {
I think we would want another story here which is similar to the "Multiple Popovers" story in the Popover component (where 1 Popover and 1 Tooltip is having the same trigger component)

2024-06-04 15:27 UTC, torgeadelin commented on src/components/MenuTrigger/MenuTrigger.tsx
> +  const { menuTriggerProps, menuProps } = useMenuTrigger(
just a formatting change, should be reverted

2024-06-04 15:30 UTC, torgeadelin commented on src/components/Popover/Popover.unit.test.tsx
> +    // assert no popover on screen
comment is wrong.

2024-06-04 15:30 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.stories.args.ts
> +    description: `Whether the tooltips be a description or a label of the trigger component`,
typo

2024-06-04 15:48 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +   * Opens the tooltip by hoer on the trigger component, waits until
hover

2024-06-04 15:48 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +    it('add aria-describedby to trigger component when isDescription is true', async () => {
what about when `isDescription` is false?

2024-06-04 15:48 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +  refCases.forEach(({ description, ref, checkRef, resetRef }) => {
i think these belong more to the Popover component not the tooltip

2024-06-04 15:48 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +        // after another hover, tooltip should be hidden again
not sure comment makes sense

2024-06-04 15:51 UTC, maxinteger commented on src/components/MenuTrigger/MenuTrigger.tsx
> +  const { menuTriggerProps, menuProps } = useMenuTrigger(
Christoph asked me to revers all the menuTrigger changes

2024-06-05 08:39 UTC, maxinteger commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +jest.unmock('@react-aria/utils');
Not needed, it was a left over

2024-06-05 08:43 UTC, maxinteger commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +    it('add aria-describedby to trigger component when isDescription is true', async () => {
it was covered by the `add aria-labelledby to trigger component by default` test, but I added one more where `isDescription` is explicitly `false`

2024-06-05 10:32 UTC, torgeadelin commented on src/components/MenuTrigger/MenuTrigger.tsx
> +  const { menuTriggerProps, menuProps } = useMenuTrigger(
I still see this change

2024-06-05 10:33 UTC, torgeadelin commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx
> -      render(<MenuTrigger
formatting changes here as well

2024-06-05 10:36 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +        // after another hover, tooltip should be hidden again
still doesn't make sense

2024-06-05 10:36 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +  refCases.forEach(({ description, ref, checkRef, resetRef }) => {
I see you reacted with thumbs up, does that mean you agree and you're planning on moving them or?

2024-06-05 10:38 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +   * Opens the tooltip by hoer on the trigger component, waits until
issue is still there

2024-06-05 10:40 UTC, torgeadelin commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +jest.unmock('@react-aria/utils');
what about uuid?

2024-06-05 11:27 UTC, cscheffauer approved these changes
fine from my side, if all other comments get addressed

2024-06-05 11:55 UTC, maxinteger commented on src/components/MenuTrigger/MenuTrigger.tsx
> +  const { menuTriggerProps, menuProps } = useMenuTrigger(
lint-staged reverted my changes, it will be ok in the next commit

2024-06-05 11:56 UTC, maxinteger commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +jest.unmock('@react-aria/utils');
ModalContainer's arrow has an id and it is generated with UUID, I mock it to get the consistent snapshot

2024-06-05 11:57 UTC, maxinteger commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +  refCases.forEach(({ description, ref, checkRef, resetRef }) => {
I agree it is not needed

2024-06-05 11:57 UTC, maxinteger commented on src/components/Tooltip/Tooltip.unit.test.tsx
> +        // after another hover, tooltip should be hidden again
fixed

2024-06-05 12:29 UTC, torgeadelin approved these changes

2024-06-05 12:51 UTC, merged