feat(lightbox): add theme wrapper
momentum-design/momentum-react-v2 pull request #480
Opened 2024-05-31 16:31 UTC by torgeadelin

# Description
- add theme wrapper for lighbox
- required as part of:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503208
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503209
- fixes focus styling for all components inside

2024-06-03 08:02 UTC, cscheffauer requested changes

2024-06-03 08:02 UTC, cscheffauer commented on src/legacy/Lightbox/index.js
> +        <MomentumThemeProvider theme={this.props.theme}>
I think this is not necessary - in the app the MomentumThemeProvider is mounted on the top and this Lightbox is not in a iFrame, so it should pick up the theme correctly. 
If not, can u please explain why its not picking up the theme?

2024-06-03 09:56 UTC, torgeadelin commented on src/legacy/Lightbox/index.js
> +        <MomentumThemeProvider theme={this.props.theme}>
Lighbox uses an external dependency for the Modal, and it build the dom elements outside of the theme provider. I've attached pic.
<img width="416" alt="image" src="https://github.com/momentum-design/momentum-react-v2/assets/14194394/2d7b77f0-9bde-46a9-9698-59bc9050ac6d">


Legacy Modal does the same thing.

2024-06-03 16:02 UTC, maxinteger approved these changes

2024-06-04 18:25 UTC, cscheffauer approved these changes

2024-06-06 13:40 UTC, merged