feat(button): add aria-disabled for shallow disabled
momentum-design/momentum-react-v2 pull request #488
Opened 2024-06-05 11:44 UTC by torgeadelin

# Description
- add aria-disabled for shallow disabled

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-367651

2024-06-05 13:57 UTC, nataliadelmar commented on src/components/ButtonCircle/ButtonCircle.tsx
> +      aria-disabled={shallowDisabled || DEFAULTS.SHALLOW_DISABLED}
what is prop disabled = true ?

2024-06-05 13:59 UTC, maxinteger requested changes

2024-06-05 13:59 UTC, maxinteger commented on src/components/ButtonSimple/ButtonSimple.tsx
> +  if (props['aria-disabled'] === true) {
based on the react-aria code if you set `isDisabled` prop on the button then it will update the `aria-disabled` as well.
https://react-spectrum.adobe.com/react-aria/useButton.html#disabled


Can we use the `isDisabled` prop in cantina instead of fight with react-aria

Probably we can remove the `disabled` prop from the type def to avoid confusion

2024-06-05 14:00 UTC, torgeadelin commented on src/components/ButtonCircle/ButtonCircle.tsx
> +      aria-disabled={shallowDisabled || DEFAULTS.SHALLOW_DISABLED}
What do you mean?

2024-06-05 15:14 UTC, torgeadelin commented on src/components/ButtonSimple/ButtonSimple.tsx
> +  if (props['aria-disabled'] === true) {
No because we don't actually want the button to be disabled, we want it to be shallow disabled (semantically disabled)

2024-06-10 13:11 UTC, nataliadelmar approved these changes

2024-06-10 13:11 UTC, nataliadelmar commented on src/components/ButtonCircle/ButtonCircle.unit.test.tsx
> +    it('should pass shallow disabled prop', () => {
I see a too similar test (the name is prob wrong) that we could reuse called 'should pass sallow disabled prop' a few lines up there (line 220 of this file)

2024-06-10 17:05 UTC, torgeadelin commented on src/components/ButtonCircle/ButtonCircle.tsx
> +      aria-disabled={shallowDisabled || DEFAULTS.SHALLOW_DISABLED}
I don't think so. aria-disabled is just a semantically equivalent of disabled but with the exception that it's still interactive.

If the button is disabled, adding aria-disabled seems paradoxal to me, it's like forcing disabled but then reverting the true disabled to be interactive and just be semantically disabled (for SR).

2024-06-10 17:08 UTC, torgeadelin commented on src/components/ButtonCircle/ButtonCircle.unit.test.tsx
> +    it('should pass shallow disabled prop', () => {
good eye, have fixed this

2024-06-11 09:13 UTC, maxinteger approved these changes

2024-06-11 09:59 UTC, merged