feat: add link role
momentum-design/momentum-react-v2 pull request #500
Opened 2024-06-14 07:23 UTC by jiwang7

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

- Add role for ButtonHyperLink component to allow it to SR as a link;
- Add package —— @react-aria/link
- update package version —— @react-aria/utils 3.24.1

*The full description of the changes made in this request.*

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-533449
*Links to relevent resources.*
src/components/ButtonHyperlink

2024-06-14 08:59 UTC, maxinteger requested changes

2024-06-14 08:59 UTC, maxinteger commented on src/components/ButtonHyperlink/ButtonHyperlink.constants.ts
> +export type roleType = 'button' | 'link';
this must be defined in the `ButtonHyperlink.types.ts`

2024-06-14 08:59 UTC, maxinteger commented on src/components/ButtonHyperlink/ButtonHyperlink.types.ts
> +export interface Props extends myProps {
you can extends multiple interfaces, no need for the extra type

```suggestion
export interface Props extends AiaLinkProps, AriaButtonProps<'a'> {
```

2024-06-17 01:56 UTC, jiwang7 commented on src/components/ButtonHyperlink/ButtonHyperlink.constants.ts
> +export type roleType = 'button' | 'link';
fixed

2024-06-18 06:01 UTC, jiwang7 commented
This draft change mix a button and a link. I will create another component to handle link button. Thanks for your review～

2024-06-18 06:01 UTC, closed without merging