fix(PopoverNext): pass zIndex param to tippy, allow ariaLabel param to override default labelling
momentum-design/momentum-react-v2 pull request #503
Opened 2024-06-15 21:50 UTC by lismith2-cisco

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

*The full description of the changes made in this request.*
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505185
https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/5917

This is used for the positioning-only trigger for webex assistant. zIndex puts the assistant response popover slightly behind the webex assistant control popover. Added to MenuTrigger, just because other style-related props are. ariaLabel provides a label directly, as the positioning-only trigger cannot be used as aria-labelledby.

# Links

*Links to relevent resources.*

2024-06-17 10:21 UTC, cscheffauer requested changes
looking good, 2 small comments

2024-06-17 10:21 UTC, cscheffauer commented on src/components/Popover/Popover.types.ts
> +  ariaLabel?: string;
there are attribute unit tests missing for the aria-label change

2024-06-17 10:21 UTC, cscheffauer commented on src/components/Popover/Popover.types.ts
> +   * Aria label for the popover. By default, the popover will be labelled by the triggerComponent.
maybe worth adding here to the comment to only use this ariaLabel in edge cases, like when its not possible to have discernible text on the trigger component (for example the trigger is something else, a different aria-label needs to be passed in when having multiple popovers attached to the same trigger, e.g.).

2024-06-17 16:48 UTC, torgeadelin commented on src/components/Popover/Popover.tsx
> +      'aria-labelledby': ariaLabel ? undefined : triggerComponentId,
to make props testing easier, i would love to only append if `aria-labelledby` ariaLabel is defined, instead of passing undefined when `ariaLabel` is falsy.

2024-06-17 16:49 UTC, torgeadelin commented on src/components/Popover/Popover.tsx
> +      'aria-labelledby': ariaLabel ? undefined : triggerComponentId,
this will prevent prop testing like this:
```js
expect(btn.props()).toEqual({
  ...
  "aria-labelledby": undefined,
})
```

2024-06-18 11:07 UTC, lismith2-cisco commented on src/components/Popover/Popover.types.ts
> +  ariaLabel?: string;
oops

2024-06-18 11:10 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +      'aria-labelledby': ariaLabel ? undefined : triggerComponentId,
sure it was just easier this way, but I can change it if you think it will help

2024-06-18 11:12 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +      'aria-labelledby': ariaLabel ? undefined : triggerComponentId,
I think when I've seen similar before, it considers an unset key to be equal to an explicitly undefined key though

2024-06-26 16:56 UTC, lismith2-cisco commented on src/components/Select/Select.tsx
>    const state = useSelectState(props);
this file is just lint changes due to merge

2024-06-26 17:00 UTC, lismith2-cisco commented on src/components/Popover/Popover.types.ts
> +  ariaLabel?: string;
added unit tests

2024-06-26 17:01 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +      'aria-labelledby': ariaLabel ? undefined : triggerComponentId,
changed

2024-06-27 15:46 UTC, cscheffauer approved these changes

2024-06-27 16:00 UTC, merged