feat: add Link component
momentum-design/momentum-react-v2 pull request #508
Opened 2024-06-19 08:30 UTC by jiwang7

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

- New Link component
- implement by react-aria/link useLink
- add storybook and test file 
 
*The full description of the changes made in this request.*

# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-533449
*Links to relevent resources.*

2024-06-20 10:15 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  isWithIcon?: boolean;
I suggest this name:
opensNewTab?: boolean

2024-06-20 10:15 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  iconProps?: Partial<IconPrpos>;
typo in IconPrpos

2024-06-20 10:15 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +  );
missing: aria-label for the link and the link+icon. Let's research what is the best and conventional way of doing this? should the aria-label be on the div container wrapper? or in each individual element?

I suggest:
1. Add a property called 'opensNewTabIndicatorAriaLabel'?: string
2. const linkId = id passed from props || uuiid generated like popover component does
3. In the a tag, add an id prop = {linkId}
4. In the a tag, add an aria-labelledby. if !opensNewTab, then `aria-labelledby = {linkId}`; otherwise, if opensNewTabIndicatorAriaLabel, then `aria-labelledby  = ${linkId} ${opensNewTabIndicatorAriaLabel}`

2024-06-20 10:33 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +        {isWithIcon && <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />}
This icon is an informative icon (it conveys important meaning that is not explicitly visible in the screen) and non-sr users wouldn't know what it means. We would need to add a Tooltip it that with the content: {opensNewTabIndicatorLabel}

Wrap the icon on a ghost button circle to allow the tooltip to trigger on hover.

Add an uuid as id to the button circle. 
const iconId = uuid.v4()

2024-06-20 10:43 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +        {isWithIcon && <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />}
tooltip should only be there if opensNewTabIndicatorLabel is defined, otherwise we risk an empty tooltip appearing on screen

2024-06-20 10:44 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +        {isWithIcon && <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />}
![image](https://github.com/momentum-design/momentum-react-v2/assets/56999622/7cfbd83c-2af6-4178-a74b-1c8a5a6e2b74)
check this tooltip for example from https://equalizedigital.com/accessibility-checker/link-opens-new-window-or-tab/#:~:text=Links%20that%20open%20new%20windows,link%20in%20the%20current%20tab.

2024-06-21 13:50 UTC, JudyZhuHz commented on src/components/Link/Link.types.ts
> +  isWithIcon?: boolean;
I think isWithIcon is good, because this parameter is to distinguish whether to add an icon after the text.
For example, if the link not need open a new tab, don't need add pop-out icon after the text.

2024-06-25 02:20 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +  );
fixed but wait tooltip component update

2024-06-27 01:36 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +  );
Tested, it works already

2024-07-03 14:40 UTC, cscheffauer requested changes
Tested locally - multiple issues:
- When opening it in storybook, i am trying to focus to it: i don't see the FocusRing appearing at all 
- The inverted variant should be removed completely, since the colors there are definitely not meeting the contrast ratio specs needed for accessibility.

2024-07-03 14:40 UTC, cscheffauer commented on src/components/Link/Link.style.scss
> +    margin-left: 5px;
all our spacing etc should be in `rem`, not px

2024-07-05 00:57 UTC, jor-row commented on src/components/Link/Link.types.ts
> +  isWithIcon?: boolean;
But the reason we are adding this is because accessibility says if it opens in a new tab it should always have an icon, no? So ```opensNewTab``` makes more sense, or at least make it clear what icon it is. ```isWithIcon``` is too generic when the icon is hard coded and not changeable.

2024-07-05 13:28 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  opensNewTabIndicatorLabel?: string;
After discussing with Christoph, this Link should also accept the case in which the element is semantically a Link, but visibly a Button or MenuItem (we would send our own styling through props to make it look like a button)

For this reason, the tooltip could say: a) "Opens a new tab" only or b) the Button label + "Opens a new tab". 

So, we should change the name of this prop to 'tooltipContent?: string'

2024-07-05 13:28 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  opensNewTabIndicatorLabel?: string;
Additionally, we would need to add another prop called 'tooltipType' which is of type tooltipType (you can get that from Tooltip component's types), and that way the consumer can specify if this tooltip is the entire label of the link or only the description of the link.
type: 'label' | 'description' | 'none'

2024-07-05 13:28 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +export { Example, States, LinkWithIcon };
Following my other comment, we should add a story where the link look like a button pill and a button circle

2024-07-05 13:28 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +export { Example, States, LinkWithIcon };
Note: when the link looks like a button circle, there is no need to add an icon of 'new tab', so hasIcon: true in this case

2024-07-05 15:56 UTC, maxinteger requested changes

2024-07-05 15:56 UTC, maxinteger commented on src/components/Link/Link.tsx
> +  delete mutatedProps.disabled;
you can "extract" the `disabled` value in line 12, so you do not need to delete the property here

2024-07-05 15:56 UTC, maxinteger commented on src/components/Link/Link.tsx
> +                title={title}
you can make this code more DRY if you put all the common props of `<a>` into an an object and use here and for the other `<a>` in line 61

2024-07-05 15:56 UTC, maxinteger commented on src/components/Link/Link.tsx
> +              >
Please add `rel="noopener noreferrer` to external links.

More info here: 
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Maybe we can add an option to turn it off since most of our link pointing to Cisco sites, but either way this must be the default

2024-07-05 15:56 UTC, maxinteger commented on src/components/Link/Link.tsx
> +        {opensNewTabIndicatorLabel && (
Please use the `target` prop value for check is it an external link or not

for example:
```ts
const isExternalLinkl = props.target === '_blank';
```

probably you can drop the `Tooltip` when there is no `opensNewTabIndicatorLabel`, but the icon and the `rel` must be set for all external links

2024-07-08 08:15 UTC, jiwang7 commented on src/components/Link/Link.style.scss
> +  &.focus {
<img width="1685" alt="image" src="https://github.com/momentum-design/momentum-react-v2/assets/133743423/7fefbcc8-e020-47ef-b4f8-b3771661567e">
I have tested, when I remove &:focus. It will display another color, which is from a:focus. So, I think we still need &:focus style.

2024-07-09 06:03 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  opensNewTabIndicatorLabel?: string;
ok, I will fix

2024-07-09 06:08 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +        {opensNewTabIndicatorLabel && (
Do I just need to add rel = 'noopener noreferrer' for <a> with target = '_blank'? or I should add rel = 'noopener noreferrer' as a common props for a tag.

2024-07-09 08:22 UTC, maxinteger commented on src/components/Link/Link.tsx
> +        {opensNewTabIndicatorLabel && (
Let's keep it simple, the way you implemented is good for now.

2024-07-09 09:02 UTC, maxinteger requested changes

2024-07-09 09:02 UTC, maxinteger commented on src/components/Link/Link.stories.tsx
> +const ButtonCircleLink = Template<LinkProps>(Link).bind({});
This is incorrect. `<a>` can not contain interactive element 

see [A tag HTML Spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element:~:text=The%20a%20element%20can%20be%20wrapped%20around%20entire%20paragraphs%2C%20lists%2C%20tables%2C%20and%20so%20forth%2C%20even%20entire%20sections%2C%20so%20long%20as%20there%20is%20no%20interactive%20content%20within%20(e.g.%2C%20buttons%20or%20other%20links).%20This%20example%20shows%20how%20this%20can%20be%20used%20to%20make%20an%20entire%20advertising%20block%20into%20a%20link%3A)

2024-07-09 09:22 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  hasIcon?: boolean;
We already have a props named hasIcon, which is like `hideExternalLinkIcon`, we can hide the icon by setting `hasIcon = false`. And We can set IconProps = { name: 'xxx'} to set another icon. I think it is flexible enough.

2024-07-09 13:29 UTC, nataliadelmar commented on src/components/Link/Link.stories.args.ts
> +  type: {
'tooltipType' should be the name of it

2024-07-09 13:29 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +const ButtonCircleLink = Template<LinkProps>(Link).bind({});
correct: we have a button circle and pill requirement, but that means we will have to recreate it from scratch and not use ButtonCircle or ButtonPill as children of this Link. This way:
```
const ButtonCircleLink = Template<LinkProps>(Link).bind({});

ButtonCircleLink.args = {
  href: 'https://www.webex.com/',
  target: '_blank',
  tooltipContent: 'opens a new tab',
  type: 'description',
  children: (
    <div style={{// all the styling this div needs to become a circle, with fixed dimensions, with fixed var colors, display: flex, center-allign}}>
      <Icon name="chat-group" autoScale={150} />
    </div>
  ),
};

```

2024-07-09 13:29 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +  children: <ButtonPill>example</ButtonPill>,
Same here: w have to recreate the buttonPill from scratch and not use ButtonPill as children of this Link. This way:
```
const ButtonPillLink = Template<LinkProps>(Link).bind({});

ButtonPillLink.args = {
  href: 'https://www.webex.com/',
  target: '_blank',
  tooltipContent: 'opens a new tab',
  type: 'description',
  children: (
    <div style={{// all the styling this div needs to become a pill, with fixed dimensions, with fixed var colors, display: flex, center-allign}}>
      <Text>Go to Download page</Text>
      <Icon name="chat-group" autoScale={150} />
    </div>
  ),
};

```

2024-07-09 13:29 UTC, nataliadelmar commented on src/components/Link/Link.style.scss
> +  &.focus {
for some reason, that mdl token is winning the race, please debug why; we shouldn't be falling into mdl (momentum-design-legacy) tokens anymore

2024-07-09 13:29 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  hasIcon?: boolean;
Do we always use target="_blank" when we are opening a new tab in Cantina?

2024-07-10 00:55 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  children: <ButtonPill>example</ButtonPill>,
I misunderstood the requirement. I will fix it.

2024-07-11 02:19 UTC, jiwang7 commented on src/components/Link/Link.style.scss
> +  &.focus {
About two issues @cscheffauer  mentioned before https://github.com/momentum-design/momentum-react-v2/pull/508#pullrequestreview-2156164854.
1. In Link component. We should set `href` props, if we don't set `href`, it can't be focused. I have added `href` in every storybook example. And it can be focused already.
2.we have conversation in acc marmot space. The inverted style is needed.
So, could you please take a book at these changes. Thank you!

2024-07-11 10:49 UTC, maxinteger commented on src/components/Link/Link.types.ts
> +  hasIcon?: boolean;
Ok, we can keep the prop, but:
- when it is not set and `target=_blank` => DO show the icon
- when it is not set and it is a normal link =>  DON'T show the icon
- otherwise show the icon based on the `hasIcon` values

BTW I think we should use a more explicit name, ex. `hasExternalLinkIcon` or something similar

2024-07-12 06:01 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  hasIcon?: boolean;
I accept we should use `hasExternalLinkIcon`. But for target to effect displaying icon, I think it is out of bounds of target. Target should just control open link ways. It is not its responsibility. I think we should make `hasExternalLinkIcon` single-purpose.

2024-07-12 09:24 UTC, maxinteger commented on src/components/Link/Link.types.ts
> +  hasIcon?: boolean;
I think the only reasonable use case for the "pop-out" icon is when the link is opening on a new tab which only happens with the `target=_blank". Also it is a requirement for A11y.

If the default visibility of the icon is not depend on the `target` then the consumer must remember to set both `target` and `hasExternalLinkIcon` which is error prone. 

The only reason why we need the `hasExternalLinkIcon` is because in some rare case consumer might want to hide the icon even when the link is external.

@nataliadelmar What do you think?

2024-07-15 14:54 UTC, nataliadelmar commented on src/components/Link/Link.style.scss
> +  &.focus {
acc style is needed to to a legacy style that sets color to --mdl-textColorHyperling-hover (legacy color). We don't want to remove that line because we are afraid of breaking existing code that relies on that line to get the blue color. We also cannot put !important in our css rule because we need states to change depending on if they are on hover, normal or pressed

2024-07-15 16:00 UTC, nataliadelmar requested changes

2024-07-16 01:35 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +                    <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />
In this change, when `hasExternalLinkIcon = false` and `target === 'blank'`, the Icon still exist. According to your description. Maybe we should implement like this？

`
let isShowIcon = false;

  if(hasExternalLinkIcon === undefined) {
    props.target === '_blank';
    isShowIcon = true;
  } else if (hasExternalLinkIcon) {
    isShowIcon = true;
  } else {
    isShowIcon = false;
  }
  
  isShowIcon && <Icon className={STYLE.icon} scale={16} name="pop-out" {...externalLinkIconProps} />
  `

2024-07-16 01:48 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  iconProps?: Partial<IconProps>;
ok

2024-07-16 01:54 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  iconProps: { id: 'icon' },
Yes, i can remove it. By the way if we don't have href in Link, we can't focus Link.

2024-07-16 01:58 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  iconProps: { id: 'icon' },
In LinkHasIcon storybook example, If we don't have `target`, It's no different from a tag. So basically I think we need `target: '_blank' `

2024-07-16 02:52 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  children: (
fixed

2024-07-16 02:52 UTC, jiwang7 commented on src/components/Link/Link.style.scss
> +.md-link-button-wrapper {
fixed

2024-07-16 02:52 UTC, jiwang7 commented on src/components/Link/Link.style.scss
> +.md-link-ButtonPillLink {
fixed

2024-07-16 02:53 UTC, jiwang7 commented on src/components/Link/Link.stories.args.ts
> +        summary: 'IconNextProps',
fixed

2024-07-16 02:54 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  tooltipContent?: string;
fixed

2024-07-16 10:26 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +                    <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />
I see your point; the last else is redundant because of the first line is already setting it to false:
```
let isShowIcon = false;

if(hasExternalLinkIcon === undefined && props.target === '_blank') {
    isShowIcon = true;
} else if (hasExternalLinkIcon) {
    isShowIcon = true;
}

isShowIcon && <Icon className={STYLE.icon} scale={16} name="pop-out" {...externalLinkIconProps} />
```

2024-07-16 10:43 UTC, nataliadelmar commented on src/components/Link/Link.types.ts
> +  tooltipContent?: string;
Please also update the description of all properties on stories.args.ts with these latest description. For example, the description of tooltipContent is still 'Used for tooltip content'

2024-07-16 10:43 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +delete ButtonCircleLink.argTypes.disabled;
double disabled delete; the last delete should be of the inverted prop, which is not relevant for the button circle:
```
delete ButtonCircleLink.argTypes.children;
delete ButtonCircleLink.argTypes.disabled;
delete ButtonCircleLink.argTypes.inverted;
```

2024-07-16 10:43 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +delete ButtonPillLink.argTypes.disabled;
double disabled delete; the last delete should be of the inverted prop, which is not relevant for the button circle:
```
delete ButtonPillLink.argTypes.children;
delete ButtonPillLink.argTypes.disabled;
delete ButtonPillLink.argTypes.inverted;
```

2024-07-16 10:43 UTC, nataliadelmar commented on src/components/Link/Link.stories.tsx
> +  target: '_blank',
missing an href otherwise the link is not focusable

2024-07-16 10:49 UTC, nataliadelmar approved these changes

2024-07-17 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  tooltipType: 'description',
fixed

2024-07-17 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  tooltipType: 'description',
added

2024-07-17 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +  target: '_blank',
added

2024-07-17 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +delete ButtonPillLink.argTypes.disabled;
fixed

2024-07-17 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +delete ButtonCircleLink.argTypes.disabled;
fixed

2024-07-17 02:07 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +  tooltipContent?: string;
fixed

2024-07-17 02:07 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +                    <Icon className={STYLE.icon} scale={16} name="pop-out" {...iconProps} />
fixed

2024-07-17 11:31 UTC, cscheffauer approved these changes

2024-07-18 09:27 UTC, maxinteger requested changes

2024-07-18 09:27 UTC, maxinteger commented on src/components/Link/Link.stories.tsx
> +delete States.argTypes.inverted;
nitpicking: instead of `delete` please use `pick` or `omit` from lodash

2024-07-18 09:27 UTC, maxinteger commented on src/components/Link/Link.tsx
> +  }
nitpicking: this could be simplified like this:

```suggestion
  let isShowIcon = hasExternalLinkIcon === true || isExternalLink;
```

2024-07-18 09:27 UTC, maxinteger commented on src/components/Link/Link.unit.test.tsx
> +    it('should have rel when target is provided', async () => {
issue: please check the external icon as well, it should be there when the target is _blank

Also, you need one more test for the `target=_blank` and `hasExternalLinkIcon=false`

2024-07-19 01:34 UTC, jiwang7 commented on src/components/Link/Link.tsx
> +  }
In this simplified change, `hasExternalLinkIcon` can't force hide it.
If `hasExternalLinkIcon  = false` but `props.target === '_blank'`, it will display icon.
So, I think we can't simple like this. I will replace `props.target === '_blank'` to `isExternalLink `

2024-07-19 02:06 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +delete States.argTypes.inverted;
fixed

2024-07-19 02:06 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx
> +    it('should have rel when target is provided', async () => {
fixed

2024-07-19 09:19 UTC, maxinteger commented on src/components/Link/Link.tsx
> +  }
you are right, I missed that case

2024-07-19 09:20 UTC, maxinteger approved these changes
Looks great!

2024-07-22 05:30 UTC, merged