fix(TooltipPopoverCombo): fix the aria-labelledby of the popover when the button has a tooltip
momentum-design/momentum-react-v2 pull request #512
Opened 2024-06-20 12:29 UTC by lismith2-cisco

# Description

This fixes the aria-labelledby chaining issue to provide the correct label for the popover in TooltipPopoverCombo, by allowing Popover to have aria-labelledby overridden and allowing Tooltip to have labelId overridden. This fix removes some duplicate and now-unnecessary ids.

This also removes the extra aria-haspopup which was incorrectly being added to the tooltip itself in TooltipPopoverCombo.

This also fixes Tooltip treating type none the same as type description.

2024-06-20 13:01 UTC, cscheffauer requested changes
had a quick look, not tested locally yet

2024-06-20 13:14 UTC, jor-row commented on src/components/Popover/Popover.tsx
> -    id: interactive ? triggerComponentId : triggerComponent.props?.id || id,
That was only added last week here https://github.com/momentum-design/momentum-react-v2/pull/496/files to fix something that is now using TooltipPopoverCombo

Given that I don't think this is will break things in Cantina

2024-06-20 15:16 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> -    id: interactive ? triggerComponentId : triggerComponent.props?.id || id,
Popover component still allows to pass in id prop, and it will be used as id for the popover (ModalContainer). The change made the popover and the button have the same id, which should never happen.

2024-06-24 07:45 UTC, cscheffauer requested changes

2024-06-24 07:45 UTC, cscheffauer commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
useState doesn't have any effect here, since there is no setter `setAriaLabelledBy` used. You can just write it without the useState.

2024-06-24 07:45 UTC, cscheffauer commented on src/components/Tooltip/Tooltip.tsx
>              // we add `aria-labelledby` manually, see below
this comment is not applicable anymore

2024-06-24 07:45 UTC, cscheffauer commented on src/components/Tooltip/Tooltip.types.ts
> +  labelId?: string;
nitpick: prop types should ideally have proper TSDocs, otherwise its a bit hard for consumers in Cantina to understand the meaning of the props, especially the prop `type`

2024-06-25 09:26 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
This is to only call uuidv4 once and store the value between renders.

2024-06-25 09:26 UTC, lismith2-cisco commented on src/components/Tooltip/Tooltip.tsx
>              // we add `aria-labelledby` manually, see below
this comment is atill applicable

2024-06-25 09:27 UTC, lismith2-cisco commented on src/components/Tooltip/Tooltip.types.ts
> +  labelId?: string;
this is true, I will add it (it wasn't me that added type though!)

2024-06-26 10:13 UTC, nataliadelmar commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
you can use useRef to persist the value across renders; I think TextInput component is doing that

2024-06-26 10:29 UTC, nataliadelmar commented on src/components/Tooltip/Tooltip.types.ts
> +  'aria-haspopup'?: string;
is the type of this prop something we can import from aria?

2024-06-26 10:29 UTC, nataliadelmar commented on src/components/Tooltip/Tooltip.tsx
> +      ...(isDescription && { 'aria-describedby': labelId }),
what about changing the name of labelId to 'tooltipId' to not make it label-exclusive?

2024-06-26 10:44 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
I am aware that we are, but I don't think we should be, the useRef docs say "Do not write or read ref.current during rendering... If you have to read or write something during rendering, use state instead." see 'Pitfall', https://react.dev/reference/react/useRef

2024-06-26 11:40 UTC, lismith2-cisco commented on src/components/Tooltip/Tooltip.tsx
> +      ...(isDescription && { 'aria-describedby': labelId }),
changed to labelOrDescriptionId since it isn't applied to the actual tooltip

2024-06-26 11:41 UTC, lismith2-cisco commented on src/components/Tooltip/Tooltip.types.ts
> +  'aria-haspopup'?: string;
Yes! Done.

2024-06-26 11:42 UTC, lismith2-cisco commented on src/components/Tooltip/Tooltip.types.ts
> +  labelId?: string;
added docs

2024-06-26 12:15 UTC, nataliadelmar commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
"Do not write or read ref.current during rendering, except for [initialization.]"(https://react.dev/reference/react/useRef#avoiding-recreating-the-ref-contents)

2024-06-26 12:17 UTC, nataliadelmar commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
this isn't inside the render, it is in intialization

2024-06-26 16:01 UTC, lismith2-cisco commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
back to the controversial useState

2024-06-27 08:09 UTC, cscheffauer commented on src/components/Popover/Popover.tsx
> +  const [ariaLabelledby] = useState(
@lismith2-cisco what u mentioned from the docs i think is not applicable - the sentence "Do not write or read ref.current during rendering" to me is a note that ref.current doesn't automatically re-render your dom, which means you shouldn't use useRef if your UI depends on it. But since in our case we only want to store the initial value of the uuidv4 and persist it between re-renders, i think we should use useRef.
Also from the same docs:
"If your component needs to store some value, but it doesn’t impact the rendering logic, choose refs."
https://react.dev/learn/referencing-values-with-refs#when-to-use-refs

For the sake of consistency across our code base my suggestion would be to use useRef, same as in all the other occurrences. I would be happy to discuss this further and would recommend you providing more information on how we should do it (with pros and cons) and have a convention for it moving forward - since there is no convention in place, my vote is to stick to consistency.

2024-06-27 08:16 UTC, cscheffauer requested changes

2024-06-27 08:16 UTC, cscheffauer commented on src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap
> +    <button>
why has the button the aria-haspopup removed here? i can see in the unit tests that aria-haspopup is passed in and in my opinion the button should still have aria-haspopup - is this a bug?

2024-06-27 08:35 UTC, lismith2-cisco commented on src/components/TooltipPopoverCombo/TooltipPopoverCombo.unit.test.tsx.snap
> +    <button>
The component that it renders still has aria-haspopup, it's just set by Popover and passed through Tooltip instead of being set in TooltipPopoverCombo. You can see it in line 258/436

2024-06-27 09:22 UTC, cscheffauer approved these changes

2024-06-27 14:14 UTC, merged