Fix: fix submenu customized menuitem click crash issue
momentum-design/momentum-react-v2 pull request #523
Opened 2024-06-28 05:34 UTC by junhao3268

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description
![image](https://github.com/momentum-design/momentum-react-v2/assets/142187938/aa297661-9d65-4eb8-9891-882dafbec3f5)

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2024-06-28 14:17 UTC, maxinteger requested changes

2024-06-28 14:17 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.constants.ts
> +  TITLE: 'title',
List item should not have default title and it never user anyway, please remove this line.

2024-06-28 14:17 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> +        title={title}
I do not understand why do you use `title` attribute here. And looks like it does not related to the title of this PR. Could you please share the Jira issue link?

2024-07-01 01:08 UTC, junhao3268 commented on src/components/ListItemBase/ListItemBase.tsx
> +        title={title}
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-505149
we discussed with @nataliadelmar about the visual indicator in last catchups, decide to add Icon after the list item (link like a button), and add a extra title for hover tooltip to further display the visible indicator, so we need to add the titlt prop to solve the type error.
![image](https://github.com/momentum-design/momentum-react-v2/assets/142187938/ff27e512-6c4e-4d54-af73-d54770e69b86)

2024-07-01 01:30 UTC, junhao3268 commented on src/components/ListItemBase/ListItemBase.tsx
> +        title={title}
> I do not understand why do you use `title` attribute here. And looks like it does not related to the title of this PR. Could you please share the Jira issue link?

We thought this part was also related to link bucket, so we put it in this pr, we should move this part to another PR.

2024-07-01 14:10 UTC, maxinteger approved these changes

2024-07-01 14:10 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> +        title={title}
@junhao3268 yes, even if it is the same bucket it should be separated PR if it is not related to the original problem which is "fix submenu customized menuitem click crash issue" in this case.

I see you already moved your the title changes. Thank you

2024-07-01 14:11 UTC, maxinteger requested changes
sorry I have to add the `validated` label first :)

2024-07-01 14:18 UTC, maxinteger approved these changes
Looks good!

2024-07-03 00:43 UTC, merged