feat(reaction-aria-toolbar): changes
momentum-design/momentum-react-v2 pull request #530
Opened 2024-07-05 10:33 UTC by torgeadelin

# Description

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2024-07-08 18:29 UTC, torgeadelin commented on src/components/Avatar/Avatar.unit.test.tsx
> +import { action } from '@storybook/addon-actions';
This file has been changed due to husky pre commit issue that was merged before....

2024-07-09 10:45 UTC, Coread commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +            if (providedRef) {
question: Have you considered what happens if you were to pass a non-function ref into this component?

2024-07-09 11:24 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +            if (providedRef) {
I was initially unsure about merging two non-functional refs but discovered it can be done using `useImperativeHandle` by explicitly specifying which methods to merge. I could consider overriding the ref by default for non func refs or providing a custom merge function with useImperativeHandle, but I feel like is too much work for now. 

After testing this approach in our current use cases, it was working ok.

2024-07-09 12:14 UTC, maxinteger requested changes

2024-07-09 12:14 UTC, maxinteger commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +        case ariaToolbarContext?.orientation === 'horizontal' ? 'ArrowLeft' : 'ArrowUp':
We could make AriaToolbar more accessible if we use left/right and up/down for both orientation

[WCAG Tooltip pattern](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/) also suggest that.

2024-07-09 15:26 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +          }
fixed

2024-07-09 15:29 UTC, torgeadelin commented on src/components/AriaToolbar/AriaToolbar.types.ts
> +  ariaToolbarItemsSize: number;
I would prefer to keep it as is, because it follows the same pattern we have for List.
If we really want to refactor this, we should do it in both components at the same time, but it feels a little bit too out of scope for my changes.

2024-07-09 15:30 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +          ariaToolbarContext?.setCurrentFocus(index);
addressed

2024-07-09 15:30 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +          }
addressed

2024-07-09 15:30 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +              if (typeof providedRef === 'function') {
removed

2024-07-09 15:30 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +          }
refactored

2024-07-09 16:17 UTC, torgeadelin commented on src/components/AriaToolbarItem/AriaToolbarItem.tsx
> +            if (providedRef) {
I have added `useProvidedRef` util which handles both cases.

2024-07-09 20:13 UTC, maxinteger approved these changes

2024-07-09 20:13 UTC, maxinteger commented on src/utils/useProvidedRef.ts
> +  if (providedRef && typeof providedRef !== 'function') {
nitpicking: `providedRef &&` is not necessary because of `typeof`

2024-07-09 20:13 UTC, maxinteger commented on src/utils/useProvidedRef.ts
> +    if (providedRef) {
nitpicking: `if (providedRef) {` is not needed because of `typeof` in the next line

2024-07-11 14:37 UTC, merged