fix: re-factor toggletip tip
momentum-design/momentum-react-v2 pull request #539
Opened 2024-07-15 14:02 UTC by maxinteger

# Description

- used interactive popover instead of non-interactive with live aria
- added close button

# Links
[
*Links to relevent resources.*
](issue: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-502450)

2024-07-16 12:42 UTC, nataliadelmar commented on src/components/Toggletip/Toggletip.stories.tsx
> +  ),
I cannot see the X button
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b5f8018d-c6c0-4d35-87e6-9bda59914d04">

2024-07-16 13:30 UTC, maxinteger commented on src/components/Toggletip/Toggletip.stories.tsx
> +  ),
Yes, I deliberately left it out. The Sainsbury's design system does not have it, and when I navigated with VO it was much easier (less steps). Maybe because it is not intractable either.

Please check with VO and let me know if you think the close button is still needed

2024-07-17 10:01 UTC, nataliadelmar commented on src/components/Toggletip/Toggletip.tsx
> +    };
delete

2024-07-18 12:00 UTC, torgeadelin requested changes

2024-07-18 12:00 UTC, torgeadelin commented on src/components/Toggletip/Toggletip.unit.test.tsx
> +    // after tabbing away, toggletip should be still open
Question: does this mean the user always has to either click away or press escape to close it?

2024-07-18 13:01 UTC, maxinteger commented on src/components/Toggletip/Toggletip.unit.test.tsx
> +    // after tabbing away, toggletip should be still open
Good point, I checked the other implementations and there the popover disappear onBlur, so I added back the this functionality

2024-07-18 13:01 UTC, maxinteger commented on src/components/Toggletip/Toggletip.tsx
> + * - the label of the close button
fixed

2024-07-18 13:01 UTC, maxinteger commented on src/components/Toggletip/Toggletip.tsx
> + * - the spacing to avoid overflow of the content with the close button
fixed

2024-07-18 15:15 UTC, torgeadelin commented on src/components/Toggletip/Toggletip.unit.test.tsx
> +    // after tabbing away, toggletip should be still open
comment should probably change too now that you've added blur?

2024-07-18 15:41 UTC, maxinteger commented on src/components/Toggletip/Toggletip.unit.test.tsx
> +    // after tabbing away, toggletip should be still open
:facepalm:

2024-07-18 15:54 UTC, torgeadelin approved these changes
lgtm

2024-07-19 09:10 UTC, merged