feat: LinkNext component
momentum-design/momentum-react-v2 pull request #549
Opened 2024-07-23 06:28 UTC by jiwang7

# Description
<img width="874" alt="Snipaste_2024-06-20_15-32-27" src="https://github.com/momentum-design/momentum-react-v2/assets/133743423/87508625-56a4-42e4-a7ca-f874184ec654">

- New Link component
- implement by react-aria/link useLink
- add storybook and test file 
 
# Links
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-533449
*Links to relevent resources.*
https://react-spectrum.adobe.com/react-aria/useLink.html

2024-07-23 06:37 UTC, jiwang7 commented
The PR is merged before, but revert because of error message of cantina. These error message is fixed.So commit again.

2024-07-23 10:38 UTC, torgeadelin requested changes

2024-07-23 10:38 UTC, torgeadelin commented on __mocks__/@react-aria/link/index.js
> +}
add new line

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.stories.tsx
> +    <div
Why not use ButtonCircle?

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.stories.tsx
> +    <div
Why not use ButtonPill?

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.style.scss
> +  // need to overwright focus style and src
typo: overwrite

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.types.ts
> +
nitpick: can we add newline between all prop definitions?

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.unit.test.tsx
> +import React from 'react';
Issue: When running the tests, there are a bunch of warnings in the console, could we please fix them too?
I saw some related to invalid DOM attributes being passed to DOM elements.

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.unit.test.tsx
> +        onPress: expect.any(Function)
Issue: As I mentioned above, this is probably wrong, onPress should not be present on a `<a>` element, it's not a valid DOM property.

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.unit.test.tsx
> +      component.props().onPress({
Note/Nitpick: If I'm not mistaken, there might be a util function somewhere that does this.

2024-07-23 10:38 UTC, torgeadelin commented on src/components/Link/Link.unit.test.tsx.snap
> +        onPress={[MockFunction]}
Issue: Same issue as the one mentioned in the unit test, elementType and onPress are not valid DOM attributes.

2024-07-23 10:38 UTC, torgeadelin commented on src/storybook/helper.stories.argtypes.ts
> +const commonAriaLink = {
Nitpick: Saw a bunch of formatting issues in this file, could you please format it?

2024-07-23 10:38 UTC, torgeadelin commented on src/storybook/helper.stories.argtypes.ts
> +  onPress: {
Issue: I'm not sure onPress are needed here. We might have a common arg type object with all these, not sure -- but I would remove them from here.

2024-07-23 10:38 UTC, torgeadelin commented on src/storybook/helper.stories.argtypes.ts
> +  onKeyUp: {
I'd remove everything from above until the previous PR comment I left.

2024-07-23 10:38 UTC, torgeadelin commented on src/storybook/helper.stories.argtypes.ts
> +  onKeyUp: {
Including onKeyUp

2024-07-23 10:38 UTC, torgeadelin commented on __mocks__/@react-aria/link/index.js
> +}
I'm not sure if this is going to fix the unit test failures in Cantina.
Do we have a separate PR that mocks this in Cantina as well?

2024-07-24 01:11 UTC, jiwang7 commented on __mocks__/@react-aria/link/index.js
> +}
Yes, I have added a unit test mock file in Cantina. https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/6164/files

2024-07-24 01:14 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +    <div
`<a>` can not contain interactive element. We had a conversation in last merged PR.

2024-07-24 01:14 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +    <div
same as ButtonCircle

2024-07-24 02:43 UTC, jiwang7 commented on src/components/Link/Link.style.scss
> +  // need to overwright focus style and src
fixed

2024-07-24 02:43 UTC, jiwang7 commented on src/components/Link/Link.types.ts
> +
fixed

2024-07-24 02:45 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx
> +import React from 'react';
Yeah. I think it is duo to with react-aria/link mock file. updated and fixed.

2024-07-24 02:45 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx
> +        onPress: expect.any(Function)
removed

2024-07-24 02:51 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx
> +      component.props().onPress({
Should I add another util for onPress? In useLink, when we pass `onPress` and useLink will export `onClick`. I updated mock file already. I think it is fine now.

```
linkProps: mergeProps(domProps, routerLinkProps, {
      ...interactionHandlers,
      ...linkProps,
      'aria-disabled': isDisabled || undefined,
      'aria-current': props['aria-current'],
      onClick: (e: React.MouseEvent<HTMLAnchorElement>) => {
        pressProps.onClick?.(e);
        if (deprecatedOnClick) {
          deprecatedOnClick(e);
          console.warn('onClick is deprecated, please use onPress');
        }

        // If a custom router is provided, prevent default and forward if this link should client navigate.
        if (
          !router.isNative &&
          e.currentTarget instanceof HTMLAnchorElement &&
          e.currentTarget.href &&
          // If props are applied to a router Link component, it may have already prevented default.
          !e.isDefaultPrevented() &&
          shouldClientNavigate(e.currentTarget, e) &&
          props.href
        ) {
          e.preventDefault();
          router.open(e.currentTarget, e, props.href, props.routerOptions);
        }
      }
    })
```

2024-07-24 02:52 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx.snap
> +        onPress={[MockFunction]}
fixed

2024-07-24 02:52 UTC, jiwang7 commented on src/storybook/helper.stories.argtypes.ts
> +const commonAriaLink = {
fixed

2024-07-24 02:54 UTC, jiwang7 commented on src/storybook/helper.stories.argtypes.ts
> +  onPress: {
I'm not sure too. I add these props because they are props of useLink. So, we should delete them all?

2024-07-24 02:55 UTC, jiwang7 commented on src/storybook/helper.stories.argtypes.ts
> +  onKeyUp: {
As uncertain as above.

2024-07-24 09:36 UTC, torgeadelin commented on src/components/Link/Link.stories.tsx
> +    <div
Is this because we need a link that looks like button pill or button circle?

2024-07-24 09:37 UTC, torgeadelin commented on src/components/Link/Link.stories.tsx
> +    <div
I really don't think this is the best approach. We should add logic inside ButtonPill and ButtonCircle to handle links as well...

2024-07-24 09:40 UTC, torgeadelin commented on src/components/Link/Link.unit.test.tsx
> +      component.props().onPress({
Sorry, I was refering to https://github.com/momentum-design/momentum-react-v2/blob/dedb8420c51ca8da4cf23f8618a2c7d399d28a65/test/utils.ts#L29

2024-07-24 09:41 UTC, torgeadelin commented on src/storybook/helper.stories.argtypes.ts
> +  onPress: {
I don't think we're adding these apart from button components...
I would remove them 🤷🏻‍♂️

2024-07-25 02:21 UTC, jiwang7 commented on src/storybook/helper.stories.argtypes.ts
> +  onPress: {
yeah, I remove them except onPress, I think onPress is still useful

2024-07-25 02:54 UTC, jiwang7 commented on src/components/Link/Link.unit.test.tsx
> +      component.props().onPress({
added

2024-07-25 11:19 UTC, torgeadelin commented on src/components/Link/Link.stories.tsx
> +    <div
Also extend the types from LinkNext on top of ButtonPill types and respectively ButtonCircle types

2024-07-25 11:42 UTC, torgeadelin commented
Waiting for you to remove the stories, and then I will approve :)

2024-07-26 01:28 UTC, jiwang7 commented on src/components/Link/Link.stories.tsx
> +    <div
Yeah, I got it. removed these storybook.

2024-07-26 08:54 UTC, torgeadelin approved these changes

2024-07-29 01:04 UTC, merged