feat(accordion): pass props down to header button
momentum-design/momentum-react-v2 pull request #559
Opened 2024-07-31 14:33 UTC by gabrielchl

# Description

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2024-07-31 15:27 UTC, maxinteger requested changes

2024-07-31 15:27 UTC, maxinteger commented on src/components/Accordion/Accordion.types.ts
> +  buttonProps?: ButtonSimpleProps;
probably you want to `Omit` some of the button props which are already used, for example `aria-expanded` or `aria-controls`

2024-07-31 15:27 UTC, maxinteger commented on src/components/Accordion/Accordion.tsx
> +            {...buttonProps}
this could overwrite the `onClick` from the previous line, either you exclude the `onClick` or merge yours with the user specified one. In other components we used the later solution and merged the 2 handler

2024-07-31 23:06 UTC, maxinteger approved these changes

2024-07-31 23:06 UTC, maxinteger commented on src/components/Accordion/Accordion.types.ts
> +export type ButtonCustomProps = Required<Pick<ButtonSimpleProps, ButtonSimpleCustomPropKeys>> & {
Now it is a bit overcomplicated because inside the component we have full control on the values and we know what we want to pass to the button which has a type safe interface anyway. 

we need `ButtonAllowedProps` to make it clear to the consumer what props are valid

You can keep this change.

2024-07-31 23:06 UTC, maxinteger commented on src/components/Accordion/Accordion.style.scss
> +    gap: 0.5rem;
🙇 thanks for changing it to `ram`

2024-07-31 23:15 UTC, gabrielchl commented on src/components/Accordion/Accordion.style.scss
> +    gap: 0.5rem;
![Untitled](https://github.com/user-attachments/assets/47334ace-a7bb-4e05-92df-d2cc1b0b6ff1)

2024-08-01 11:33 UTC, torgeadelin approved these changes

2024-08-01 11:34 UTC, merged