feat: tree component
momentum-design/momentum-react-v2 pull request #566
Opened 2024-08-05 15:46 UTC by maxinteger

# Description

Add new Tree and TreeBaseNode components

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-548345

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.types.ts
> +   * Determines if the tree node is interactive (usually used as a header when false)
What do you mean with '(usually used as a header when false)' ? If the node is not interactive, it is probably a leaf node right?

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +    throw new Error('TreeNodeBase: nodeId prop is required.');
I think we do not throw error in Tree components. We normally console.warn(message), like we do here 
<img width="335" alt="image" src="https://github.com/user-attachments/assets/898519d8-77bf-4560-b0af-7ccf1094e557">

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +  useLayoutEffect(() => {
Is this for the case of having a tree component inside a popover? Do we have a use case for that? I can only think of calendar item popover, but curious if there is any other

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +          'TreeNodeBase: this component can only receive ListItemBaseSection as children.'
can only receive ListItemBaseSection or Text as children

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +        );
So, if children is an array, the only permitted cases are:
`[<ListItemBaseSection />, <ListItemBaseSection/ >, <ListItemBaseSection>]`
`[<ListItemBaseSection />, <ListItemBaseSection/ >]`
`[<Text />, <Text/ >, <Text>]`
`[<Text />, <Text/ >]`
 
Why do we want to make this that restrictive? why not simply rendering the children inside the node?

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +    treeContext?.shouldItemFocusBeInset || DEFAULTS.SHOULD_ITEM_FOCUS_BE_INSET;
On TreeNodeBase.tsx I see there is a prop called shouldItemFocusBeInset. Why are we not using this for this line too?

2024-08-14 16:38 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +  const treeNodeTabIndex = getTreeNodeBaseTabIndex(nodeId, treeContext.activeNodeId, interactive);
shouldnt this const be called treeNodeBaseTabIndex?

2024-08-15 09:11 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.types.ts
> +   * Determines if the tree node is interactive (usually used as a header when false)
good point. This was a leftover from the ListItemBase, but we do not really need this

I removed the `interactive` and `isDisabled` props for now because if we can disable nodes then it will effect on the navigation. 

Let's postpone this functionality until we really need it

2024-08-15 09:21 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +  useLayoutEffect(() => {
Since this solution works in list and you already mentioned a possible use case, I keep this code

2024-08-15 09:25 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +        );
I re-phrased the warning.

Valid children are:
- Single, eg.: `<div/>`, `</>` (React.Frament)
- Multiple eg: `[<Text />, <Text/ >]

The message is misleading, `[<ListItemBaseSection />, <ListItemBaseSection/ >]` is not allowed, instead you have to use: `[<ListItemBaseSection />]` and put the multiple child into `ListItemBaseSection`

2024-08-15 09:27 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +  const treeNodeTabIndex = getTreeNodeBaseTabIndex(nodeId, treeContext.activeNodeId, interactive);
Since it is a private variable of the component, the prefix is not needed. I reduced the name to `tabIndex` only

2024-08-15 09:27 UTC, maxinteger commented on src/utils/navigation.ts
> +  'a[href], button, input, textarea, select, details, [tabindex]:not([tabindex="-1"]';
Nice catch!

2024-08-15 09:37 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +    treeContext?.shouldItemFocusBeInset || DEFAULTS.SHOULD_ITEM_FOCUS_BE_INSET;
Good point, we do not need the `shouldItemFocusBeInset` on the TreeNodeBase, removed
(also renamed it in the Tree component's porps)

2024-08-15 09:47 UTC, nataliadelmar commented on src/components/Tree/test.utils.ts
> +  isOpenByDefault: boolean = undefined,
isn't this the same as to say `isOpenByDefault?: boolean`

2024-08-15 09:47 UTC, nataliadelmar commented on src/components/Tree/test.utils.ts
> +  isOpenByDefault: boolean = undefined,
do we need the default to undefined?

2024-08-15 09:47 UTC, nataliadelmar commented on src/components/Tree/Tree.utils.ts
> +const TREE_NAVIGATION_ITERATION_LIMIT = 1_024;
this should be in constants file

2024-08-15 09:47 UTC, nataliadelmar commented on src/components/Tree/Tree.utils.ts
> +export const toggleActiveNode = (tree: FlatTree, nodeId: TreeNodeId): TreeNodeId => {
the name of this util is confusing, it doesn't get the active node, it uses the passed nodeid and toggles it. So maybe a name like `toggleNode` would be better

2024-08-15 09:47 UTC, nataliadelmar commented on src/components/Tree/Tree.utils.ts
> +  if (node) {
should we log any warning if the node doesn't exist?

2024-08-15 10:00 UTC, maxinteger commented on src/components/Tree/test.utils.ts
> +  isOpenByDefault: boolean = undefined,
it is the same as `isOpenByDefault?: boolean` but it is more explicit this way, and following the patter in the next line `children: Array<TreeNode> = []`

2024-08-15 10:16 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +export const toggleActiveNode = (tree: FlatTree, nodeId: TreeNodeId): TreeNodeId => {
Actually we do not event need this function

2024-08-15 10:29 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +  if (node) {
I added a check to `getNextActiveNode`, not sure about the rest of the case. Some time is valid to have an undefined result for example when we reach the root which has not parent

2024-08-15 13:11 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.stories.docs.mdx
> +After the node selected the user can use the `Tab` key to select the first, second, etc. interactive element.
'After the node is **focused** (not selected), the user can ...'

2024-08-15 13:11 UTC, nataliadelmar commented on src/components/TreeNodeBase/TreeNodeBase.stories.docs.mdx
> +When the last interactable element is selected, the next tab will move the focus to the next interactable
'When the last interactable element is **focused**, the next tab will move the focus to the next interactable...'

2024-08-15 13:11 UTC, nataliadelmar commented on src/components/Tree/Tree.tsx
> +        'aria-selected': isSelected,
We shouldn't set aria-selected if activeNode === node.id (that is, if the node is simply focused).

2024-08-15 15:01 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +   * @see {@link https://codepen.io/maxinteger/pen/zYVNabV Example of a nested and flat tree}
question: not sure if we're allowed to do this? (license issue)

2024-08-15 15:02 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +   * Note: it does not change the visibility of the root node.
suggestion: add another comment saying this only excludes the tree root from keyboard navigation

2024-08-15 15:05 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +  getNodeDetails: (id: TreeNodeId) => FlatTreeNode;
question: does this work for both flat and non-flat trees? do we always return flat tree node?

2024-08-15 15:06 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +  removeExternalToggleFunction: (id: TreeNodeId) => void;
question: I don't understand the purpose of these 2. Are these just callbacks when we remove and add nodes to the tree or?

2024-08-15 15:07 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +  for (let counter = 0; ; counter++) {
issue: there's an extra `;`.

2024-08-15 15:10 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +  for (let counter = 0; next; counter++) {
question: is `next` in the middle the condition for the loop, meaning that as long as next is defined?

2024-08-15 15:12 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +    if (counter > TREE_NAVIGATION_ITERATION_LIMIT) {
question: we do support 1K participants, and if we're gonna use this in the participants list, we might reach the limit.. but not sure how realistic that is.

Any particular reason you added it or?

2024-08-15 15:12 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +  let current = tree.get(activeNodeId);
question: what is activeNodeId? is it the currently selected node in the tree?

2024-08-15 15:19 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +export const getNextActiveNode = (
suggestion: maybe rename this func, there's another function above `findNextTreeNode `, and in the comment it says ` * Find the next active tree node based on the current active node`.  I can see that the imlpementation of this one is actually different, it actually handles the keyboard nav.

2024-08-16 00:07 UTC, gabrielchl commented on src/components/Tree/Tree.utils.ts
> + * Travers the tree and convert it to a map between the node id and the node
```suggestion
 * Traverse the tree and convert it to a map between the node id and the node
```

2024-08-16 09:04 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.types.ts
> -  shouldItemFocusBeInset?: boolean;
the prop never used in the ListItemBase we always get the value from the list context. I just checked in Cantina this prop appear only once on the List component, so I can not see how is this break the code

2024-08-16 09:06 UTC, maxinteger commented on src/components/Tree/Tree.stories.args.ts
> +  shouldNodeFocusBeInset: {
It is used in the TreeNodeBase same way as we use it in the List/ListItemBase

2024-08-16 09:07 UTC, maxinteger commented on src/components/Tree/Tree.tsx
> +    shouldNodeFocusBeInset,
It is passed to the tree context and then used in the TreeNodeBase

2024-08-16 09:10 UTC, maxinteger commented on src/components/Tree/Tree.tsx
> +    throw new Error('Tree must have at least one child when excludeTreeRoot is true');
I can change that, but then it will fail a few lines later with a more generic error, because it tries to read an `id` of an undefined child.

I would prefer the more descriptive error then the generic one

2024-08-16 09:18 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +   * @see {@link https://codepen.io/maxinteger/pen/zYVNabV Example of a nested and flat tree}
So, what do you recommend? I can create a GitHub gist, or I can just copy the HTML and add it to the story docs, or I can add here as well

BTW the link is pointing to my CodePan :)

2024-08-16 09:20 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +   * Note: it does not change the visibility of the root node.
It is already in the first line of the comment, but I added the "keyboard" word to make it more accurate

2024-08-16 09:24 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +  getNodeDetails: (id: TreeNodeId) => FlatTreeNode;
Yes, this can be misleading. There are 2 things
1) The tree can be rendered in the DOM flat or nested (up to the consumer)
2) Our Tree component represents the tree data structure as a "FlatTree", it is more efficient to navigate in it when you need to find the next active node. (consumer has no control over this)

These are un-related to each other. Most of the time the internal representation is completely hidden for the consumer, except here. 

Let me know if you have better name for this type to make it less confusing.

2024-08-16 09:44 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +export const getNextActiveNode = (
`findNextTreeNode` is just a utility function which is not exported and used only in the `getNextActiveNode` function. I can update the docs to make it more descriptive, but I am also open for name suggestions

2024-08-16 09:44 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +  let current = tree.get(activeNodeId);
Yes, the `activeNodeIs` is the id of the currently focused node

2024-08-16 09:49 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +  for (let counter = 0; ; counter++) {
`for` loop must have two `;`. This is an unconditional loop, where we decided about the exit condition in the body. I could use the `while(true)`, but then I have to define the counter in a separated line and the update as well, that mean 2 additional lines!!! :D

2024-08-16 09:49 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +  for (let counter = 0; next; counter++) {
yes

2024-08-16 18:24 UTC, torgeadelin commented on src/components/ListItemBase/ListItemBase.types.ts
> -  shouldItemFocusBeInset?: boolean;
Aaa gotcha. I guess it's safe to remove in that case. I haven't realised it was propagating through context.

2024-08-16 18:25 UTC, torgeadelin commented on src/components/Tree/Tree.tsx
> +    throw new Error('Tree must have at least one child when excludeTreeRoot is true');
Ok, we can leave the throw I then.

2024-08-16 18:26 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +   * @see {@link https://codepen.io/maxinteger/pen/zYVNabV Example of a nested and flat tree}
Maybe gist? I know it points to your own codepad, but ai think the issue still applies regardless.

2024-08-20 11:37 UTC, nataliadelmar approved these changes

2024-08-20 11:37 UTC, nataliadelmar commented on src/components/Tree/Tree.types.ts
> +  treeStructure: TreeRoot;
TreeRoot is of type TreeNode, which does not have a flat structure. What is we want a flat structure?

2024-08-20 11:37 UTC, nataliadelmar commented on src/components/Tree/Tree.types.ts
> +  setVirtualTreeNodeOpenState?: (id: TreeNodeId, isOpen: boolean) => void;
you have a type set for this called ToggleTreeNode

2024-08-20 11:37 UTC, nataliadelmar commented on src/components/Tree/Tree.types.ts
> +  toggleTreeNode: (id: TreeNodeId) => void;
we have a type called ToggleTreeNode that is a function with id and isOpen as params. It is confusing that one toggleTreeNode only needs id and the other needs both id and isOpen stated, don't you think?

2024-08-20 12:15 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +  treeStructure: TreeRoot;
flat tree is the internal representation of the tree inside the Tree component, it is more efficient to use the flattened tree for navigation then the normal nested tree.

Please note, it is independent from the `isRenderedFlat` because it is about how the consumer built the tree in the DOM

The consumer should not know about this internal representation.

2024-08-20 12:17 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +  setVirtualTreeNodeOpenState?: (id: TreeNodeId, isOpen: boolean) => void;
Unfortunately there are different. The `isOpen` parameter is option in the `ToggleTreeNode` and required in `setVirtualTreeNodeOpenState`

2024-08-20 16:54 UTC, torgeadelin reviewed
some small issues still, but looking great otherwise

2024-08-20 16:54 UTC, torgeadelin commented on src/components/Tree/Tree.types.ts
> +   * @see {@link https://codepen.io/maxinteger/pen/zYVNabV Example of a nested and flat tree}
We're still using codepen, but I'm not going to block it for that.

2024-08-20 16:54 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +  for (;;) {
suggestion: `while (true) {}`

2024-08-20 16:54 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +
nitpick: unnecessary new line

2024-08-20 16:54 UTC, torgeadelin commented on src/components/Tree/Tree.utils.ts
> +export const toggleTreeNodeRecord = (
question: what is the difference between this and `toggleTreeNode` from https://github.com/momentum-design/momentum-react-v2/blob/44edce188dfbcb694ef449ed8675454a75ef7fb7/src/components/Tree/Tree.tsx#L38

2024-08-20 16:54 UTC, torgeadelin commented on src/components/TreeNodeBase/TreeNodeBase.style.scss
> +  &[data-interactive='true'] {
issue: you're missing interactive prop on the tree node base (you need to follow similar approach as we do in list item base), OR just remove it? Not sure we need `interactive` for tree node... but you never know..

2024-08-20 16:54 UTC, torgeadelin commented on src/components/TreeNodeBase/TreeNodeBase.style.scss
> +  &[data-interactive='true'] {
issue: I don't see any disabled state

2024-08-20 16:54 UTC, torgeadelin commented on src/components/TreeNodeBase/TreeNodeBase.style.scss
> +  &[data-interactive='true'] {
I've identified both of this issue from the storybook page of this component. I noticed you've used the template for pseudo states (praise!), and they're broken. The reason they are broken are because of the 2 issues abvove.

2024-08-20 16:54 UTC, torgeadelin commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +        {...treeNodePressProps}
suggestion: we should allow the pass in the `..rest` props to this as long as they're valid tags. Not sure what the best approach for this is.. We normally just pass in ...rest BUT I've noticed a lot in Cantina and mrv2 that a lot of times we pass in invalid DOM attributes to the HMTL elements, which result in warnings in unit test output and console.logs in browser.

2024-08-20 16:54 UTC, torgeadelin commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +        {...treeNodePressProps}
This is helpful if we need to pass any aria attributes from the consumer side.

2024-08-20 16:55 UTC, torgeadelin requested changes
some small issues still, but looking great otherwise

2024-08-22 07:24 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +   * @see {@link https://codepen.io/maxinteger/pen/zYVNabV Example of a nested and flat tree}
Removed the link and I added the examples to the storybook docs

2024-08-22 07:26 UTC, maxinteger commented on src/components/Tree/Tree.types.ts
> +  getNodeDetails: (id: TreeNodeId) => FlatTreeNode;
FYI, I renamed this and some other types to make it less confusing for devs and consumers

2024-08-22 07:28 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +  for (;;) {
ESLint does not like it, `no-constant-condition`, I do it anyway, `while(true)` is more readable then `for(;;)`

2024-08-22 07:32 UTC, maxinteger commented on src/components/Tree/Tree.utils.ts
> +export const toggleTreeNodeRecord = (
in `toggleTreeNodeRecord` the `isOpen` parameter required while in the `toggleTreeNode` is optional. Also, `toggleTreeNodeRecord` is used internally meantime `toggleTreeNode` is part of the Tree context API

2024-08-22 07:45 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.style.scss
> +  &[data-interactive='true'] {
Nice catch, Tree node is interactive by default, at least for now. I removed the `&[data-interactive='true'] {`, but kept the rest.

2024-08-22 07:47 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.style.scss
> +  &[data-interactive='true'] {
yes, there is no disabled state fro the tree node at the moment. We can add it when it is needed.

2024-08-22 08:11 UTC, maxinteger commented on src/components/TreeNodeBase/TreeNodeBase.tsx
> +        {...treeNodePressProps}
fixed

2024-08-22 08:52 UTC, torgeadelin approved these changes

2024-08-22 11:26 UTC, merged