Spark 502431 search input aria controls expanded
momentum-design/momentum-react-v2 pull request #567
Opened 2024-08-06 00:00 UTC by peter7cole

# Description

- adds aria-controls and aria-expanded to SearchInput
- types and unit test

2024-08-06 00:05 UTC, peter7cole commented
I'm inclined to leave the formatting fixes in the test file, but am open to reverting them.

2024-08-06 00:08 UTC, peter7cole commented on src/components/SearchInput/SearchInput.unit.test.tsx
> +    });
this is the only real test change/addition

2024-08-08 13:24 UTC, peter7cole commented on src/components/SearchInput/SearchInput.unit.test.tsx
> +    });
the only new tests

2024-08-08 13:34 UTC, peter7cole commented on src/components/SearchInput/SearchInput.unit.test.tsx
> +    });
the only actual test additions

2024-08-08 14:12 UTC, chburket reviewed
just a comment about convention

2024-08-08 14:12 UTC, chburket commented on src/components/SearchInput/SearchInput.types.ts
> +  ariaControls?: string;
I know that is some cases, we allow all html attrs to be specified (...rest  - see List.tsx). Here it looks like we are allowing aria-controls specifically and we are camel-casing it.  Is there a standard way of doing this?

2024-08-08 20:10 UTC, robstax requested changes

2024-08-08 20:10 UTC, robstax commented on src/components/SearchInput/SearchInput.tsx
> +      aria-controls={controls}
couple things:
1. my understanding is that all of these attributes need to be on the `<input/>` itself on line 113.
2. we *only* want to add `aria-controls` and `aria-expanded` IF AND ONLY IF `isCombobox` is true. if it's not a combobox (`isCombobox` is false) we must not set the `aria-expanded` attribute at all. make sense?

2024-08-08 20:10 UTC, chrisadubois commented on src/components/SearchInput/SearchInput.unit.test.tsx.snap
> +      role="searchbox"
Shouldn't there be a snapshot with combobox=true?

2024-08-14 16:54 UTC, robstax approved these changes

2024-08-16 14:24 UTC, nataliadelmar commented on src/components/SearchInput/SearchInput.tsx
> +      {...inputProps}
do inputProps return any role? if yes, it might overwrite our `role={ARIA_ROLES.COMBOBOX}`

2024-08-16 14:24 UTC, nataliadelmar commented on src/components/SearchInput/SearchInput.types.ts
> +  controls?: string;
when passing props that will be using in aria-props, we are normally converting the aria-prop to camelCase.
`ariaControls?: string`
That way it is even more obvious that what are we intending to do with this value

2024-08-16 14:24 UTC, nataliadelmar commented on src/components/SearchInput/SearchInput.types.ts
> +  isExpanded?: boolean;
In the expanded case, I am happy to leave it as isExpanded. However, isExpanded only works for the Combobox case, not any other case like a Tooltip or simple explanation popover triggering from the Input. Because of this, it might be a good idea to change this prop to isComboboxExpanded?: boolean

2024-08-16 16:24 UTC, peter7cole commented on src/components/SearchInput/SearchInput.tsx
> +      {...inputProps}
inputProps doesn't contain a role value and this works as is, or we could cover the future possibility of it with
```javascript
{...{ ...inputProps, role: ARIA_ROLES.COMBOBOX }}
```

2024-08-16 18:35 UTC, merged