fix(Menu): horizontal keyboard navigation handling
momentum-design/momentum-react-v2 pull request #576
Opened 2024-08-09 20:44 UTC by johnsoter13

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description
In order to have consistent screen reader behavior. We determined that all single selection popouts should be menus, in order to do this we need to enable horizontal keyboard navigation for menus, similar to lists. 
*The full description of the changes made in this request.*
- Refactored horizontal keyboard handling into reusable hook
- added horizontal keyboard handling to menu/menu section
- added tests

# Links
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549363](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549363)
*Links to relevent resources.*

2024-08-13 20:06 UTC, maxinteger requested changes
Looks good, I have only 2 questions

2024-08-14 14:37 UTC, johnsoter13 commented on src/components/Menu/Menu.types.ts
> +  orientation?: ListOrientation
I was asked to convert the In-meeting layout to a single selection menu. 

![Screenshot 2024-08-14 at 10 36 49 AM](https://github.com/user-attachments/assets/cbe0cb25-df90-4f42-b680-5b00dd865458)

The top half of this menu is horizontal

2024-08-14 14:37 UTC, maxinteger commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +    setContext: (newFocus: any) => void;
Why did you used `any` for the `newFocus` type instead of `number`?

2024-08-14 17:27 UTC, johnsoter13 commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +    setContext: (newFocus: any) => void;
Ah I will change this. Pretty sure I get this from somewhere else in the code and didn't bother to change it

2024-08-14 20:22 UTC, johnsoter13 commented on src/components/Menu/Menu.types.ts
> +  orientation?: ListOrientation
I have it set to vertical as a default

2024-08-16 08:46 UTC, maxinteger approved these changes
Nice one!

2024-08-16 14:38 UTC, merged