feat(sr-announcer): move sr announcer from cantina to mrv2
momentum-design/momentum-react-v2 pull request #588
Opened 2024-08-23 11:32 UTC by nataliadelmar

# Description
Moving SR Announcer from Cantina to MRV2 for other components in Cantina to reuse it. This component causes a screen reader to announce a message when required.

2024-08-23 13:51 UTC, martroos requested changes
I think it would be worth attaching the `announce` function to the default export, other than that everything looks fine.

2024-08-23 13:51 UTC, martroos commented on src/index.js
> +  announce,
suggestion: It might be cleaner to attach the `announce` function to the `ScreenReaderAnnouncer` component, as is done with the `NotificationSystem` - this means that it needs no extra description to make it clear that it is associated with the announcer, and keeps everything more modular.

2024-08-23 13:51 UTC, martroos commented on src/components/index.ts
> +export { default as ScreenReaderAnnouncer, announce } from './ScreenReaderAnnouncer';
suggestion: Assuming you go with my suggestion of attaching `announce` to the `ScreenReaderAnnouncer`, the `announce` export won't be needed here.

2024-08-23 13:51 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.tsx
> +export const announce = (options: AnnounceOptions, announcerIdentity = DEFAULTS.IDENTITY): void => {
thought: Previously this was defined _after_ the `ScreenReaderAnnouncer` component - this was to avoid any chance of confusion with the `announce` defined on line 94. You get away with it due to function (block) scoping, so it's not a big deal, but something to keep in mind in future.

2024-08-23 13:51 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx
> +    jest.clearAllTimers();
nitpick: I _think_ calling `useFakeTimers` before each test implicitly clears all timers - not a big deal, but I suspect the clear isn't needed.

2024-08-23 13:51 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.tsx
> +export default ScreenReaderAnnouncer;
suggestion: For modularity / namespacing, don't export `announce` above, instead do:

```ts
ScreenReaderAnnouncer.announce = announce;
```

And obviously update relevant places that call it. This means that if we want to expose other methods related to this in future (like the `clear` function`), we can.

2024-08-27 08:24 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
> +type Body = string | ReactNode;
nitpick: I _think_ `ReactNode` includes strings, so probably doesn't need to be explicitly set here.

2024-08-27 08:24 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
> +  body: Body;
question: Why is this not just text? Since this (the screen reader) is an invisible component, what is the benefit of allowing non-text items here? Not suggesting it's wrong, just trying to understand the use case.

2024-08-27 08:25 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.unit.test.tsx
> +  beforeAll(() => {
suggestion: I think this does want to be `beforeEach` still.

2024-08-27 08:56 UTC, nataliadelmar commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
> +type Body = string | ReactNode;
that is true 
<img width="792" alt="image" src="https://github.com/user-attachments/assets/e15b8d21-954d-44ef-a01b-7f34e0de6480">

Fixed

2024-08-27 09:01 UTC, nataliadelmar commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
> +  body: Body;
ohh because sometimes what we want to announce is already a constructed react node on the screen, which we can clone and pass that clone to the sr announcer instaed of passing a stringified version of it.

**Example:** Search input. 
When a search result is empty, we might display something like:
```
<>
<h2>Oh no!!</h2>
<p>We have not been able to find any results</p>
</>
```
We also want the SR to announce "Oh no We have not been able to find any results". So instaed of having to stringify that node, we just pass it directly to the SRAnnouncer

Same for a Toggletip content that does not have simple text inside but has sth like this:
<img width="829" alt="image" src="https://github.com/user-attachments/assets/ea3618dc-9f42-43bf-bdcd-6cb123d338f7">

2024-08-27 09:12 UTC, martroos commented on src/components/ScreenReaderAnnouncer/ScreenReaderAnnouncer.types.ts
> +  body: Body;
Ah ok, so the content of the toggle tip is passed in as `children`, so it is more effort to stringify them (or demand that they are provided in string form as well). One thing to note is this makes it possible for people to nest a live section within a live section (if someone provided `<div aria-live-"assertive">Some text to announce</div>`), but this is completely avoidable by the developer.

2024-08-27 13:41 UTC, merged