feat(listitembase): allow empty items
momentum-design/momentum-react-v2 pull request #600
Opened 2024-08-30 16:14 UTC by Coread

# Description

Allow lists to render correctly when some elements are empty

# Links

*Links to relevent resources.*

2024-09-02 09:26 UTC, martroos submitted a review, later dismissed

2024-09-02 09:26 UTC, martroos commented on src/components/ListItemBase/ListItemBase.tsx
> +  useEffect(() => {
issue: This breaks looping lists if one of the ends is considered empty - maybe not a huge issue, but it doesn't behave as expected.

2024-09-02 09:26 UTC, martroos commented on src/components/ListItemBase/ListItemBase.tsx
> +  }, [focus, lastCurrentFocus, listContext.listSize]);
suggestion: I think this should include `indexItem` and probably `listContext.setCurrentFocus` (the latter is admittedly the result of a `useState` so not hugely important, but this module doesn't really know what it is based on the context).

2024-09-02 09:26 UTC, martroos commented on src/components/ListItemBase/ListItemBase.tsx
> +        }
suggestion: Some comments to explain what is happening would be useful - with some analysis you can see that you are actively keeping items at the (direction dependent) previous item if this item is at one of the ends, and otherwise skipping it, but it's not necessarily simple at a glance (the comment would have also made it clear that looping wouldn't work any more).

2024-09-02 09:26 UTC, martroos commented on src/components/List/List.stories.tsx
> +      <List noLoop listSize={7}>
issue: This is a list of length 9 (looping will happen to work going down because this number is wrong!).

2024-09-02 09:26 UTC, martroos commented on src/components/ListItemBase/ListItemBase.style.scss
> +    white-space: nowrap;
nitpick: This is another instance of the ["visually hidden"](https://www.a11yproject.com/posts/how-to-hide-content/) styling which is in various parts of the library, would be nice to mixin / include this in scss terms.

2024-09-03 08:10 UTC, Coread commented on src/components/ListItemBase/ListItemBase.style.scss
> +    white-space: nowrap;
as far as I know, we don't currently have shared scss between the new components?

2024-09-03 08:11 UTC, Coread commented on src/components/List/List.stories.tsx
> +      <List noLoop listSize={7}>
fixed

2024-09-03 08:11 UTC, Coread commented on src/components/ListItemBase/ListItemBase.tsx
> +        }
this is now fixed

2024-09-03 08:13 UTC, Coread commented on src/components/ListItemBase/ListItemBase.tsx
> +  }, [focus, lastCurrentFocus, listContext.listSize]);
I've added the full list of dependencies to the useEffect

2024-09-03 08:13 UTC, Coread commented on src/components/ListItemBase/ListItemBase.tsx
> +  useEffect(() => {
this is now fixed

2024-09-10 09:14 UTC, maxinteger requested changes

2024-09-10 09:14 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.types.ts
> +  onBlur?: (e: React.FocusEvent<Element>) => void;
`Props` should extends `FocusProps` and `FocusWithinProps` instead of manually adding the props. JSDocs should be moved to the original definition.

2024-09-10 09:14 UTC, maxinteger commented on src/components/List/List.stories.tsx
> +        <ListItemBase data-exclude-focus-children size="auto" itemIndex={0} key={0}>
What is the expected behaviour for `data-exclude-focus` and `data-exclude-focus-children`? I can see they might be excluded from intractable element selection, but it is not prevent the browser focus the element with Tab.

I check this story, and I can focus on button 1 with Tab.

2024-09-10 09:34 UTC, maxinteger commented on src/hooks/useFocusState.ts
> +      }
nitpicking: this can be simplified to:
```suggestion
    props.onFocusWithin?.(...args);
```
because the arrow functions `this` is `undefined` anyway

2024-09-22 18:57 UTC, Coread commented on src/components/List/List.stories.tsx
> +        <ListItemBase data-exclude-focus-children size="auto" itemIndex={0} key={0}>
I've removed the exclude-focus-children as this was covered by your recent changes. data-exclude-focus is used by the Aria-Toolbar. The toolbar only wants to expose one of its tabable buttons to preserve focus order when you tab forward/backward from within a ListItemBase. It sets data-exclude-focus on all but the first one so the first element is the only one to ever be in the tab order.

2024-09-22 19:36 UTC, Coread commented on src/components/ListItemBase/ListItemBase.types.ts
> +  onBlur?: (e: React.FocusEvent<Element>) => void;
I'm now extending this definition using the props from react-aria. Note that it isn't as simple as extending directly, because I haven't added support for all of FocusProps or all of FocusWithinProps

2024-09-22 19:37 UTC, Coread commented on src/hooks/useFocusState.ts
> +      }
I've changed this

2024-09-30 17:22 UTC, jor-row requested changes

2024-09-30 17:22 UTC, jor-row commented on .eslintrc.js
On press of root nodes in tree the component is crashing
https://github.com/user-attachments/assets/6669c4dc-24d2-4d74-83b9-0c3edbd861c2

2024-09-30 17:22 UTC, jor-row commented on .eslintrc.js
Menu SelectionGroups are broken (and a unit test is failing because of it!) Keyboard nav doesn't work at all for them in this PR but is fine on master
https://github.com/user-attachments/assets/e378db7f-e767-436e-b929-4906a31d183a

2024-10-02 13:09 UTC, jor-row approved these changes
Tested locally and changes look good to me. A few small comments

2024-10-03 09:59 UTC, maxinteger approved these changes

2024-10-03 09:59 UTC, maxinteger commented on src/components/ListItemBase/ListItemBase.tsx
> +    // if (!!listSize && currentFocus >= listSize) {
please remove this comment

2024-10-03 10:58 UTC, jor-row commented on src/components/ListItemBase/ListItemBase.tsx
> +    // if (!!listSize && currentFocus >= listSize) {
Done

2024-10-03 10:58 UTC, jor-row commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +    supressFocus?: boolean;
done

2024-10-03 10:59 UTC, jor-row commented on src/components/AriaToolbar/AriaToolbar.tsx
> +    // When the toolbar is rendered inside a list, only item in the toolbar
done

2024-10-03 10:59 UTC, jor-row commented on src/components/List/List.stories.tsx
> +);
fixed

2024-10-03 11:41 UTC, closed without merging