fix(Menu): Keyboard navigation fix for menus with multiple sections
momentum-design/momentum-react-v2 pull request #624
Opened 2024-09-05 23:54 UTC by johnsoter13

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

- Updated Menu to no longer use hook. Using the same navigation strategy as Lists doesn't quite work for Menus since useMenu handles specific logic for us like skipping disabled items and section headers when we use arrow keys
- Updated sub components back to original state since we no longer need the hook to navigate

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2024-09-06 09:04 UTC, shnaaz commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
Why this change was required, we are not using this hook in Menu or MenuSection

2024-09-06 09:19 UTC, maxinteger requested changes
Sorry but I do not understand what issue you try to fix on the menu navigation.

Next time please add the issue link and the fill the description section of the PR.

2024-09-06 09:19 UTC, maxinteger commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
Please undo this change, `orientation` and `listSize` are critical to calculate the next focus item.

The consumer of this hook can set the default value for `orientation`, also define the `listSize`

2024-09-06 09:19 UTC, maxinteger commented on src/components/MenuTrigger/MenuTrigger.unit.test.tsx.snap
Please re-generate the snapshot file for the MenuTrigger and commit it

2024-09-06 09:19 UTC, maxinteger commented on src/components/MenuSection/MenuSection.types.ts
> -  orientation?: ListOrientation
As far as I know there is at least one example for horizontal menu in cantina. Please make sure this is not breaking Cantina

2024-09-06 09:19 UTC, maxinteger commented on src/components/MenuSection/MenuSection.tsx
> +      <ListContext.Provider value={{}}>
Since Menus are a list like components from navigation point of view, so I do not understand why the ListContext has no value at this point

2024-09-06 09:23 UTC, nataliadelmar approved these changes

2024-09-06 09:23 UTC, nataliadelmar commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
not needed
useOrientationBasedKeyboardNavigationProps is only used once from Lists now, and there you always will send listSize (as it is a required prop on List) and orientation is defaulted to VERTICAL, so this change to make them optional here is not needed :)

2024-09-06 09:29 UTC, nataliadelmar commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
I pushed a fix to fix this one bit

2024-09-06 09:46 UTC, torgeadelin commented
I have a feeling this is the revert PR??

2024-09-06 09:47 UTC, torgeadelin commented
Can we please use the revert feature and then create a new PR with the actual fix? @johnsoter13

2024-09-06 10:01 UTC, nataliadelmar commented
> Sorry but I do not understand what issue you try to fix on the menu navigation.
> 
> Next time please add the issue link and the fill the description section of the PR.

Before using the kb-navigation hook in menus, a menu was able to have sections inside that were navigated using arrow keys (across sections).

2024-09-06 10:02 UTC, nataliadelmar commented
> I have a feeling this is the revert PR??

it is the revert pr, but we want to keep things from that pr in master, which is why this new pr was made

2024-09-06 12:35 UTC, johnsoter13 commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
Yeah I changed this back, this was some testing I was doing

2024-09-06 12:36 UTC, johnsoter13 commented on src/components/MenuSection/MenuSection.types.ts
> -  orientation?: ListOrientation
I did, we no longer need to specify orientation on the MenuSection level. Can all be handled in Menu.

2024-09-06 12:37 UTC, johnsoter13 commented on src/components/MenuSection/MenuSection.tsx
> +      <ListContext.Provider value={{}}>
This is just reverting the Menu back to it's original state. I thought we needed the context defined in order to do orientation based navigation but that's not the case

2024-09-06 12:39 UTC, johnsoter13 commented on src/hooks/useOrientationBasedKeyboardNavigation.ts
> +  orientation?: ListOrientation;
I thought I pushed a change to this but I left it in local accidentally. This was just from some testing I was doing and forgot to change it back

2024-09-06 12:44 UTC, johnsoter13 commented
Sorry for the confusion @torgeadelin and @maxinteger . @nataliadelmar  and I discussed that reverting the old PR and pushing a new one was not the direction we wanted to go, but I didn't communicate that when I made this PR. 

But as Natalia said, we wanted to keep the old PR in master. This work isn't a full revert, just an adjustment to support kb navigation across sections while also supporting orientation prop for Menus

2024-09-09 10:34 UTC, shnaaz approved these changes
Also tested with Cantina, seems fine.

2024-09-09 10:55 UTC, maxinteger approved these changes

2024-09-09 10:56 UTC, merged