fix: add high contrast colors, mainly around active/selected states
momentum-design/momentum-react-v2 pull request #674
Opened 2024-10-17 12:21 UTC by dominiccarrington

# Description

This PR introduces the following changes, only for Windows High Contrast:
- All icons have a background of Canvas and the stroke/fill as CanvasText
  - This fixes all icons without having to mess with component's colors in mrv2 and Cantina
- Added SelectedItem system colors to active state of RadioSimple
- Added SelectedItem system colors to active state of ListItemBase
- Added SelectedItem system colors to selected state of TreeNodeBase
- Added AccentColor system colors to Badge

# Links
Jira Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506028
Confluence: https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=546082395
System Color Definition: https://drafts.csswg.org/css-color/#css-system-colors

2024-10-22 14:58 UTC, lismith2-cisco requested changes

2024-10-22 14:58 UTC, lismith2-cisco commented on src/components/SpaceRowContent/SpaceRowContent.tsx
> +          <Text
auto linting commited by accident?

2024-10-22 14:58 UTC, lismith2-cisco commented on src/components/Badge/Badge.style.scss
> +      background-color: AccentColor !important;
I assume all the !importants are because it doesn't work otherwise?

2024-10-22 14:58 UTC, lismith2-cisco commented on src/components/Badge/Badge.style.scss
> +    @media (forced-colors: active) {
Large badge is invisible on chrome

2024-10-22 14:58 UTC, lismith2-cisco commented on src/components/RadioSimple/RadioSimple.style.scss
> +  @media (forced-colors: active) {
RadioSimple focus state doesn't work at all. Hopefully this, plus the focus examples on list item base and tree node base can be fixed by matching the logic of the high contrast focus ring to the normal one.

2024-10-24 12:31 UTC, dominiccarrington commented on src/components/Badge/Badge.style.scss
> +    @media (forced-colors: active) {
This is annoyingly because Chrome doesn't support the AccentColor system color unless you enable a flag. https://caniuse.com/mdn-css_types_color_system-color_accentcolor_accentcolortext

2024-10-31 10:30 UTC, dominiccarrington commented on src/components/Badge/Badge.style.scss
> +      background-color: AccentColor !important;
Yep!

2024-10-31 15:30 UTC, lismith2-cisco requested changes

2024-10-31 15:30 UTC, lismith2-cisco commented on src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss
> +    // TODO: Check whether all of these !importants are required
did you mean to leave this in?

2024-10-31 15:30 UTC, lismith2-cisco commented on src/components/ButtonCircleToggle/ButtonCircleToggle.style.scss
> +    &[data-selected='true'][data-selected='true'] {
please leave a comment about why you are doing this

2024-10-31 15:42 UTC, lismith2-cisco approved these changes

2024-10-31 16:25 UTC, merged