feat(link): warn if link opens in new tab but no tooltip or label for icon is provided
momentum-design/momentum-react-v2 pull request #710
Opened 2024-11-22 14:22 UTC by gabrielchl

# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

see title

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-582981

2024-11-27 18:23 UTC, dominiccarrington requested changes

2024-11-27 18:23 UTC, dominiccarrington commented on src/components/Link/Link.unit.test.tsx
suggestion:
Line 234: could you add a tooltipContent prop to silence the console warn

2024-11-27 18:23 UTC, dominiccarrington commented on src/components/Link/Link.unit.test.tsx
suggestion:
could you add a test to check that it outputs the warning

2024-11-27 18:23 UTC, dominiccarrington commented on src/components/ButtonPillLink/ButtonPillLink.unit.test.tsx.snap
issue: Overflow is broken
| pr | master |
| --- | --- |
| <img width="217" alt="image" src="https://github.com/user-attachments/assets/ae82c3df-741b-4a9b-affa-b413da0a8753"> | <img width="212" alt="image" src="https://github.com/user-attachments/assets/c9c4b4e1-1106-457d-b222-3050975307ce"> |

2024-11-27 18:23 UTC, dominiccarrington commented on src/components/Link/Link.tsx
>    return (
thanks for simplifying it

2024-11-28 12:17 UTC, nataliadelmar requested changes

2024-11-28 12:17 UTC, nataliadelmar commented on src/components/Link/Link.tsx
we should add a warn here:

```
if(isExternalLink && !hasExternalLinkIcon) {
      console.warn(
      'MRV2: The link opens a new tab and it has no external link icon indicating this. Please pass hasExternalLinkIcon: true to the icon'
}
```

2024-11-28 12:17 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +  if (isShowIcon && !tooltipContent && !externalLinkIconProps?.['aria-label']) {
we are allowing the developer to have an icon that is not labelled visibly, only with aria-label. So that violates one of the icon rules.

Maybe it could be:

```
const isShowExternalIcon = hasExternalLinkIcon || (hasExternalLinkIcon === undefined && isExternalLink);

if (isShowIcon && !tooltipContent) {
    console.warn(
      'MRV2: This link is external link, so an indicator icon will be shown next to it. All meaningful icons need a tooltip, so please pass tooltipContent="Opens a new tab" to the link'
    );
}
```

2024-11-28 12:17 UTC, nataliadelmar commented on src/components/Link/Link.tsx
> +        <Tooltip type={tooltipType} placement="bottom" triggerComponent={content}>
We should default our tooltipType to "description", so that the SR reads '{content of the link}, Opens a new tab, Link'. Maybe we should not even allow the user to pass a tootlipType so that this is the only allowed behaviour

2024-11-28 12:22 UTC, gabrielchl commented on src/components/Link/Link.tsx
if it's external link and hasExternalLinkIcon is undefined, it'll automatically render the icon
whether the icon is rendered is not solely based on the hasExternalLinkIcon prop

2024-11-29 15:29 UTC, dominiccarrington approved these changes

2024-11-29 16:33 UTC, nataliadelmar commented on src/components/Link/Link.tsx
gotcha! youre right!

2024-11-29 16:33 UTC, nataliadelmar commented on src/components/ButtonCircleLink/ButtonCircleLink.tsx
> -    tooltipType,
hmm Im not sure if I like this change; cause a ButtonCircle doesn't have any visible label so it may need the tooltip to label it. I know I suggested it, I wasn't thinking of the ButtonCircle case, sorry. We should default the tooltipType to 'description' in the Link component, but still allow the developer to send a tooltipType.

2024-11-29 16:33 UTC, nataliadelmar commented on src/components/ButtonCircleLink/ButtonCircleLink.tsx
> -    tooltipType,
I see in Cantina an error that, although not cause by this, could be causes by this if we remove this prop.

![image](https://github.com/user-attachments/assets/7f64dddb-6a90-465a-b188-f6474f6e8c5c)
Right now, that button has `aria-label="Meetings settings"` and `aria-describedby=a tootlip that says "Meetings settings (Opens a new tab)"`. That will make SR read "Meetings settings twice unless we continue allowing the developer to set the tooltip type to label (aria-label shouldn't have been passed to that ButtonCircleLink tbf.

2024-12-02 10:21 UTC, nataliadelmar approved these changes

2024-12-02 10:22 UTC, gabrielchl commented
waiting for current mrv2 bump to be completed before merging

2024-12-02 13:00 UTC, merged